### ISSUE TITLE
[SOLVED] Bug with Premium listing in Bender Theme

### ISSUE THREAD

**Issue by darmeth** [osclass/Osclass#1014]
There is an issue with Bender theme not displaying the currency symbol in Premium ads.

![555x](https://f.cloud.github.com/assets/5500687/1187874/74e53ce4-23a4-11e3-8789-c7c11ed68091.png)

To fix:

Go to \oc-content\themes\bender\loop-single-premium.php

And change this line:

```
<?php if( osc_price_enabled_at_items() ) { ?><span class="currency-value"><?php echo osc_format_price(osc_premium_price()); ?></span><?php } ?>    
```

To this:

```
<?php if( osc_price_enabled_at_items() ) { ?><span class="currency-value"><?php echo osc_premium_currency_symbol(), osc_format_price(osc_premium_price()); ?></span><?php } ?>    
```

**Comment by garciademarina** [comment]
fixed
