### ISSUE TITLE
[feature suggestion] deactivating of items in user panel

### ISSUE THREAD

**Issue by trains58554** [osclass/Osclass#102]
Hi 

I have made some changes to hDefines and item.php in the rood directory to add the functionality of letting the user deactivate their items. I though I would share this code with you and let you guys decide if you want to add it to the core.

This code I added to the hDefines.php file

``` php
/**
     * Gets url for deactivating an item
     *
     * @param int $id
     * @return string
     */
    function osc_item_deactivate_url($id = '') {
        if ($id == '') $id = osc_item_id();
        if ( osc_rewrite_enabled() ) {
            return osc_base_url() . 'item/deactivate/' . $id ;
        } else {
            return osc_base_url(true) . '?page=item&action=deactivate&id=' . $id  ;
        }
    }
```

item.php in root directory changes added at line 245

``` php
case 'deactivate':
                    $secret = Params::getParam('secret');
                    $id     = Params::getParam('id');
                    $item   = $this->itemManager->listWhere("i.pk_i_id = '%s' AND ((i.s_secret = '%s') OR (i.fk_i_user_id = '%d'))", $id, $secret, $this->userId);
                    View::newInstance()->_exportVariableToView('item', $item[0]);
                    if ($item[0]['b_active']==1) {
                        // DEACTIVETE ITEM
                        $mItems = new ItemActions(false) ;
                        $success = $mItems->deactivate( $item[0]['pk_i_id']);

                        if( $success ){
                            osc_add_flash_ok_message( _m('The item has been deactivated') ) ;
                        }else{
                            osc_add_flash_error_message( _m('The item can\'t be deactivated') ) ;
                        }
                    }else{
                        osc_add_flash_error_message( _m('The item has already been deactivated') );
                    }

                    $this->redirectTo( osc_user_list_items_url( ) );
                break;
```

Lastly the change in theme user-items.php

``` php
<?php if(osc_item_is_active()) {?>
                                            <span>|</span>
                                            <a href="<?php echo osc_item_deactivate_url();?>" ><?php _e('Deactivate', 'modern'); ?></a>
                                            <?php } ?>
```

One more addition to make this work with permalinks
in generate_rules.php add the following code at line 53

``` php
$rewrite->addRule('^item/deactivate/([0-9]+)/?$', 'index.php?page=item&action=deactivate&id=$1');
```

Thanks

Jay

**Comment by mappo1980** [comment]
hi, I have version 3.5 you tell me how can I do?

**Comment by aide2001** [comment]
ive found this to be great, but would like to implement this when someone uses my paypal buy it now button and they get referred back to the site and then the item is deactivated.
So far the paypal thing works, they get redirected to a page i set up, now all i need is the code to help deactivate the item, if you could help.
I have thought it would be say www.website.co.uk/page/success?item/deactivate/itemnumber but doesnt work at all

**Comment by zasami** [comment]
the code don't work... i have the link but when i click on.. all time the seam message : The item has already been deactivated

**Comment by Aufwiegler** [comment]
Now in OSClass you must use this code in osclass/controller/item.php

`				case 'deactivate':
                    $secret = Params::getParam('secret');
                    $id     = Params::getParam('id');
                    $item   = $this->itemManager->listWhere("i.pk_i_id = %d AND ((i.s_secret = %s) OR (i.fk_i_user_id = %d))", (int)($id), $secret, (int)($this->userId));

                    // item doesn't exist
                    if( count($item) == 0 ) {
                        $this->do404();
                        return;
                    }

                    View::newInstance()->_exportVariableToView('item', $item[0]);
                    if( $item[0]['b_active'] == 1 ) {
                        // ACTIVETE ITEM
                        $mItems = new ItemActions(false);
                        $success = $mItems->deactivate( $item[0]['pk_i_id'], $item[0]['s_secret'] );

                        if( $success ) {
                            osc_add_flash_ok_message( _m('Объявление было скрыто') );
                        }else{
                            osc_add_flash_error_message( _m("Объявление не может быть скрыто") );
                        }
                    } else {
                        osc_add_flash_warning_message( _m('Объявление уже было скрыто') );
                    }

                    $this->redirectTo( osc_user_dashboard_url( ) );
                break;`
