### ISSUE TITLE
Osclass Searching Issue regarding Chinese Character

### ISSUE THREAD

**Issue by tkosgary** [osclass/Osclass#1221]
Chinese Text always return no result.

However, i may understanding the issue coming from on why some of the search is not function from CHINESE characters point of view. And this is relating to the different structure of text/ paragraph between English and Chinese.

For English Text, to identify a single word, each Word is separated by a space between a consecutive composition of English characters. However, from Chinese Language perspective, each word will NOT separate by space between each word.

e.g English: How are you will not written as "howareyou", however for chinese, how are you will be written as "howareyou" without space. So when users tried to search "are you", then there is no result returned.

Question: how I can modify the search.php so that it will be required a space to separate Chinese Characters during search? and it identify each of the words without the requirement of space as separator?

**Comment by zfc0812** [comment]
@conejoninja The current version of Osclass has empty line on https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/model/Search.php#L800
Which should I edit?
