### ISSUE TITLE
How to make photos/images/pictures as mandatory input during post ads

### ISSUE THREAD

**Issue by mydewaz** [osclass/Osclass#1472]
I'm using Osclass 3.3.2 and realestate theme.

What i have tried:
1. editing oc-includes/osclass/frm/Item.form.class.php like http://forums.osclass.org/themes/photo-is-required-field/
result: working for bender theme but not working for realestate theme
1. using plugin required field
   result: not working
2. put required on item-post.php (under realestate theme)
   <input type="file" name="photos[]" required/>
   result: not working
3. put if photoIndex==0 then alert('<?php echo osc_esc_js(__('Need Image')); ?>') on oc-includes/osclass/frm/Item.form.class.php
   result: not working

please help on how to make photos/image/picture as mandatory during input process.

thank you

**Comment by githubgk** [comment]
I am facing same issue got any resolution?
