### ISSUE TITLE
Modern Theme - CSRF in search URLs

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1481]
I know that Modern theme is not officialy supported, and several fixes I've posted last year were not accepted (Garcia told me he does not generally accept pull requests), so I think there is no point in posting another one, but I just wish to clarify this.

All modern-theme based themes I've tested (for example, Twitter theme from official Osclass site and many other user-spawned ones) insert CSRF tokens into search from the main page, for e.g.:

Modern Theme search url from main page:

/index.php?CSRFName=CSRF837685821_1893338073&CSRFToken=a83b40c5aacc60a1d0ceda9fb40ed75d7e66edcf351be8abe0fc6f8d9baf49e8abe2b76d09bfeda837b675a0c8d49c8926ce18258b137af36e9ed3164f702ab3&page=search&sPattern=test&sCategory=

But, in Bender theme the same URL looks like this:

/index.php?page=search&sPattern=test&sCategory=

My quick investigation of CSRF reveiled that they should not be present in get method (which is used for search), so this has to be a theme-related issue.

To solve this, just put into the search form another class:
class="nocsrf"

and now the search URL will look exactly as in Bender theme (and more meaningfull and user-friendly, btw).

---

I just need a confirmation from the devs that this is the right way.
Thanks

**Comment by t0ma5** [comment]
> 
> 
> To solve this, just put into the search form another class:
> class="nocsrf"
> 
> and now the search URL will look exactly as in Bender theme (and more meaningfull and user-friendly, btw).

I have had the same problem with Repurpose Theme :(
About 2 years ago I managed to fix it but I can't find the old forum post where the solution was found
Could you PLEASE give me more details about how to apply your suggested fix?

**Comment by dev-101** [comment]
This project is no longer active. You should find alternative version here: https://github.com/mindstellar/Osclass

Solution is very simple and similar to modern theme:

search.php | line 23
```<form action="<?php echo osc_base_url(true); ?>" method="get" class="nocsrf">```

**Comment by t0ma5** [comment]
thanks a lot for reply! I was wondering if someone was going to read my post or not :)
I did what you suggested before modifying that exact like but it didn't help my problem so I thought I was placing the code in the wrong like.
Before changing the code the search URL was this:

`website.com/search/CSRFName,CSRF1388392296_940733998/CSRFToken,1289656647648678cecfa0e82e0d1eaa2209475ad5c58ac1104bc03714027bff7294457b7f654a50aeb5fb7033560fce2f65c6c8921dd2526c48b5ba8b2f9ae2/pattern,project/category,97,101,99,98,174,100,111/iPage,2`

after the change the URL is:

`website.com/search/pattern,project/category,97,101,99,98,174,100,111/iPage,2`

But the error persists:

`Forbidden
You don't have permission to access this resource.
Apache/2.4.25 (Debian) Server at website.com Port 80`

**Comment by dev-101** [comment]
Check file ownership on your server via ftp, that is unrelated issue. You probably changed it as root.

**Comment by t0ma5** [comment]
> 
> 
> Check file ownership on your server via ftp, that is unrelated issue. You probably changed it as root.

I apologize for the newbie question but what file(s) or folder(s) should I check for?
I'm browsing the php files via FTP and all seem to have the right permissions.
