### ISSUE TITLE
some login/maintenance issues

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1611]
Recently I have started using Chrome as my main browser (before only as a regular dev tool in incognito mode), so this might colide with 340.

>update: [bug 2] confirmed with other browsers too, also on older versions, not just 340.

[bug 1] After clean install maintenance mode seems to be randomly activated when admin logs out and goes back to frontend to login as a user. This happend only 2 times so far, cannot reproduce it at all. In first case, I was connected to SFTP, so the maintenance file was indeed created in the root. Second time, it wasn't. Maybe it is a Crome bug, mixing cookies/sessions, really have no idea why, never occured before.

[bug 2] Second bug, again related, when admin logs out, then clicks Back-to-frontend link, logs in as a regular user, it gets redirected to admin login page, instead to a main website. Obviously, user is not logged in as admin, but... it is strange. Then, when I press back inside browser, I appear to be logged in as a user and everything works fine. This is only an admin side issue, does not affect ordinary users.

**Comment by conejoninja** [comment]
Can not reproduce the issue
