### ISSUE TITLE
checkbox values (multiple values)/search page url

### ISSUE THREAD

**Issue by maddrid** [osclass/Osclass#1616]
values from checkboxes  sColor[]=BLACK&sColor[]=BLUE
category instead is sCategory[]=for-sale%2Fhealth-beauty
http://abc/index.php?page=search&sOrder=dt_pub_date&iOrderType=desc&sPattern=&sCity=&sPriceMin=&sPriceMax=&make=&model=&type=&min_year=&max_year=&kmin=&kmax=&sFuel=&sColor[]=BLACK&sColor[]=BLUE&sCategory[]=for-sale%2Fhealth-beauty
multiple select may reproduce the issue

**Comment by web-media** [comment]
SHOULD BE 
sColor[]=BLUE,RED,GREEN,BLACK1
NOT 
sColor[]=BLACK&sColor[]=BLUE&sColor[]=RED&sColor[]=GREEN&sColor[]=BLACK1&sColor[]=BLUE1&sColor[]=RED1&sColor[]=GREEN1&sColor[]=BLACK2&sColor[]=BLUE2&sColor[]=RED2
