### ISSUE TITLE
osc_get_canonical() - (not) working or?

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1665]
Hi,
Is this function actually working? Whatever page I check (not the search URLs) the if condition !='' is never met, and I think it should do. Can you give me a working example in case I miss something?

Also related, do we have a direct country URLs possibility? For example, we do have links for regions and cities, but whatever I try to form a direct URL to a country, it returns 404:

http://domain.com/countryname-countrycode -> 404

Thank you
Regards

**Comment by dev-101** [comment]
With noindex/nofollow we can almost perfectly replace this (not needed)

**Comment by portatil33** [comment]
Is not solved the canonical  ??
The web is full of duplicate content in searchs.

http://www.buscadisimo.com/

**Comment by portatil33** [comment]
This websites are index & follow

http://www.buscadisimo.com/alicante-r781286
http://www.buscadisimo.com/anuncios/region,781286/sOrder,i/price/iOrderType,asc

Are the same duplicate content.
The canonical meta is necesary......
