### ISSUE TITLE
[SUGGESTION] Osclass Audit Trail (log)

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#1672]
Right now i see more and more plugins to create a log for various activities. Also i see people asking about the availability of somekind of log (for example for Alert emails). 

So i would suggest to have ONE Central Audit Trail log for osclass, that ALL plugins and core can write. Instead of having each plugin to create his own. 

Also could be optional to log and WHAT to log.

**Comment by conejoninja** [comment]
Isn't table t_log enough?
