### ISSUE TITLE
osclass 3.4.1 can not install on MySQL 5.7

### ISSUE THREAD

**Issue by Smilefounder** [osclass/Osclass#1676]
Hi team,

A lot of database issue occurred when we install  osclass 3.4.1 on MySQL 5.7.

Regards,
Huy Nguyen

**Comment by dev-101** [comment]
Osclass should definitely get compatibility with MySQL 5.7+ ASAP (currently 5.7.10 stable is released)

http://forums.osclass.org/general-help/error-1067-error-1292-installation/
