### ISSUE TITLE
Permalinks and 404

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#1692]
3.4.1. If Permalinks are Enabled, all ".php" pages do NOT return a 404 page (or http header) but they Redirect to the home page.

If this is not a bug (i guess it is, since disabling permalinks works ok), that behavior is unwanted.

**Comment by conejoninja** [comment]
Could you provide an example URL? I'm not able to reproduce the problem under nginx

**Comment by dev-101** [comment]
Hi Conejo, here is an example:

`www.example.com/my-non-existing-page.php`

Thing is a1a2.php page does not exist (you can enter anything you want + .php at the end)

**Comment by eurobank** [comment]
@conejoninja 

I just emailed you.

**Comment by conejoninja** [comment]
Are you using Apache? which configuration/modules do you have installed/enabled?

**Comment by eurobank** [comment]
I'm using LiteSpeed, for the rest tell me what exactly you mean ? I have nothing strange. 

Also i'm hosting some Wordpress sites, that properly return 404, so it is not related to my setup but to Osclass.

I would like to repeat that is OSCLASS PERMALINKS are NOT ENABLED, 404 is returned.

**Comment by conejoninja** [comment]
I just wanted to know your setup because I could not reproduce the issue using nginx

**Comment by dev-101** [comment]
I use plain Apache and also have this issue (it may not exist under Nginx or other servers).

Modules:
----------------------------------------------------------------------------------------------------------------------------

access_compat_module modules/mod_access_compat.so
actions_module modules/mod_actions.so
alias_module modules/mod_alias.so
allowmethods_module modules/mod_allowmethods.so
asis_module modules/mod_asis.so
auth_basic_module modules/mod_auth_basic.so
authn_core_module modules/mod_authn_core.so
authn_file_module modules/mod_authn_file.so
authz_core_module modules/mod_authz_core.so
authz_groupfile_module modules/mod_authz_groupfile.so
authz_host_module modules/mod_authz_host.so
authz_user_module modules/mod_authz_user.so
autoindex_module modules/mod_autoindex.so
cgi_module modules/mod_cgi.so
dav_lock_module modules/mod_dav_lock.so
dir_module modules/mod_dir.so
env_module modules/mod_env.so
headers_module modules/mod_headers.so
include_module modules/mod_include.so
info_module modules/mod_info.so
isapi_module modules/mod_isapi.so
log_config_module modules/mod_log_config.so
cache_disk_module modules/mod_cache_disk.so
mime_module modules/mod_mime.so
negotiation_module modules/mod_negotiation.so
proxy_module modules/mod_proxy.so
proxy_ajp_module modules/mod_proxy_ajp.so
rewrite_module modules/mod_rewrite.so
setenvif_module modules/mod_setenvif.so
socache_shmcb_module modules/mod_socache_shmcb.so
ssl_module modules/mod_ssl.so
status_module modules/mod_status.so

**Comment by conejoninja** [comment]
does it happens with any other filetype? .htm .html .js .css .jpeg .jpg ....??

**Comment by eurobank** [comment]
www.website.com/a1a1.php goes to Home

www.website.com/a1a2 (without extension) returns Page not found

www.website.com/a1a2.txt returns Page not found

www.website.com/a1a2.jpg returns Page not found

So only .php goes to Home.

**Comment by eurobank** [comment]
I have gone to forums.osclass.org and checked most of the publicly posted osclass websites. ALL of them suffer from it (but the owners don't know it ...).

**Comment by dev-101** [comment]
Little late, but just to say in my case only .php behaves this way; .html and other return proper 404 page.

**Comment by dev-101** [comment]
This issue can be closed now, seems to be fixed.

Thanks Conejo & Carlos
