### ISSUE TITLE
MySQL field length for for cyrillic languages issue

### ISSUE THREAD

**Issue by Yevgen-UA** [osclass/Osclass#1720]
Table oc_t_category_description - s_slug 
should have more then varchar 100 (lets say 350-500) for an adequate work of permalinks function with cyrillic languages. We have forgotten that the Cyrillic characters take up to six times more characters to store in db.
P.S. Duaring auto update from 3.4.1 to 3.4.2 this field limited up to 100 characters again. And Cyrillic users should resave all categories from admin to make them work again.
Just certainly worth paying attention to other db fields in which there may be problems due to limited number of characters for Cyrillic

**Comment by mikeyrurg** [comment]
I have made varchar to 350 but permalinks still doesn't work correctly.
My site uses cyrillic language with v3.6 Osclass.

**Comment by mikeyrurg** [comment]
I tried and with varchar 500 but it's same.

**Comment by mikeyrurg** [comment]
Do you have any other idea to solve this problem?

**Comment by mikeyrurg** [comment]
I have activated the Permalinks in my site www.totalbg.info. There are several errors:
- don't recognize category's names in URL
- can't sort listings by price
- Breadclumbs don't work correctly
I think that site don't recognize cyrillic symbols. Can you give me some code to add it in my site?
I've checked out several forums but I have found nothing that works.

**Comment by mikeyrurg** [comment]
I have activated the Permalinks in my site. There are several errors:
- don't recognize category's names in URL
- can't sort listings by price
- Breadclumbs don't work correctly
I think that site don't recognize cyrillic symbols. Can you give me some code to add it in my site?
I've checked out several forums but I have found nothing that works.

**Comment by garciademarina** [comment]
@mikeyrurg can you add here some categories names? (which don't work) in order to make some testing and be able to reproduce your issues.

**Comment by conejoninja** [comment]
VARCHAR field is limited to 255, setting it to 300 or 500 is not possible
