### ISSUE TITLE
RSS Feed URL - why 301 redirect?

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1742]
Hi,

I see that RSS Feed URL is now changed, with permalinks it was simply:

`example.com/feed`

and now example.com/feed returns 301 and URL is like this:

`example.com/search/sFeed,rss`

Is this change really necessary? I think it was better the way before.

This change broke my relative xsl path, so this is the main reason I'm complaining and how I noticed it, but shorter URL also looked nicer / was easier to remember / more logical.

Thanks,
Regards

**Comment by conejoninja** [comment]
We could add an exception to it, the problem is that you could get a feed out of any search, so if any more param is passed to

**Comment by dev-101** [comment]
Thanks for clarifying!

Regards
