### ISSUE TITLE
"Upload failure reason unknown" while trying to add images to new post

### ISSUE THREAD

**Issue by WilliamsTiger** [osclass/Osclass#1746]
Hi i've been using Osclass on my website and posted lots of ads with pictures but since this morning i'm no longer able to upload images in posts.I Get This Error: " Upload failure reason unknown"
Here is a screen:
![](http://image.noelshack.com/fichiers/2014/41/1412991307-upload-failure.png)

**Comment by shyaminayesh** [comment]
check if the php-gd extension is loaded ?

**Comment by shanutthankachan** [comment]
simply change permission of  /oc-content/uploads/temp/ folder
```
sudo chmod 777 /oc-content/uploads/temp/` then try it
```

**Comment by hectorjayat** [comment]
I changed to 777 but continue with the same problem.

Any advise?
Same issue on Cjrome and firefox, I´m using php 7.1 on my server.

Also it was working fine some days ago, but sudenly started to fail this way.
Thanks

**Comment by shyaminayesh** [comment]
@hectorjayat : anything on PHP error logs ? :thinking:

**Comment by hectorjayat** [comment]
Not sure if this a phphp version related issue because it was working fine, but so far I do not what to move, I get this error and no image is being uploaded.

**Comment by hectorjayat** [comment]
The issue is the same as Williams has, the script was working fine, but sucdenly start failing, Now when I´m logged out and try to login as a user (not as an admin) it says Sorry ,the requested page cannot be found, this happen when try to login or to register a new user. Any advise?
Thanks in advance.

**Comment by hectorjayat** [comment]
I´m thinking in to start over and delete everything, Would it be a good move?
Thanks

**Comment by AcuitySoftwareDev** [comment]
sudo chmod 777 /opt/lampp/htdocs/redclaw/oc-content/uploads/temp/

on kali linux and boom problem gone
