### ISSUE TITLE
{ITEM_URL}

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1769]
i have a issue with the activation email. 
In a different email i have used <a href="{ITEM_URL}" target="_blank">{ITEM_TITLE}</a>

to show the title of the listing with the actual link attached. In that email (email_item_inquiry), is working fine .

However, when i try to use exactly the same code in email_item_validation , i get a wrong email showing /www.mywebsite/df-sdf_36" >http://www.mywebsite/df-sdf_36">This is the title of ad  

instead of 

This is the title of ad (with the actual link attached)

The only thing that is different and i assume that the issue comes from this is the fact that in the legend of the activation email i do not see variable {ITEM_TITLE}

If this is the case, can you add {ITEM_TITLE}   to all emails that uses {ITEM_URL}?
i have a issue with the activation email. 
In a different email i have used <a href="{ITEM_URL}" target="_blank">{ITEM_TITLE}</a>

to show the title of the listing with the actual link attached. In that email (email_item_inquiry), is working fine .

However, when i try to use exactly the same code in email_item_validation , i get a wrong email showing /www.mywebsite/df-sdf_36" >http://www.mywebsite/df-sdf_36">This is the title of ad  instead of This is the title of ad (with the actual link attached)

The only thing that is different and i assume that the issue comes from this is the fact that in the legend of the activation email i do not see variable {ITEM_TITLE}

If this is the case, can you add {ITEM_TITLE}   to all emails that uses {ITEM_URL}?

**Comment by conejoninja** [comment]
I'm not sure I understood you

What problem do you have?
{ITEM_URL} is just the url
{ITEM_LINK} is the url with HTML <a> tag to make it a link
{ITEM_TITLE} is just the title in plain text.

**Comment by Adyyda** [comment]
Ok. In certain emails we have all the variables present and were we have them we can make a custom link like " To read the message press HERE" - that HERE has actualy a link inside. It is much more nice than long links and we can customise them as we wish. HTML emails, not just plain emails.

But, in other emails, not all variables are present and if you try to use one which is not present by default in that type of email, it will not work. Will look ok but when the email arrives (hardly), instead of HERE we see " /www.mywebsite/df-sdf_36" >http://www.mywebsite/df-sdf_36">This is the title of ad instead of This is the title of ad"

**Comment by conejoninja** [comment]
And in which specific email is {ITEM_TITLE} not present?
{ITEM_TITLE} is present by default in every email in which {ITEM_URL} is. If {ITEM_TITLE} is not present by default, it's probably because it's not used in the email, but please, tell us in which email do you miss them.

Additionally, you have filters before the keywords are replaced, so you could change it if you want to.

**Comment by Adyyda** [comment]
For instance, "email_item_validation" does not contain it.

http://demo.osclass.org/general/oc-admin/index.php?page=emails&action=edit&id=11

**Comment by conejoninja** [comment]
{ITEM_TITLE} should work on "email_item_validation" even if it doesn't appear on the legend. Could you check it? Also which Osclass version are you using?

**Comment by Adyyda** [comment]
You did not understand me. So, here it is again
I will use <div style="">Your listing<a style="color: #ccc; text-decoration: none; font-weight: bold;" href="{ITEM_URL}" target="_blank">{ITEM_TITLE}</a></div>
That should show the name of the listing and on click it should go to the actual listing.

Right now, in 3.5.2 (and previous) some email templates do not allow this -  for instance
"email_item_inquiry"
"email_item_validation"

if i use the code shown up, i will get a late email because the link is broken like mentioned in first message. So i have to remove the href="{ITEM_URL}" and we end up with plain text for the title of the ad. Not ok because user will find it hard, via search for instance.

So, please use the provided code (that works just fine) and see if you will get working emails.

You did a great job to set up the emails to work like on olx and all we have are some issues because , after me, you shoulded allowed all the variables that exists for the emails since that would give us the freedom to make custom reach emails instead of plain text.

**Comment by conejoninja** [comment]
Thanks, now I understood the problem, it should be fixed with this : https://github.com/conejoninja/Osclass/commit/05820a7d4e70fefd8cb17496787aa57bc0caf6f9

**Comment by Adyyda** [comment]
Thank you. Will test it when i will make the update and let you know if all is ok.
Please look as well at https://github.com/osclass/Osclass/issues/1787 which is important.
