### ISSUE TITLE
Permalink for delete account

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1770]
![untitled](https://cloud.githubusercontent.com/assets/5921012/5200474/f5d74776-756e-11e4-92e3-ee84f289c45f.jpg)

We can't set up permalink for Delete account

**Comment by conejoninja** [comment]
I don't think it's a great idea to have a permalink to delete your account without a confirmation. In any case, you could use the example.com/index.php?page=user&action=delete&id={USER_ID}&secret={USER_SECRET}
