### ISSUE TITLE
part of the lenguage does not get translated

### ISSUE THREAD

**Issue by monofeocl** [osclass/Osclass#1776]
hi i updated from 3.4.3 to 3.5.2 and my site is spanish and there is a problem becoue for some reason the part of the Category with theres sub Category does not get translated in spanish any more, i try to remove the lenguage and instaled again , en olso with the theme and try a nother one but the problem repaim, so if you could please fix this i would be glad, the website is www.tuparadero.com the rest is in spanish exept the Category's

**Comment by conejoninja** [comment]
Can not reproduce the issue. It worked fine in my setup.
If the category's name have not been modified it should be translated.
