### ISSUE TITLE
[spam/security] www.example.com/?keyword - should this return 404 ?

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1777]
Original forum topic is here:
http://forums.osclass.org/modern/page-does-not-exists-but-still-shows-in-google-search/

Quote:
```
My site is being hacked.. finally cleaned most of the scams etc...
I would appreciate if someone assist me how and where to locate this:
```

Example URLs:
>http://www......com/?keyword=louis-vuitton-n51262-sale&id=4062 
>http://www......com/?keyword=cheap-louis-vuitton-m52802&id=3366

![index](https://cloud.githubusercontent.com/assets/5383059/5291995/5451e832-7b5b-11e4-804d-f725abc1c42e.png)

Solution:
Instead of index page and HTTP 200 OK, should this return 404 page and HTTP 404 response?

![http-200-ok](https://cloud.githubusercontent.com/assets/5383059/5292024/daf9f618-7b5b-11e4-94c3-184ece4c2661.png)

**Comment by conejoninja** [comment]
@eurobank if you're talking about #1692 I'm not sure how it's related.

In this case, the spammer is adding a parameter to the home page, no .php is involved. I'm not sure how the spammer is displaying text/title, since "keyword" is not used in Osclass... It's the same has example.com?keyword=SCAM_TITLE and then have it indexed by google (not sure how).

Will reopen if someone has some more information about how to avoid this, but I think it's out of our control.

**Comment by dev-101** [comment]
Probably they just added those links inside a sitemap file and Google picked them up. Why Google saw them as legit? Well, HTTP header return 200 OK status and page loads with content. Google probably at that stage does not compare 1-on-1 that it is the exact same page as index page - and you end up with this issue. Problem is not related to .php, but to the fact both issues are related to HTTP headers code.

Regards

**Comment by conejoninja** [comment]
I'm not sure you could submit a sitemap from a website you don't own.
If that's possible, I would submit links to famous websites, for example : 
http://www.github.com?keyword=SCAM_TITLE (also a 200 OK header) "SCAM_TITLE" stays in URL
https://twitter.com/?keywords=SCAM_TITLE (307 + 200 OK header) "SCAM_TITLE" stays in URL
... And probably with most websites you could think of


Also, what is the point of having said link? there's no spam content on the website...


My point is, that you can not control is someone adds some parameters to your URL (it could be a valid parameter), but I still don't understand how it was indexed at first place. It doesn't look like a Osclass URL, not sure how it was originated and why Google indexed them if they have the same content ...

**Comment by dev-101** [comment]
No, no, the user explained in the forums that its server was compromised:
http://forums.osclass.org/modern/page-does-not-exists-but-still-shows-in-google-search/

It did not explain how/why though.
