### ISSUE TITLE
New Item Post > Location > City (wrong cities via ajax)

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1782]
Hi, this must have been noticed long before so sorry in advance. Location auto-complete pulls all the cities from the database which is not only inefficient, but allows users to mix regions with wrong cities, and it is valid both inside Admin Dashboard > Manage Listings Add/Edit and in frontend (Bender theme, latest Osclass 3.5.3). US geo locations database is installed and used.

1) When posting new add, say we choose US, then enter state `Illinois` for a Region, and then try to enter a city which begins with Ne.. (we aim for `Nebo` here), list populates all the US cities which begin with `NE' instead only those part of the entered region. For e.g. this is what we get:

![1-not-working-at-publishing](https://cloud.githubusercontent.com/assets/5383059/5471377/f72e3be8-85f4-11e4-95e4-7130fb733696.png)

Most easily to spot are 3 different Nebos here (edited names to help differentiate the states). User can choose any city out of the list, although only one is correct and belongs to the state of Illinois. Notice the Nebraska City, which also does not belong to Illinois etc and many others (the list is very long).

2) If we decide to edit the same item (which was saved only with the Region during the original posting), auto-complete will now get correct results with cities only belonging to the said region.

![2-working-at-edit](https://cloud.githubusercontent.com/assets/5383059/5471410/730bc8fc-85f5-11e4-8705-ec71ed3ca004.png)

This is a serious issue, since in the first case if we/user enter wrong region/city combination, we will not retrieve a proper city name or id and many simply use the script this way out-of-the-box.

Thanks,
Regards

**Comment by conejoninja** [comment]
This only happened if the region is written instead of selected from the autocomplete dropdown menu, but it should be fixed now.
