### ISSUE TITLE
email_new_comment_user doesn't work

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1783]
Email "email_new_comment_user" does not work. Owner of the listing does not receive the email that informs him that he received a new comment. Olso, no email arrives when you click on "Test it" in admin area (after you have added the email address ofcorse).

**Comment by conejoninja** [comment]
Can not reproduce the issue. Did you checked the option under admin panel > settings > comments
![image](https://cloud.githubusercontent.com/assets/475423/5874250/a0bcff2e-a2ff-11e4-8737-2b17fb6a6cac.png)

Could you verify that the option is checked?

**Comment by Adyyda** [comment]
Sorry for this. You were wright. Option was not active.
