### ISSUE TITLE
Wrong order of locations if using regionals

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1786]
If we use regionals, the order of location is in general broken. Please fix this issue so that they show exactly in the order from the sql file wich is uploaded.
![alphabet](https://cloud.githubusercontent.com/assets/5921012/5514841/80c6b728-8856-11e4-8b65-02b76deb583f.jpg)

**Comment by conejoninja** [comment]
Hi, This has to be with the "collation" of the tables in the database. To put it simple, "collation" is the language of the data in the table, used for example to order it. We create the table with "utf8_general_ci" which works fine for most international data. If you're experiencing problems I suggest you to change it.


Here's some more information:
http://dev.mysql.com/doc/refman/5.6/en/adding-collation.html
http://stackoverflow.com/questions/16937675/mysql-incorrect-order-by-with-utf8-characters

In phpMyAdmin you select your table > Operations > under table options 
![image](https://cloud.githubusercontent.com/assets/475423/5834080/da38dcb6-a159-11e4-8031-3c401b24a8f4.png)


I suggest you to use utf8_romanian_ci

**Comment by Adyyda** [comment]
Beside changing to utf8_romanian_ci and apply the changes do i have to do anything else in osclass because nothing is changed?

**Comment by conejoninja** [comment]
Let me try some other solution, as it should have worked

**Comment by Adyyda** [comment]
Did you find a solution to this bug? Thaks
