### ISSUE TITLE
Too many items were uploaded. Item limit is 0.

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1788]
Default 3.5.3 installation, Bender, default settings. Everything is working fine (no bugs, no js errors), except when using Bender theme and number of attached images limit is left to 0 (= no limit, default) in Admin Dashboard, following bug occurs:

1) post new item with for example only 1 image
3) try to edit item > now remove uploaded image > and then try to upload new image

`Too many items were uploaded. Item limit is 0.`

js message is shown and there is no way to attach new image(s) afterwards.

Bug only affects qq uploader. Confirmed on 2 different systems.

Temp Fix: set finite number of allowed attached images per item (> 0).

**Comment by scottmcconnell** [comment]
Was this resolved? If so, how?

**Comment by conejoninja** [comment]
Yes, here https://github.com/conejoninja/Osclass/commit/1203190bc09ba69e7de27d563f6f73c635a10f5a

**Comment by scottmcconnell** [comment]
Champion - Thanks for the quick response.
