### ISSUE TITLE
Items datatable ,all columns sortable 

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#1791]
Date is sortable :+1: 
All columns sortable (Status,Title,User,Category,Location ) 
On large number of items admin   ability to sort items by columns its a must !

**Comment by dev-101** [comment]
Hi web-media, why did you close this issue/feature request?

**Comment by conejoninja** [comment]
It could not be sorted by status nor by location.
Status depends on several fields (premium, active, enabled), this would be a mess in the query
Location is made up from city + region + country (this could be sorted by, but at a cost from the DB query)

I just want to know your opinion. Is it worth it?

**Comment by dev-101** [comment]
Well, probably not. Location can be filtered, if we search something in particular, and status can be filtered too. I just wish if there was a filter to display only expired items (for bulk removal), that would be very helpful.

Thanks
