### ISSUE TITLE
Search location with checkbox

### ISSUE THREAD

**Issue by Iscamon** [osclass/Osclass#1796]
Hi, i listed the regions of spain (spain theme) in the siderbar of search page with checkboxes, and i want to do the search with one or more regions at the same time, like the categories checkboxes do. At the moment only search by one region. This is my code: 

<input type="checkbox" name="sRegion" id="sRegion" value="<?php echo osc_esc_html(osc_list_region_id()); ?>" style="width:30px" <?php echo (osc_search_region() == osc_field(osc_list_region(), 'region_name', '') ? 'checked' : ''); ?> ><label for="<?php echo osc_esc_html(osc_list_region_id());  ?>"><strong><?php echo osc_list_region_name();?></strong></label>

Any idea how can i do this??? Thanks

**Comment by conejoninja** [comment]
Please, post your doubts in the forums http://forums.osclass.org/
This place is for bugs and errors
