### ISSUE TITLE
slash "/" in search word pattern breaks URLs on Apache (server response 404)

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1797]
For example: if we search for a word `/test` or `test/` it will result in Apache server 404 error response. This problem is well-known under Apache with various solutions available.

Backslash is not an issue, since all special chars values are sanitized from the item title URLs, and do not affect the search. But, what if a slash is part of the word, for example: AC/DC ?

http://stackoverflow.com/questions/3235219/urlencoded-forward-slash-is-breaking-url
http://www.leakon.com/archives/865 (different solution ideas)
http://stackoverflow.com/questions/4390436/need-to-allow-encoded-slashes-on-apache (about apache slash directive)

forum topic:
http://forums.osclass.org/3-5-x/error-404-when-inputting-words-with-slashes/

-----

I have quickly done tests with 2 variations on apache AllowEncodedSlashes directive, on VPS it had no effect (no apache config errors in logs, and 404 still there).

On local server with setting set either to On or NoDecode: no more 404s were present with words containing slash, but pattern parameter was empty and completely ignored; without a pattern all items were returned from search.

**Comment by dev-101** [comment]
According to second resource link in the first post, this is a security feature of Apache and really I am not sure how slash character in search is important? I mean, it probably affects less than 0,001 % of all the search keywords.

```
By default, Apache http web server immediately returns a “404 (Not Found)” error when it encounters url encoded versions of path separators or slashes in URL (Uniform Resource Locator). These are %2F for forward slash (/) and %5C for back slash (\).

The server simply rejects the URL without invoking mod_proxy or mod_rewrite.

This behavior was made to prevent a CGI security hole where sensitive files are mistakenly accessed by scripts using PATH_INFO as a result of poor or no security checks at all.

While this was a legitimate thing to do, this causes problems with some scripts that depend on receiving encoded values which may contain slashes, in URLs.
```

**Comment by conejoninja** [comment]
After reading about this topic, I'm not sure we should do something about this.
1.- Looks like it's not only on Apache, other webservers could disable this without option to fix it (as it's part of the CGI standard to disable it)
2.- This would require changes in the way we parse the URL, as it would not be possible to differentiate it from normal slashes

**Comment by dev-101** [comment]
Hi Conejo,

I agree - but can you tell me where is the initial line for pattern sanitizing inside the core files - so that we can manually apply simple trim function at least - example:

$str_replace = str_replace('/', ' ', $pattern);

This will trim any slash inside the search pattern, and it should not affect the search results (it will return all patterns with / in front or in the end), it may be tricky for the word "ac/dc" for example, if the full text does not index words 2 characters in length, but this is not my concern. In case it does, it will simply search for split words "ac" and "dc" and it should work.

I have tried in many places and many things to trim it inside osclass with str_replace but always failed. Not sure if apache even passes the url to osclass at all because of this.

>2.- This would require changes in the way we parse the URL, as it would not be possible to differentiate it from normal slashes

Yes, this would not be the issue if we used & to form all urls with parameters, but since / is used, this is the problem.

Thanks,
Regards

**Comment by conejoninja** [comment]
the problem is not sanitizing sPattern, because sPattern is actually wrong at that step.

Search URL look like

search/param,value/param2,value2/param3,value3/ 

In this case,  search/sPattern,/test/param2,value2/ will take an empty value for sPattern, 

if the url is something like search/sPattern,AC/DC/param2,value2/ then sPattern will be "AC" only


There's no much problem with it, but we need to take care of it, and hope it doesn't break anything else. I'm not sure it's worth the trouble for a minimum of cases

**Comment by dev-101** [comment]
I was afraid that you will write something like this :)

After several days trying every section inside core files to trim the sPattern (because with Apache `AllowEncodedSlashes` directive 404 is not happening anymore, but because of extra / present, URL structure breaks and search returns all items, my idea was to in that case only (with directive present) remove the / slash from the pattern itself.

Another idea was to use javascript on a client side to disable typing / slash inside search box, but although virtually every device has js enabled by default, for rare cases it does not this would not work.
Do I worry too much? - yes! :)

Thanks,
Regards

**Comment by dev-101** [comment]
I know this issue is closed, but I have to get back to it again.
Daniel, if you be so kind to re-open it for the time being, so we don't get lost track of it.

The reason for reopening this issue is that I have setup WordPress on the same system/server environments (both older and newer Apache/PHP versions), and in WordPress this issue does not exist (e.g. search functions quite normal, with permalinks enabled).

example:

>wordpress . site/?s=test+%2F

returns proper search results.

however, in Osclass server/apache generic 404 error page is returned:

>Not Found
>The requested URL /search/pattern,test+/ was not found on this server.

This clearly indicates that the problem could be in fact related to Osclass, because in WP works just fine.

---

Again, problem could be as well related to "&" character issue #1921.
