### ISSUE TITLE
BCRYPT COST & automatic password hash update

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1804]
Hi, I was recently thinking about this.

If we manually define and change BCRYPT cost, the old passwords will remain with the old cost. The only way now to update all hash values to the new cost is to either initiate password reset to all users (is there an automatic way -- how?) OR that each user update/change password manually.

Why instead we do this: during user's next login we compare current cost with stored one (already stored in hash) and if it is changed -- we generate 2 hash values with old (for verification) and new (for update), then simply compare the old one and if the user has passed successful login procedure we automatically update the old hash value with the newly generated one, completely silently and not bothering the end user.

Thanks,
Regards

**Comment by conejoninja** [comment]
I think it's better to just reset users password. Since the bcrypt cost is different the hash will not be the same and the user will not be able to login, only way to do it, is to reset the password.

If we do what you propose we could end up calculating two hashes, but I don't think changing the bcrypt_cost is too common. It's a good practice to change passwords from time to time.

**Comment by dev-101** [comment]
Hi Conejo,

How can we perform massive password reset inside Osclass? I do not see any way to do it from admin dash?

The COST is already stored inside all hash values: `$y (e.g. version) $15 (cost) $... (hash string)`
So, this is very much possible! 2nd calculation will only take place IF login was successful. Updates are rare, yes, but they have to be performed with server upgrades to keep up.

Here is a flow chart:
----------------------------------------------------------------------------------------------------------------------------
![bcrypy cost automatic update flow chart](https://cloud.githubusercontent.com/assets/5383059/5800319/54eb79d8-9fdd-11e4-9c6e-b441c3e7a8cf.png)

----------------------------------------------------------------------------------------------------------------------------

Please, take a second thought about it,

Thanks,
Regards

**Comment by conejoninja** [comment]
Hi,

Which version of PHP are you using? I just tested the functions (all three of them) and since the cost is inside the hash, the verifying functions don't rely on the current cost of the bcrypt to work, they should work even if you change the bcrypt cost. Could you confirm this?

**Comment by dev-101** [comment]
Hi Conejo,
sorry if I was not clear about this. Autoupdate feature is about password security, not about login issues. of course I can login and it works, but the password hashes are not updated. The whole idea here is when you move to a higher server  you gradually and hassle-free to users increase strenght.

**Comment by dev-101** [comment]
Hi Conejo,

just got home and tested it - there seems to be an issue with admin part, instead of admin it updates user's equivalent pk_i_id s_password field. Afterwards, said user cannot login anymore (obviously), and the admin cost is never updated/changed, it can still login without issue. Tested on a clean 353 under Apache and PHP 5.4.16

This need a little more testing, but anyway I want to thank you - this is exactly what I wanted! Will postpone it until tomorrow. :beers:

**Comment by dev-101** [comment]
I am very tired, but took a quick look at the code before 'shutdown' and here is the line that should be replaced:

https://github.com/conejoninja/Osclass/blob/390e553c6a4c7982969fb0f61c304aa4f02a8457/oc-admin/login.php#L68

User:: should be Admin::

PR
https://github.com/osclass/Osclass/pull/1808

Thanks again!
Regards
