### ISSUE TITLE
Redirect loop with SEF/permalinks

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1812]
Hi,
all of a sudden i get This webpage has a redirect loop when i try to access one category:
example.com/kjøretøy. IIRC, it worked fine before. Also, this happens only for categories with language special chars. 
When i disable SEF/Permalinks, it all work fine!

Apache log:
[22/Jan/2015:09:10:50 +0100] "GET /kj\xc3\xb8ret\xc3\xb8y HTTP/1.1" 301 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36"

Here a simple curl to http://example.com/kjøretøy gives 301.

curl -I http://example.com/kj%C3%B8ret%C3%B8y
HTTP/1.1 301 Moved Permanently
Date: Thu, 22 Jan 2015 09:36:18 GMT
Server: Apache/2.2.29 (CentOS)
Set-Cookie: osclass=daeb936b487d04a6dbca9756b311064a; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: http://example.com/kj%c3%b8ret%c3%b8y
Content-Type: text/html
Content-Language: no

Any idea why this happens?

**Comment by dev-101** [comment]
I have tested with Chrome 40.0 on 2 different systems under Apache and it is working fine for me.
Check your files integrity and any errors in your logs.

![1](https://cloud.githubusercontent.com/assets/5383059/5855677/3197a82a-a23b-11e4-803b-5c014d36c399.png)

-----------------------------------------------------------

![2](https://cloud.githubusercontent.com/assets/5383059/5855681/3cac92a2-a23b-11e4-9352-de86ec37b720.png)

-----------------------------------------------------------

![3](https://cloud.githubusercontent.com/assets/5383059/5855682/40ff9188-a23b-11e4-94e6-e86588d638bb.png)

**Comment by conejoninja** [comment]
Probably we're missing some conversion made by your webserver... could you tell us something more about your configuration ?

**Comment by fossxplorer** [comment]
Thanks. Yes, it was probably a reverse proxy in front of Apache causing the redirect loop as it works fine without the reverse proxy.

**Comment by dev-101** [comment]
This is because Varnish is effectively bypassed with Osclass, since it detects cookies and does not work. Somewhere in the middle of this issue you may find my post about it: https://github.com/osclass/Osclass/issues/1060

**Comment by fossxplorer** [comment]
Thanks for the info @dev-101.
Does https://github.com/PluginCache-osclass/plugincache still work with current version of Osclass?

**Comment by dev-101** [comment]
It should work,did not tested it lately (since 3.4x). It is based on original plugin and it is created by cartagena68, with contribs from users. Do not use first versions (or use official Simple Cache). Forum topic: http://forums.osclass.org/plugins/caching-plugin/
