### ISSUE TITLE
Item Edit - Region and City

### ISSUE THREAD

**Issue by darmeth** [osclass/Osclass#1813]
When editing an advert, the user is shown all cities and all Regions when using the drop-down locations as detailed here:http://doc.osclass.org/Changing_between_drop-down_and_autocomplete_for_locations

Example: If the user posted an advert with Region=London and City=Westminster, when they edit the listing, they are given ALL Regions and ALL Cities in the table, not only the Cities in London. Of course, when the ad is loaded to be edited, it loads correctly but changing the City is therefore the problem. To explain further, if the user wished to change Westminster to Soho, they have to scroll through the entire list of cities on the table. I first noticed this in 3.5.0 with Bender, Modern and a few other custom themes.

**Comment by dev-101** [comment]
drop-down is working fine for me since much older version,
did you implement it right?

**Comment by darmeth** [comment]
Yes, implemented as per the document. Posting a new advert works fine, it is only on edit where the problem happens.

**Comment by darmeth** [comment]
OK! Finally solved. The instructions need to be changed. Here is how I fixed:

Item-edit.php needs to be:
<?php ItemForm::region_select(osc_get_regions(osc_user_region_id()), osc_user()); ?>
<?php ItemForm::city_select(osc_user()); ?>

Also, there is another error on the doc for item-post.php:
<?php ItemForm::region_select(osc_get_regions(osc_user_country_code()), osc_user()) ; ?>
...
<?php ItemForm::city_select(osc_get_cities(osc_user_region_id()), osc_user()) ; ?>

Should be:
<?php ItemForm::region_select(osc_get_regions(osc_user_region_id()), osc_user()); ?>
...
<?php ItemForm::city_select(osc_get_cities(osc_user_city_id()), osc_user()); ?>

**Comment by dev-101** [comment]
Ah, I see it now, this is the problem with Bender theme and the obsolete article since the time it was written. You are correct, it does not work properly in Bender with suggested code because of a single item_post.php file.
