### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by lamas525** [osclass/Osclass#1823]
Hi, 

This is not issue,this is idea ,but i cant realize it. Can someone fully integrate new reCAPTCHA ?If you cant do it public to this project. Can someone please help me to integrate it to my osclass? i mean no CAPTCHA reCAPTCHA not standart reCAPTCHA .. A lot of thanks for all team and specialy for Conejo.

link to new reCAPTCHA: https://www.google.com/recaptcha

Good luck and i hope see you soon

**Comment by dev-101** [comment]
Hi, it is already in pull requests,

**Comment by lamas525** [comment]
Oh really? Lot of thanks. Sorry for new issue

**Comment by lamas525** [comment]
I integrated it from pull request. Get new keys. But now i see new error. Can you help me pls? 

http://inzertstar.cz/ 

and this is what i get: Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at (blah..blah...blah)/www/oc-includes/osclass/helpers/hUtils.php:301) in (blah..blah...blah)/www/oc-includes/osclass/core/Session.php on line 47

Warning: Cannot modify header information - headers already sent by (output started at (blah..blah...blah)/www/oc-includes/osclass/helpers/hUtils.php:301) in (blah..blah...blah)/www/oc-includes/osclass/utils.php on line 1758

**Comment by dev-101** [comment]
Have you did it properly? Double-check everything again.

Make sure you have nothing that outputs to the browser before that line 47. That error means you have already sent some html before line 47  at Session.php and then tried to use a header value that can't be modified anymore since already sent.

**Comment by lamas525** [comment]
I didnt modify anythink in my site.. Pure NEW Osclass.  I copied all files (full) from commits.. chcecked all commits linked to this pull request. I will check all again and try integrate it again. But I think it must be ok

**Comment by lamas525** [comment]
I checked all again. Integrated again. Maybe it is cuz i integrated new hotfixed from hotfixes branch..

Still getting this errors..

**Comment by lamas525** [comment]
issue is here:

utils.php 1758:

function osc_redirect_to($url, $code = null) {
    if(ob_get_length()>0) {
        ob_end_flush();
    }
    if($code!=null) {
        header("Location: ".$url, true, $code);
    } else {
        header("Location: ".$url);
    }
    exit;
}

**Comment by lamas525** [comment]
Oh i have it.. My bad.. i copied 2 empty lines at end of file hUtils.php.. and this is what happends :D really nice.. 2 empty lines can break admin and do a lot of warnings.. nice .. Thanks all.. nice job

**Comment by lamas525** [comment]
http://inzertstar.cz/user/register

Registration doesnt work... Its unchanged registration from bender theme

**Comment by dev-101** [comment]
Please read the comment section of that PR and linked forum topic for more info. This is not a final commit (it is not merged yet) which means it needs some more stuff to be added for theme compatibility.

**Comment by lamas525** [comment]
Yes, i read it. And i know it isnt final version. Ok I will try to repair it. If I wont success. I will post problem here ok? Thanks ;) Have a nice day

**Comment by dev-101** [comment]
Instead, better continue conversation at original PR, no need to split things on several places.

Fix for your theme (it is Bender-based): do not remove lines 1210-1211, and to avoid duplication of buttons, edit your user-register,php as I explained in the forums. This is temporary solution, though.

**Comment by conejoninja** [comment]
Forgot to tag the issue in the commit, but it's here : 

https://github.com/osclass/Osclass/commit/564389bfcecd1cf14b6b3cf6e1c4ef611d4b3e87
https://github.com/osclass/Osclass/commit/689b5ffab182d8f8aa8769d2f96af151e38bfd13
