### ISSUE TITLE
Email Validation @ Contact Form (email injection protection)

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1825]
Hi,

Original forum topic:
http://forums.osclass.org/development/does-osclass-protect-against-email-injection/

Currently we rely only on js validate and perform no validation against invalid email @ contact form. There should be a step that actually performs the validation step and prevents send function. I successfully submitted several contact forms with disabled js and injection strings (hijack attacks did not work, but forms should not be submitted either).

Thanks,
Regards

**Comment by dev-101** [comment]
There is a validation as I see now, but it passes almost all irregular strings (it only complains if email is missing @ ). One common solution is proposed in #1826.

Not sure if we should be worried, but osc_email_validate() function also has a weakness passing as valid emails containing multiple @ as separators.

**Comment by dev-101** [comment]
preg_match could be modified at the end to allow generic TLDs (4+ characters)

**Comment by garciademarina** [comment]
Will try  to improve the server email validation

https://developer.wordpress.org/reference/functions/is_email/#source

**Comment by garciademarina** [comment]
Bear in mind that email is obtained using Params class, which means the email is sanitized

**Comment by dev-101** [comment]
Hi Carlos,
thanks for improving the helper, but this still does not fix contact controller, as the helper is NOT used there :)
