### ISSUE TITLE
Can't access media

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1827]
I've moved some of the categories around and after that i can't access Settings->Media:
Apache log:
 - [05/Feb/2015:15:39:07 +0100] "GET /oc-admin/index.php?page=settings&action=media HTTP/1.1" 500 

I'm using PHP 5.5 with Opcache and APCu.

**Comment by conejoninja** [comment]
how did you move the categories ? 
I can not reproduce this issue

**Comment by fossxplorer** [comment]
Sorry, it was due to php-gd not being loaded properly! Now it works!
