### ISSUE TITLE
Unable to delete ads

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1828]
I'm trying to delete ads both as user and as admin, i'm just getting "the ad could not be deleted".
How can i delete the ad from the db? Is it enough to delete the entry from table oc_t_item?

**Comment by conejoninja** [comment]
You should use the the admin panel as each item depends on other tables (comments, images, description,...)

**Comment by fossxplorer** [comment]
I get the error as i wrote from admin panel as well :(

![screenshot from 2015-02-06 13 34 04](https://cloud.githubusercontent.com/assets/3185080/6079386/dd8c553e-ae04-11e4-9b8f-3744065175d7.png)

**Comment by conejoninja** [comment]
Did you used any plugin and disabled it now?
If you try to remove some data from the table directly (t_item) then it will complain about some foreign key and point to the table where other information is located.
By default, it's located in (IIRC) 
t_item
t_item_comment
t_item_description
t_item_location
t_item_meta
t_item_resource
t_item_stats

And deleting a listing from the admin panel should delete too from those tables, so probably a plugin created a table and now is preventing you to delete the item.

**Comment by fossxplorer** [comment]
Yes, but not between posting of the ads that i'm unable to delete. Also, i tried to re-enable them, and didn't help. 
Note that when these ads were published, the php-gd module were not loaded and while uploading an image, there was an error. Now i've fixed that. Could that create this issue?
Hmm, ok, i can make a big mess if i start to delete manually in the db.
I'll just disable the ads for now, although it's not desirable.

**Comment by conejoninja** [comment]
Please try to delete them directly from the database to know which table is causing this issue

**Comment by fossxplorer** [comment]
Ok, i'll create a test instance with this prod server and then try to delete.
I'll post the results here!
Thanks a lot and have a good weekend!
