### ISSUE TITLE
Custom fields not visible to admin

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1829]
Although they show up for users, i can't see them in /oc-admin/index.php?page=cfields any longer.
![screenshot from 2015-02-06 14 02 43](https://cloud.githubusercontent.com/assets/3185080/6079693/d91ab53c-ae08-11e4-9be9-57c75301f5af.png)

Any idea why?

**Comment by conejoninja** [comment]
I think I missed something as they appear on the image you shared

**Comment by fossxplorer** [comment]
I think you misunderstood. The 3 you see were just test i created, but i did create 2 custom fields and assigned to some categories. Now i've deleted the test custom fields, still i see my 2 other when posting and viewing ads, but not in the admin:
![screenshot from 2015-02-06 14 43 53](https://cloud.githubusercontent.com/assets/3185080/6080184/bd294cde-ae0e-11e4-9449-11dc91917929.png)
