### ISSUE TITLE
[Feature request] SSL/TLS support

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1831]
Since we are dealing with users and passwords, it's necessary to have the ability use SSL/TLS for an OSClass instance. 
Thanks!

**Comment by conejoninja** [comment]
You could configure your server to redirect to your secure version, this has nothing to do with Osclass, at most, change config.php define('WEB_PATH', 'point here to your https version'); so every request will be redirected to your https version of the website.

**Comment by ajolo2ky** [comment]
It would be nice to send users to https when login in/registering (letting them browse the site in http)
