### ISSUE TITLE
No Fallback for css and js files

### ISSUE THREAD

**Issue by xstable** [osclass/Osclass#1840]
I have try to overload bender. It give some errors, cause minify return 400error.

I figured out, that the folder /css and /js (with all files) have to copy to the new theme-overload. If you didn't do this, it won't work.

BTW: The index.php in the overloding theme... does the "name" still have to be "bender", oder the new one? And what is with the function-name... newOne_theme_info, or keep bender_theme_info().
Here the Documentation doesn't give enough informations about this!

At the moment, I have this:

``` php
/*
Theme Name: stay-together (overload from bender)
Theme URI: http://osclass.org/
Description: overload from bender theme. So don't delete the "bender" Folder in the Theme-Folder!!!
Version: 3.0.1
Author: Osclass
Author URI: http://osclass.org/
Widgets:  header, footer
Theme update URI: bender
Parent Theme: bender
*/

    function stayTogether_theme_info() {
        return array(
             'name'        => 'stayTogether'
            ,'version'     => '3.0.1'
            ,'description' => 'Bender theme'
            ,'author_name' => 'Osclass'
            ,'author_url'  => 'http://osclass.org'
            ,'locations'   => array()
        );
    }
```

**Comment by dev-101** [comment]
Please use forum for this kind of issues. GitHub is reserved for concise bug reports and core improvements.

http://forums.osclass.org/3-4-x/how-to-setup-child-theme/
http://forums.osclass.org/tips-and-tricks/(tutorial)-how-to-set-up-child-theme/
