### ISSUE TITLE
[Feature request] Company accounts and display logo

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1842]
Is it possible to allow for private and company/business accounts? For business accounts we would typically ask for some extra info like business org id etc. 
Also, to be able to display company's logo instead of name is an important feature IMO with link to the companies web site on the logo.

Thanks.

**Comment by OsmanDzudzevic** [comment]
This is much needed. Any ideas on what approach should we take of creating this feature ?

**Comment by conejoninja** [comment]
There's already a b_company field in the user profile which serves to identify individuals and companies. Please, ask in the forums, about how to use it. As this place should be left for issues and bugs.
