### ISSUE TITLE
PHP Notice: Use of undefined constant __FROM_CRON__

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1848]
Upgrade generates notice about unescaped constant https://github.com/osclass/Osclass/blob/master/oc-admin/ajax/ajax.php#L537

```PHP Notice: Use of undefined constant __FROM_CRON__ - assumed '__FROM_CRON__' in oc-admin/ajax/ajax.php on line 537```

**Comment by conejoninja** [comment]
It doesn't make sense to me, if __FROM_CRON__ is not defined, then the first part of the conditional should be true and there's no need to check the second part (!__FROM_CRON__) ...

**Comment by dev-101** [comment]
I am not sure either (thus no PR with simple @), but on 2 websites it generated the same notice :(

**Comment by dev-101** [comment]
Hi Conejo, strange, but the master branch I've linked above and my ajax.php file already has the quotes around magic constant - what am I missing?

**Comment by conejoninja** [comment]
I thought the same, I'm not sure, but some changes were made in master but not in hotfixes or viceversa. "Now" master and hotfixes should have the  same code and all the changes (I hope so)

**Comment by dev-101** [comment]
I have also noticed few differences, so had to manually sync my local hotfix and develop branches, but still, not sure if this will fix the issue - I mean, I already have this change in place during upgrade?

**Comment by conejoninja** [comment]
Depends on what version did you have back then and from which version did you upgrade.
I think version 3.5.3 was made from hotfixes, which lacks of this fix instead of master, which had it fixed.

I tested it and I didn't get the notice, but now I 'm not sure about anything

**Comment by dev-101** [comment]
:)

Ok, will auto-upgrade in few minutes and report back -- Thanks!

**Comment by dev-101** [comment]
Ok, except the weird message in admin "Problems when copying files. Please check your permissions.", I just hit Upgrade button afterwards and everything went fine.

perms/owns are properly set as far as I can say and they weren't changed for months, why this message appeared now is beyond me.

Anyway, notice has been fixed - Thanks!
