### ISSUE TITLE
Listing Verification broken in 3.5.5

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1849]
If listing verification option is checked, verification does not work anymore and upon clicking the verification link, dual flash messages are presented (OK and warning), but the item is never activated.

```PHP Notice: Undefined offset: 0 in oc-includes/osclass/ItemActions.php on line 567```

![2015-03-26_001305](https://cloud.githubusercontent.com/assets/5383059/6837472/df71b764-d34c-11e4-9391-df49da65d60f.png)

**Comment by conejoninja** [comment]
Did you upgraded from hotfixes or master or did you use the admin panel ?

**Comment by dev-101** [comment]
Hi Conejo, I have auto-upgraded from admin to official version, also in forums other members noticed this issue as well, temporarily reverting to 353 fixed the issue, clearly indicating problem was in recent changes.

This commit seems to have fixed it - thanks!
