### ISSUE TITLE
Osclass 3.5.5: Users couldn't validate their ads from validation mail

### ISSUE THREAD

**Issue by teseo-2014** [osclass/Osclass#1850]
http://forums.osclass.org/3-5-x/news-update/msg118414/#msg118414

__oc-includes/osclass/model/Item.php__

Apparently, changing line 190:
                        __$args[$k] = $this->dao->escape($v);__

to:
			__if ( !is_numeric($v) ) $args[$k] = $this->dao->escape($v);__

solves this issue.

**Comment by conejoninja** [comment]
Was fixed here : https://github.com/osclass/Osclass/issues/1849
