### ISSUE TITLE
Change oc-admin string "Listing"

### ISSUE THREAD

**Issue by MartaOsclass** [osclass/Osclass#1852]
Oc-admin menu, section "Listing" must be "Listings"

**Comment by dev-101** [comment]
Sorry about this little mess, last one is correct https://github.com/osclass/Osclass/pull/1855

At first, I've forked master branch by accident which still seems to be ahead of hotfix branch (as of 3.5.6 release) and it created some unwanted parts of PR.

**Comment by garciademarina** [comment]
already merged
