### ISSUE TITLE
Custom Field is not showing as Default Fields.

### ISSUE THREAD

**Issue by savenhero** [osclass/Osclass#1856]
Hello
I have an issue" I added a Custom Field Called "Bidding Amount" which is appearing at the last.
The main issue is "Bidding Amount Field" is not appearing default when i click on "Publish you Add Free"
After selecting the category this field is appearing....
Please help to overcome from this issue.
http://www.lateraleducation.com/item/new
I am sending two attachment of " Before selecting category" after selecting category.
I have also tried through coding in the backend,  through coding fields is not working...

![before selecting category](https://cloud.githubusercontent.com/assets/11793338/6991396/02ad6d2c-daaf-11e4-9c96-e22f85796c24.png)
![after selecting category](https://cloud.githubusercontent.com/assets/11793338/6991397/07c5bf12-daaf-11e4-9042-de6327265d99.png)

Please help me to solve this..

**Comment by dev-101** [comment]
There is no such thing as "Default Field", each one must be linked to at least one category.

**Comment by garciademarina** [comment]
not issue
