### ISSUE TITLE
Preference 

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#1867]
We need more methods in (Preference class) to work with preferences .
Class is instatiated(query is made ) .
We can acces only 1 preference at  the time  get method( $this->pref[$section][$key] ) 
We need acces to ($this->pref[$section) (getBySection ? )
We also need acces to all preferences " (return $this->pref)". (getAll ?) 
Any new attempt to find by section  will produce a new db query to look for preferences that is already  extracted  in toArray method. on  class construct 

Thanks .!

**Comment by web-media** [comment]
Some  of needed  methods among others:
  get-All-preferences(to return all extracted  preferences) ,
  get-All-Sections(return an array  of  sections from already extracted  preferences)  ,
  get-By-Section (return all values from desired  section from already extracted preferences) 
  unset all preferences

**Comment by web-media** [comment]
Some thoughts:
```php
 public static function newInstance() {
        
        if (!self::$instance instanceof self) {
            self::$instance = new self;
            self::$instance->toArray();
        }
        return self::$instance;
        
    }


    /**
     *
     */
    
    function __construct() {
        parent::__construct();
        $this->setTableName('t_preference');
        /* $this->set_primary_key($key); // no primary key in preference table */
        $this->setFields(array('s_section', 's_name', 's_value', 'e_type'));
//       $this->toArray();
    }
 public function getBySection( $section = "osclass") {
        if (!isset($this->pref[$section])) {
            return '';
        }
        return $this->pref[$section];
    }
    /**
     * Get all preferences
     *
     * @access public
     * @since unknown
     * @param string $key
     * @return string
     */
     public function getAll( ) {
        if (!isset($this->pref)) {
            return '';
        }
        return $this->pref;
    }

    public function replace($key, $value, $section = 'osclass', $type = 'STRING') {
        static $aValidEnumTypes = array('STRING', 'INTEGER', 'BOOLEAN');
        $array_replace = array(
            's_name' => $key,
            's_value' => $value,
            's_section' => $section,
            'e_type' => in_array($type, $aValidEnumTypes) ? $type : 'STRING'
        );
        $this->set($key, $value, $section, $type = 'STRING');
        return $this->dao->replace($this->getTableName(), $array_replace);
    }
```

**Comment by dev-101** [comment]
Hi Conejo,
after applying this patch, a lot of notices are generated:

```
PHP Notice:  Undefined index: crypt_key in oc-includes/osclass/model/Preference.php on line 148
```

this is because `isset($this->pref[$section]` can be true without key, which is explicitly returned in the next line.

**Comment by conejoninja** [comment]
Thanks, I messed up the operators, should be fine now

**Comment by dev-101** [comment]
Thanks, working fine now :)

**Comment by dev-101** [comment]
Hi Conejo, just one more thing :)

Maybe I see double, but there is a duplicate condition here: https://github.com/osclass/Osclass/commit/0e53ac79e1eba7c35cf07b660b62233e5900a6af#diff-519faa8ab91ce6ee3f925c7e2bc21de4R163

**Comment by conejoninja** [comment]
done, thanks a lot

**Comment by dev-101** [comment]
np :+1:
