### ISSUE TITLE
t_pages sharing email templates with pages

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1869]
I think this should be separated in 2+2 distinct tables, instead of keeping them joined/mixed as it is now:

t_email_templates
t_email_templates_description

t_pages
t_pages_description

Not only from organizational point of view, but also pages will have lower id values. From time to time I keep forgetting where templates are stored and keep looking for a non-existent templates tables :)

Any thoughts on this?

**Comment by conejoninja** [comment]
Tables will have the same fields, so it makes sense there's only one table, one model,...

**Comment by dev-101** [comment]
Hi CONEJO,
I know it will require some extra code and changes... but it is a little unorganized :(
Just when I look at my templates and pages mixed, doesn't look nice at all, also page id's are high right from the start because templates are taking them upon install.

**Comment by dev-101** [comment]
Hi, I actually did something smarter: manually sorted templates to start with id=1001+ and pages from id=1+. No core mods needed. Of course, any new page/template will have to be sorted manually, but that's not a big issue. One of the things that made suggest this change was the sort option that does not do anything:

![t_pages order](https://cloud.githubusercontent.com/assets/5383059/7368721/46808cfa-edab-11e4-8c7e-9865c46e0ad9.png)
