### ISSUE TITLE
Increase minimum version of php to 5.6.X

### ISSUE THREAD

**Issue by garciademarina** [osclass/Osclass#1886]
Increase minimum version of php to 5.6.X, make it optional.

**Comment by conejoninja** [comment]
Installation requires now at least PHP 5.6 version.

I did not remove any compatibility library, but we should clean them sometime in the future, but it will break Osclass for people running old versions of PHP.

**Comment by dev-101** [comment]
Thanks, just don't forget to update download page https://osclass.org/page/download as well.
