### ISSUE TITLE
Delete Account cancel button not working

### ISSUE THREAD

**Issue by luckygoyal** [osclass/Osclass#1887]
The cancel button in the delete account is not working. But when I click in the square in the top bar it disappears.

**Comment by luckygoyal** [comment]
It works in the internet explorer but does not work on chrome.

**Comment by luckygoyal** [comment]
It is working in mozilla also. It is not working for chrome.

**Comment by conejoninja** [comment]
We can not reproduce the issue, which theme are you using?

Please check on the developer console (chrome or firefox) if there's any Javascript error
