### ISSUE TITLE
osclass mail server settings not working

### ISSUE THREAD

**Issue by anoob-kd** [osclass/Osclass#1894]
am using OsClass 3.5.7 version and MySQL
we can't able to send and receive mail
plz help me :(

**Comment by conejoninja** [comment]
https://doc.osclass.org/Setting_up_a_mail_server
https://blog.osclass.org/2013/01/29/set-up-your-mail-server-for-osclass/

**Comment by anoob-kd** [comment]
that one is note working,

**Comment by conejoninja** [comment]
You have a problem of configuration, not a bug in the code, please post your problem in the forums : http://forums.osclass.org/

**Comment by anoob-kd** [comment]
See this screenshot 
http://my.jetscreenshot.com/demo/20150715-mvut-26kb

**Comment by conejoninja** [comment]
GMail may or may not allow sending emails via SMTP (IIRC you need to activate it in the configuration of your gmail account, it's known that gmail blocks some emails from/to the same email, or if the ip is in a blacklist).

You have a problem of configuration, not a bug in the code, please post your problem in the forums : http://forums.osclass.org/

**Comment by anoob-kd** [comment]
Email Setting already open ,
can we send the code to you

**Comment by anoob-kd** [comment]
help me

**Comment by conejoninja** [comment]
This is not the place, please go to the forums : http://forums.osclass.org/
And I already told, it's a configuration problem or gmail for some reason is blocking/not sending your emails.

**Comment by anoob-kd** [comment]
ok thanks you

**Comment by anoob-kd** [comment]
hi dear ,
i am got another bug

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\osclass\oc-includes\osclass\classes\database\DBCommandClass.php on line 1001

**Comment by conejoninja** [comment]
A SQL query took too long to execute, it could be an not-optimized query or maybe your sql server is under heavy load and slow.

Please, post your problems in the forums: http://forums.osclass.org/ (4th time I ask you to do so).

It's NOT ok to hijack this issue and post a different problem. Please, post your problems in the forums.

Regards
