### ISSUE TITLE
session_start(): The session id is too long or contains illegal characters

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1899]
original forum topic here:
http://forums.osclass.org/3-5-x/session_start()-the-session-id-is-too-long-or-contains-illegal-characters/

I have never seen this warning, but never the less, this could be a potential vulnerability issue if error reporting is on, disclosing path to the session class file. Also, I have no idea how is he triggering it inside Chrome (compromised browser? computer? something else?). Not sure, really.

In any case, I think we should add preg_match check and return false, just in case, e.g.
http://php.net/manual/en/function.session-start.php#82957

*adapted for Osclass e.g.

```
    if (!preg_match('/^[a-z0-9_]{31}$/', $sessid)) {
        return false;
    }
```

---

`UPDATE:`  I have easily triggered this error with a simple attack and it should be def. fixed.

**Comment by garciademarina** [comment]
remember to regenerate session  id
