### ISSUE TITLE
Red flash messages are in one line

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1900]
Please make the needed changes so that if we have multiple errors in a page, see them one on a line, not all of them combined into a single line.
You can see example and fix here http://forums.osclass.org/general-help/error-messages/

Another example of combine errors is this 
![screen shot 2015-08-04 at 13 01 39 1](https://cloud.githubusercontent.com/assets/5921012/9065246/5e329786-3a85-11e5-9433-7fe6a9b9aba6.png)

Please note that this happens in some areas and in another we see each error in a single line as we should. So please unify them. Thanks

**Comment by Adyyda** [comment]
Once you apply the fix provided by Teseo we see them properly, as they should
![untitled](https://cloud.githubusercontent.com/assets/5921012/9065402/103b59ea-3a86-11e5-82c2-e0878f63052a.jpg)

**Comment by dev-101** [comment]
I can hardly say that this version is any "better". The reason why you see different lines in some "areas" is because they trigger different validation sections/errors. They are separate messages altogether.

**Comment by Adyyda** [comment]
I see. So a mambo jambo of mixed errors in one line is fine for you. Ask 10 peoples and see what they reply...

**Comment by dev-101** [comment]
It is multi-flash messages feature inside Osclass. It is not mambo-jumbo :)

**Comment by Adyyda** [comment]
In which language phrases end without any punctuation? In none i think. You like them all in 1 line? Fine, but let's place than some . or other mark after each of them so users understand eventually that they are separate messages.

**Comment by dev-101** [comment]
That's a bug, there should be a dot.

**Comment by eurobank** [comment]
It is actually "Mumbo Jumbo" and not Mambo Jambo

**Comment by phox081** [comment]
"n" error messages in one line... mumble mumble... without punctuation or separation between them...  It's a good idea if you want your users do not understand your messages. The Solution is not in translations, but separate them in "n" lines, I think.
