### ISSUE TITLE
Manage Listings Link Produces a blank page in Google Cloud

### ISSUE THREAD

**Issue by xonuox** [osclass/Osclass#1901]
We recently installed two separate installations of osclass:
1.  on a shared hosting environment - that we control
2.  on google cloud

Our current issues with deploying osclass to google's cloud platform is that when we click on the Manage Listings link, osclass produces a blank page.  We also have an issue under TOOLS - UPGRADE OSCLASS where it states that it can not be auto-upgraded.  We are investigating the file permissions...but wonder if this is also causing the blank page issue with Listings.

Any assistance in better understanding what could be causing the Listing problem would be greatly appreciated.

Thanks...Mike

**Comment by eurobank** [comment]
Github is not for Support of Osclass. Please post your problems at forums.osclass.org

**Comment by conejoninja** [comment]
Please enable PHP & MySQL debug to see if there is any error, also are you using any plugin? disable them and enable one by one to discard them too. Post your results at the forums https://doc.osclass.org/Debug_PHP_errors https://doc.osclass.org/Debug_SQL_queries

**Comment by conejoninja** [comment]
Please enable PHP & MySQL debug to see if there is any error, also are you using any plugin? disable them and enable one by one to discard them too. Post your results at the forums https://doc.osclass.org/Debug_PHP_errors https://doc.osclass.org/Debug_SQL_queries
