### ISSUE TITLE
Users are able to remove their email address

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#1902]
I see a lot of empty email from registered users. They should not be allowed to remove their emails IMHO.

Thanks
![screenshot_1](https://cloud.githubusercontent.com/assets/4467158/9156491/8dda6b4a-3ee4-11e5-94fa-3e7eeac6b8c1.png)

**Comment by garciademarina** [comment]
not an issue, it's because some plugins have foreign keys and are not removed correctly so some registers are not removed.

**Comment by eurobank** [comment]
But you missed to understand the issue. As usual.
