### ISSUE TITLE
There was a problem with the alert

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1911]
When we are in search page, we have the ability to save the search. All fine except the fact that once saved, there is no mention that the search is already saved and if the user will revisit the search area and will try to save the same search again it will receive the message "There was a problem with the alert". Meaning what? How can the user know what that means? The message should be something like "You already saved this search". This important area needs to be improved so that will show the fact that the search is already saved and have the ability from the search page (same block) to cancel this subscription, without the need to go to the user account.

**Comment by conejoninja** [comment]
themes should include this feature too, not only the core.
