### ISSUE TITLE
Error page after submitting edited listing by not registered user 

### ISSUE THREAD

**Issue by efathi** [osclass/Osclass#1912]
For non-registered users, if they try to edit their ad through the link they have received, after editing and pushing submit button it will go to an error page "Sorry but I can't find the page you're looking for". Checking the DB, the records have been updated.

This won't happen if you have already logged in to the admin dashboard or you have validated your ad. Please help solve this problem. I ma guessing it is related to the cookies.

**Comment by garciademarina** [comment]
I cannot reproduce the issue.
