### ISSUE TITLE
When admin logs out and go to frontend to login as a user, login fails and it redirects to admin login page

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1913]
Hi,

Let's try this once again, this is an ongoing and very old issue still unresolved.
Admin has 2 accounts (main admin & frontend user with different email/paswd):

1) Admin logs into admin dashboard
2) Admin logs out, at this point its back to admin login page
2) Clicks on top left URL/title to go to frontend
3) Goes to frontend user's login page
4) log in -> fails -> it gets redirected to admin login page
5) manually return to frontend page -> nope, admin is still not logged-in (as a user with diff account).

Only way to fix this is restart browser / destroy session / delete cookie. This is confirmed (regardless of the theme) on several clean test setups and even local installation.

Most recent forum discussion here:
http://forums.osclass.org/tips-and-tricks/login-website-returns-to-admin-page-gt-fix/

**Comment by dev-101** [comment]
Hi Carlos,
I think we should avoid using hard-coded 'oc-admin' path (if possible).

Thanks

**Comment by garciademarina** [comment]
oc-admin path it's already hardcoded on the core, we will continue using oc-admin as a string for this case.

**Comment by dev-101** [comment]
Well, I was working on experimental extension that could change that... but now you are complicating things :)

You see, there is a difference when you define something in one place,
but once it is defined, it is natural to use abstract definition of it instead the actual value (which might be changed). It is easy to get a clean path in this case with simple subtraction of 2 previously defined values.


```
$l = strlen(osc_base_url(false));
$p = str_replace('/', '', substr(osc_admin_base_url(false),-$l));
```
