### ISSUE TITLE
& character in search

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1921]
This issue seems to be related at least to some extent with the old slash search problem here #1797.
Combined keywords with & character keeps only the first word and strips down everything past &.

e.g. "test & test"

Now, here is the `good part` : fresh WordPress installation with various permalinks on the exact same server (apache, local, nothing special) is working fine with both `/` and `&` characters and search functions normally. Additionally, 2 remote servers also do not have any issues with WordPress and characters are url encoded, of course.

This clearly indicates that the way parameter is treated or at some later stage it gets corrupted and breaks normal search functionality with this special characters for some reason.

Unlike previous issue, this one is present both w/wo permalinks.

Solution? Well, I am not that deep into the core yet, but I see that some filtering is going on in the background. Could it be that the HTML Purifier is the cause of all the trouble? Or some regex/rewrite rule?

**Comment by garciademarina** [comment]
@dev-101 I think it's fixed and we think we did not add any bug, 

can you check please?

**Comment by dev-101** [comment]
Will do, hang on...

**Comment by dev-101** [comment]
well, it works, buut...

`test & test`

gets url encoded as

`test+%26amp%3B+test`

because `&` if first tranformed into `&amp;` and it shouldn't

**Comment by dev-101** [comment]
while you are at it, is it possible that we properly extract `/` slash?
(works in WP)

**Comment by dev-101** [comment]
Hi Carlos, after few days of testing sometimes a notice is generated with the above change:

`PHP Notice:  Undefined offset: 3 in oc-includes/osclass/classes/Rewrite.php on line 194`

For example, when I edit an item, it triggers the notice and offsets could be a random number apparently (3, 8, ...)

**Comment by dev-101** [comment]
@garciademarina @conejoninja

:beers:
