### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by fossxplorer** [osclass/Osclass#1927]
Hi,
i'm filing my issue again as i still can't solve it.
I have some categories with names such as "kjøretøy" and when i click that category, there is a redirect loop. Also, the browser shows "http://mydomain.com/kjøretøy" instead of http://mydomain.com/kj%C3%B8ret%C3%B8y.
Is there any fix for this critical issue by now?
Is there no way of displaying æ as ae, å as a and ø as o?

Thanks.

**Comment by fossxplorer** [comment]
Sorry i didn't see the commit https://github.com/conejoninja/Osclass/commit/e9b4b3d668e51fe8f4982694eb0bec4148efbee8.

Now it works mostly, except for the character 'ø' :(

**Comment by conejoninja** [comment]
Please, edit (without changes) a subcategory and tell us if that worked. IIRC, when a category (or subcateogry) is edited, the slug (url) is generated. So just go to Settings > Categories, select a subcategory and click edit > save.

Tell us if that worked.

**Comment by fossxplorer** [comment]
It worked perfectly @conejoninja 
Thanks a lot :sunglasses:
