### ISSUE TITLE
BUG regarding HTTP URL syntax with query standard (every URL is based on this)

### ISSUE THREAD

**Issue by ModDM** [osclass/Osclass#1928]
The function of the URL query as part of the HTTP URL syntax standard is missing in Osclass, in the URL custom field feature. Osclass users who want to use this feature will see this doesn't work yet. This is a bug.

Every HTTP URL conforms to the syntax of a generic URI. A description (simplified):
domain[/]path[?query]

The query is a sequence of attribute–value pairs separated by a delimiter.

Query delimiter        |  Example
-----------------------------|-----------------------------------------------
Ampersand ( & )       |  key1=value1&key2=value2
Semicolon ( ; )         |   key1=value1;key2=value2

I didn't test the Semicolon delimiter, but the Ampersand (&) delimiter is not working in your sites' admin > Listing > Custom fields > Add new > Type > URL. I explain:

The Ampersand (&) has an important function as a delimiter, but when people (users of an Osclass site) enter their site address (URL) containing these delimiters into this custom field, then the Osclass system changes the Ampersand (&) into & amp; (HTML code of &). This is not conform the HTTP URL syntax standard and the resulting URL (after submitting via that custom field) will redirect people to a page saying "Page not found!".

Can this be corrected in a next version of Osclass?

**Comment by dev-101** [comment]
This is because all fields are treated equal and sanitized as html, this could be quit & dirty fix, but effectively bypassing xss check. Not sure how dangerous this could be, so better wait for some senior dev to check it. Simple dedicated plugin for URL field could be alt solution.

https://github.com/osclass/Osclass/commit/cfcf3e8590e9c634e1aec88d1f576b48f326da80

**Comment by ModDM** [comment]
Dear Sir / Madam,

I am glad somebody read this issue I posted, so that it is also read that these URLs are not working. I report this, not because I just 'think' something, but because I have a big problem with this since many months (so I have tested enough before posting here). Let's show you an example that these URLs don't work, then you can see it in practice and skip the theory and hopefully this will be fixed soon:

To clearify, my subject applies only to URL custom fields:
Osclass admin > Listing > Custom fields > Add new > Type > URL

Example: Here you can see the below link works. But to seriously know what I am talking about, try to enter this link in the Osclass custom field, to see if this works. The answer will be no.

For example look at this super modern website: www.designstoelenenfauteuils.nl

Why is Osclass not able to link to pages on this site? For example this link:

http://www.designstoelenenfauteuils.nl/index.php?route=product/category&path=67

Now try to open the above link again, but then how Osclass handles it:

Add the same 4 failing characters in the URL as Osclass does and those are the following 4 characters: amp;
You have to add those characters directly after the & in the URL. Result: Page can not be found. In Dutch language it tells you "Category not found" (Categorie niet gevonden!).

Dear Osclass, this is a real big problem. Osclass is meant to place ads. For ads it is important that people can place a link to their website that relates to the ad. If it doesn't work then please don't refer to situations in which it does work, but it would be appreciated if you would solve the problem that exists in practice as I showed you. No reason to change many codes of the entire Osclass system, I am just talking about the URL custom field feature, that is found here:
Osclass admin > Listing > Custom fields > Add new > Type > URL

Very much thanks in advance.

Kind regards,

ModDM

**Comment by ModDM** [comment]
Dear Dev-101,

Thank you very much for your alt solution.
About your dedicated plugin: That's appreciated. And please: Could you
maybe instruct me a little bit with the steps to take to add your plugin to
Osclass? For example which FTP files do I have to add, or is this done
without FTP? For me this is a little bit difficult, I have some trouble to
understand how to add such a plugin. It would be super to receive some
instructions from you, because I was looking forward to such a solution for
many months now - I only have to add that plugin you sent me the link from.
Are you sure this solves the failing HTML treatment of the & sign in this
below URL feature?
Osclass admin > Listing > Custom fields > Add new > Type > URL

Any instructions to add the plugin would be much appreciated and thanks in
advance,

With kind regards,

ModDM

P.S.
I posted a longer answer to confirm more facts that show I really have big
problems with this URL failure since many months (the details are found in
that answer). So I hope the Osclass team will release a permanent solution
for the URL failure of this feature:
Osclass admin > Listing > Custom fields > Add new > Type > URL
ᐧ

2015-10-14 0:24 GMT+02:00 dev-101 <notifications@github.com>:

**Comment by dev-101** [comment]
Hi ModDM,

yes, I have tested URL field yesterday and URLs are working properly. It is possible that you have a theme-related issue.

Regards

**Comment by dev-101** [comment]
For plugins, please check documentation http://doc.osclass.org/ and forums.

Plugins are installed this way:
1. unzip plugin (plugin name must be in format `my_plugin_name`, not `my plugin name` or `my-plugin-name`
2. upload this directory to oc-content/plugins/ folder
3. go to Admin Dashboard > Plugins > and click on Install in the plugin table wor/column that belong to that particular plugin you wish to install.

**Comment by ModDM** [comment]
Hello, Can you please replicate my issue not with a changed and modified
Osclass installation, but with a pure Osclass installation as literally
downloaded from the Osclass website? Otherwise you are not doing the same
as I did, which makes it difficult to communicate about the same subject.
So can you do the same steps as I did? Regards, ModDM
ᐧ

2015-10-14 12:37 GMT+02:00 dev-101 <notifications@github.com>:

**Comment by ModDM** [comment]
Thank you, I will directly try this.
ᐧ

2015-10-14 12:40 GMT+02:00 dev-101 <notifications@github.com>:

**Comment by ModDM** [comment]
Dear Dev-101,

Maybe we don't understand each other. Did you had a fix or plugin for me to try to solve this issue? If so, was that the solution on that link you sent me? If so, those are only codes, I don't see download ZIP in format my_plugin_name as you described. My intention is to try the possible solution you mentioned and how to install that. Thank you in advance,

Regards, ModDM

**Comment by dev-101** [comment]
Sure, take a look by yourself here:
http://myvpsdemo.tk/community/events/test_i43

Website Address is working fine.

**Comment by dev-101** [comment]
Hi, I see now that you are correct. Browser will treat `&amp;` literally and this will break the URL.

I have tried to add this URL for test:
https://demo.osclass.org/cars/index.php?page=item&id=760

and it was converted to html encoded version, which does not work:
`https://demo.osclass.org/cars/index.php?page=item&amp;id=760`

**Comment by conejoninja** [comment]
I'm missing something, just to be clear, is the problem with URLs in general or only with URL in "custom fields"?

**Comment by ModDM** [comment]
Only in custom fields.

**Comment by dev-101** [comment]
Hi Conejo, only in CFs

**Comment by dev-101** [comment]
It should be fixed in function osc_item_meta_value() helper, there is a htmlentities() on the values, just testing it...

**Comment by ModDM** [comment]
Thank you dev-101, I am glad you tested it yourself with your links and came to the same conclusion. I am interested in the solution, good to hear you test it.

**Comment by dev-101** [comment]
Here's one way to fix this, mind you, this will not please W3C because of that &, but I don't care for that really, as per recent development:

https://github.com/osclass/Osclass/commit/0468f471e7f491b3cf229e45dd32a8c839ba7759

**Comment by ModDM** [comment]
I don't have to replace the file, but only change the codes you show there in the below file?
oc-includes/osclass/helpers/hItems.php

**Comment by dev-101** [comment]
here is the file
https://raw.githubusercontent.com/osclass/Osclass/0468f471e7f491b3cf229e45dd32a8c839ba7759/oc-includes/osclass/helpers/hItems.php

**Comment by ModDM** [comment]
ok thank you

**Comment by dev-101** [comment]
Hi Conejo, I think we should merge this. It definitely fixes the problem.
If you look into source code of GitHub itself, they are doing it that way, too.

**Comment by ModDM** [comment]
Dear dev-101,

I just tested it and it works great. The new codes even restore the links of existing ads into the right ones. Thanks for THE solution!

Kind regards,

ModDM

**Comment by dev-101** [comment]
Thanks, glad it works :)
