### ISSUE TITLE
MySQL Duplicate Index issue in Osclass

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1929]
forum topic here:
http://forums.osclass.org/3-5-x/database-issue-30878/

Apparently, after each upgrade Osclass adds index to tables, which is a performance/resource and upgrade issue.

In MySQL 5.6 duplication detection will throw notice, and in 5.7 a warning.

**Comment by dev-101** [comment]
Here's the upgrade log excerpt (just tested 353->357):

```
Line 477: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_category ADD INDEX (fk_i_parent_id)
Line 479: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_category ADD INDEX (i_position)
Line 481: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_city ADD INDEX (fk_i_region_id)
Line 483: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_city_area ADD INDEX (fk_i_city_id)
Line 485: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item ADD INDEX (fk_i_user_id)
Line 487: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item ADD INDEX (fk_i_category_id)
Line 489: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item ADD INDEX (fk_c_currency_code)
Line 491: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item_comment ADD INDEX (fk_i_item_id)
Line 493: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item_resource ADD INDEX (fk_i_item_id)
Line 495: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_item_stats ADD INDEX (dt_date, fk_i_item_id)
Line 497: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_keywords ADD INDEX (fk_i_category_id)
Line 499: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_keywords ADD INDEX (fk_i_city_id)
Line 501: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_plugin_category ADD INDEX (fk_i_category_id)
Line 503: [13-Oct-2015 01:00:06 Europe/Madrid]  --- ALTER TABLE oc_t_region ADD INDEX (fk_c_country_code)
```

and the immediate check of the results:

![result](https://cloud.githubusercontent.com/assets/5383059/10441206/99c0b98e-7146-11e5-871a-f3d23bc6bffd.png)

**Comment by dev-101** [comment]
osc_updateDB() needs to be fixed/updated to avoid adding existing indexes to the tables.

**Comment by conejoninja** [comment]
Could you run on your mysql server the followings queries?

```sql
DESCRIBE oc_t_category;
SHOW INDEX FROM oc_t_category;
SHOW CREATE TABLE oc_t_category;
```

Thanks

**Comment by dev-101** [comment]
Hi Conejo,

I have already repeated several tests and resolved this issue manually (check forum for idea).
SHOW INDEX command will display all duplicate indexes which are generated after each upgrade (tested manual and auto upgrades from 343, 353, 356... does not matter). Each successive upgrade will re-create new indexes on tables, exact copies which are auto-renamed.

osc356->357
![db](https://cloud.githubusercontent.com/assets/5383059/10480960/de5eba1e-726d-11e5-8def-70e40edd229c.png)

Solution to this problem must have 2 parts: fix current situation during auto-upgrade for all existing-active users, and prevent it from happening in the future versions. One way is to name those indexes on all new installations (teseo's advice), the second one is to write a simple upgrade funcs script that will do this SQL (early morning concept design, you'll get an idea):

`
i=2;
while(i<=100) {
DROP INDEX i_position . _$i ON %s_t_category;
DROP INDEX fk_i_parent_id_ . $i ON %s_t_category;
DROP INDEX fk_i_region_id_ . $i ON %s_t_city;
DROP INDEX fk_i_city_id_ . $i ON %s_t_city_area;
DROP INDEX fk_i_user_id_ . $i ON %s_t_item;
DROP INDEX fk_i_category_id_ . $i ON %s_t_item;
DROP INDEX fk_c_currency_code_ . $i ON %s_t_item;
DROP INDEX fk_i_item_id_ . $i ON %s_t_item_comment;
DROP INDEX fk_i_item_id_ . $i ON %s_t_item_resource;
DROP INDEX dt_date_ . $i ON %s_t_item_stats;
DROP INDEX fk_i_city_id_$i ON %s_t_keywords;
DROP INDEX fk_i_category_id_ . $i ON %s_t_keywords;
DROP INDEX fk_i_category_id_ . $i ON %s_t_plugin_category;
DROP INDEX fk_c_country_code_ . $i ON %s_t_region;
i++;
}
'
Above tables are affected and if you used on some auto-upgrade or manual upgrade with overwrite, sure you got this problem.

**Comment by dev-101** [comment]
Hi Conejo,

we really need this fix as soon as possible, it is 'annoying' to recreate duplicate indexes every time an upgrade is performed, either manual or auto and to remove them from database each time.

This is one of the most important issues right now :)

Thanks!

**Comment by conejoninja** [comment]
This should fix the issue

**Comment by dev-101** [comment]
Both for new and existing installations?

**Comment by conejoninja** [comment]
It will not remove duplicated indexes, but it will avoid creating new ones

**Comment by dev-101** [comment]
Ok, thanks. It is always a good idea to name indexes, so at least we will not have a problem like this anymore.

Thanks! :beers:

**Comment by conejoninja** [comment]
thing was there were some unnamed indexes and the check if they existed or not failed over and over again, now it shouldn't fail anymore.

**Comment by dev-101** [comment]
:+1:
