### ISSUE TITLE
init_admin hook runs 2x

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1948]
It looks like init_admin hook is run twice if admin is not logged in (@ admin login page).

1) I think it should be removed from AdminBaseModel
2) or we can rename it

**Comment by conejoninja** [comment]
https://github.com/osclass/Osclass/commit/bd43d757cdbd571d3b72243a1dd3e7ce29f57287

**Comment by dev-101** [comment]
Hi Conejo, thanks for fixing this

I wonder... old hook @ login.php could be something like 'before_admin_login_form' , it probably doesn't make any sense, but just in case. What do you think?

**Comment by conejoninja** [comment]
I'm not really sure what was the purpose of the hook there, but I will take a look to the hooks for the next "big" (not hotfixes) release

**Comment by dev-101** [comment]
Thanks!
