### ISSUE TITLE
Can't add items

### ISSUE THREAD

**Issue by nelsonsb** [osclass/Osclass#1953]
I don't know if you can help me.

The users of my site can't add items.  The process report 406 error.

I think that the problem is server, but can't create support ticket because I don't know what is error.

I activate debug errors but don't show nothing.

The site work fine and have good speed, but this function doesn't work.

Thanks

**Comment by conejoninja** [comment]
Which theme are you using?
Can't reproduce the issue

**Comment by nelsonsb** [comment]
Solved.

The problem was php settings in hosting.

Thanks
