### ISSUE TITLE
UNABLE TO UPLOAD MORE THAN 1MB PIC when posting a listing

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#1957]
hai i  am unable to upload more than 1mb pic, classibook.com/phpinfo please check it and inform me whats the issue...  

debug error :
[24-Oct-2015 20:21:02 Asia/Kolkata] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 42042001 bytes) in /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php on line 68

**Comment by conejoninja** [comment]
switch to imagick instead of gd if you have it enavled in yout server or configure php to use more ram. this is a configuration issue and not a code one. please ask in the forums

**Comment by abdulghanysyed** [comment]
yes that is the my issue also sir, in server imagic was enable and also it was displaying in admin pannel as enable, but still imagic not working
