### ISSUE TITLE
Fatal error: Allowed memory size of 67108864 bytes exhausted

### ISSUE THREAD

**Issue by AlexL777** [osclass/Osclass#1963]
Hello Developers,
I have shown with the latest version of osClass a problem and although I use the Free Bootstrap Responsive Theme and me is in the footer this error message.

    Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /www/htdocs/xxxxxxx/oc-includes/osclass/core/View.php on line 67

Could you possibly help me there?

Would be grateful for it. Regards, Alexander

**Comment by conejoninja** [comment]
raise your php memory limit, i think 64mb is a too low value, but does this happen with any other theme? it is strange that you required such high values in regular pages

**Comment by AlexL777** [comment]
Thank you, and thou hast brought me to the idea. I have the memory limit increases in the .htaccess and lo, the error message is gone. Excellent!
