### ISSUE TITLE
"Ajax error, please try again." when changing the category order

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1965]
forum topic here: (and some others)
http://forums.osclass.org/general-help/get-the-error-'ajax-error-please-try-again-'-when-change-the-category--30288/

Coincidentally, a lot of users past couple of days/weeks reported this issue. One thing is in common: all had 500-1000 categories in count.

Could be caused by ajax timeout error, or possibly sort plugin.

**Comment by dev-101** [comment]
teseo figured it out from the error logs of a member that the issue is caused by php configuration max_input_vars, and the way Osclass sends the data in array form. Serializing the stream as a single long string will fix this issue.

(credits goes to teseo - thanks!)

**Comment by Gm4acct** [comment]
Dear Team, 
Today I installed Osclass in my google cloud platform. Everything is running smooth, only problem is I'm not able to edit or delete categories from settings. It's showing -"Ajax error, try again."
Please support me to resolve this issue.
