### ISSUE TITLE
Submit button duplicated in modern theme

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1968]
I have looked over and over again and did not find the code that is used for submit button in modern theme. I have asked on forum and no reply as well (http://forums.osclass.org/3-5-x/ltbutton-type'submit'gt-in-modern-theme/).

So, here is the issue. In modern theme, the submit button appears in php code as

<div class="alert_form">
    <span>
    <form action="<?php echo osc_base_url(true); ?>" method="post" name="sub_alert" id="sub_alert">
        <fieldset>
        	<?php _e('Subscribe to this search', 'modern'); ?>
            <?php AlertForm::page_hidden(); ?>
            <?php AlertForm::alert_hidden(); ?>

            <?php if(osc_is_web_user_logged_in()) { ?>
                <?php AlertForm::user_id_hidden(); ?>
                <?php AlertForm::email_hidden(); ?>

            <?php } else { ?>
                <?php AlertForm::user_id_hidden(); ?>
                <?php AlertForm::email_text(); ?>

            <?php }; ?>
        </fieldset>
        
            <button type="submit" class="sub_button" ><?php _e('Subscribe now', 'modern'); ?>!</button>
    </form>
    </span>
</div>

but, in the website html code is converted into

<div class="alert_form">
<span>
<form id="sub_alert" name="sub_alert" method="post" action="http://modern.vindeurgent.ro/index.php">
<input type="hidden" value="CSRF1091776207_905551591" name="CSRFName">
<input type="hidden" value="1ed5a4089ae57cd7d4c4dcb5b1a0c9d838172ba87821a8f65591c5824562c28ec77604cdc2ac41648d6db8420eb9aa726739f2e1f90e4749ae77139677ec4093" name="CSRFToken">
<fieldset>
Subscribe to this search
<input id="page" type="hidden" value="search" name="page">
<input id="alert" type="hidden" value="gjGstHnFBRywsohQCLH1Sl+Czopv1PJCgNV1HzBp8+sCBTy3QTAxUvt0GUiDY284WFKRXRtFjjMYUfWLbDPr2pB/VS48Mt2RAMeGF8ZnmptdOeHFODuGoucFEf0/1hbf7+iO7AfhOEV2TzywNGoKUOTqyqrN2WUm1wcod90h4TNHx5GIV6Uo+3SUFGwXULrEHBX4Aj+h7R8uvaS1XG/sCSqvKYKWTtUMiMs/RJAFip5aAz2R5giq2ZzcFFjjrD+RhChRzxb2xXvVQTqoTIIPjg887aGS/pYT7wXnf9u4CrCL1W8oOtLHnLY6mimJiDn5x/RsA6MGv/ZEfk1fAl4elMOtI6JhS9CcYNTW7fCI/mvX4F7xo+DUtV7+fzNvY2Hai8fzv+st3y5tOV5zkQuvb2xY3/MRM5YDmZ1j3y8HKO6Yo3QZKYY5OGbG/UhYSyHrM9wGHoILJI4WsWNg2kYBJkSHI5n9wGdsNpGGWBLhLMYNVG5vv+mORb05dHifFVaefu3UMWZ3SgCxwwFP3rCOErdM+rinYhXhapEjKSqumcQT7x0sv5HGvN6nSPwYkBw6DVu0vPdOKRIRMWES1EluG8rIAKSTqc+5Lbwy1S0fr35mnym/HHKVMVydSSgcFj7XI5Xu4ISU9Ge0n3gKYUOzQa1NW2fTkO83SgfOysScIXYbP7M39HwXHbfjtldHmPa7DebdkJvBHF3+31Hza21xz/7TR3gmGj/byi+FZnqrZmk0oRGbvA/f88yMFjtrCJkv" name="alert">
<input id="alert_userId" type="hidden" value="0" name="alert_userId">
<input id="alert_email" type="text" value="Enter your e-mail" name="alert_email" style="color: rgb(128, 128, 128);">
</fieldset>
<div class="button" style="-moz-user-select: none;">
<span>
Subscribe now!
<button class="sub_button" type="submit">Subscribe now!</button>
</span>
</div>
</form>
</span>
</div>

So, exactly from where is the input button placed into a
<div class="button" style="-moz-user-select: none;"> ?

Because of this extra code, we have the actual button with the style 
div.button a, div.button button, div.button input {
    position: absolute;
    top: -9999px;
}
to make it invisible and a new container that acts like the button.

This implementation does not exist in beder theme so this must be done in the modern theme.
So can anyone tell me exactly from where? Thanks

**Comment by Adyyda** [comment]
the code that i have copied is lost during save

**Comment by dev-101** [comment]
Did you make some changes? Plugins? Most probably, you have a conflict with uniform library and something else in your setup. This is not present in clean versions.

check live:
http://myvpsdemo.tk/?theme=modern

then click on login page:
http://myvpsdemo.tk/user/login

**Comment by Adyyda** [comment]
Your website can't be accessed. 
Anyway, take a look at https://demo.osclass.org/general/index.php?page=search&sCategory=1&theme=modern

In left side we have subscribe now which has as structure 
<div class="button" style="-moz-user-select: none;">
<span>
Subscribe now!
<button class="sub_button" type="submit">Subscribe now!</button>
</span>
</div>

In style, line 521, change top: -9999px; to top:0 and you will see that the actual button will show. So even in demo you have a duplicated submit button and the real one is placed outside ov visible area with position absolute and top -9999px.

And if you check the alert php file you will never find a <div class="button" with inline style="-moz-user-select: none;">

**Comment by Adyyda** [comment]
I really hate this github. How can you post code? All my code is cut off...

**Comment by conejoninja** [comment]
The buttons and other form elements are rendered by uniform.js library, in the HTML will appear as duplicated but to the user will only be shown as one


For formatiing please read : https://guides.github.com/features/mastering-markdown/
you need to use three ` +  php (or the language you want to show)

```php
```php
// your code here
```
```

**Comment by dev-101** [comment]
Sorry, your ISP was blocked due spamming history, you should be able to access it now.

github markdown
https://help.github.com/articles/markdown-basics/

**Comment by Adyyda** [comment]
uniform.js library is used in bender theme? Because in bender buttons are not duplicated and 1 hidden. This may seem ok to you but if i try to add some code to such button like font awesome, the code gets duplicated. Not ok after me, and i guess you know it as well since bender does not use such way for creating buttons. Thanks anyway for the info, will take a look at uniform.js

**Comment by Adyyda** [comment]
In jquery.uniform.js does not exist "button" and olso no inline style -moz-user-select: none ?
