### ISSUE TITLE
Required fields in item post/edit

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1986]
Hello. Go to your demo, chose modern theme and Publish a listing. You will see marked with \* the email address, category, title and description fields which means that they are mandatory.
Do not fill or select anything. Click directly on Publish and you will see the error messages telling you to fill in the required fields.
The problem is that this is happening just for category and email fields?
We must have same errors for title and description because they are mandatory and you can't create a ad without them.
![screen shot 2015-12-13 at 19 43 31](https://cloud.githubusercontent.com/assets/5921012/11773914/a50cafa0-a238-11e5-9ab5-253d7ef4f463.png)

**Comment by krahamath** [comment]
i think That's not possible, because those ids and names will change by languages so can't able to make them required.

**Comment by garciademarina** [comment]
theme related, modern it's not the default theme anymore
