### ISSUE TITLE
MySQL 5.7 compatibility

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1987]
MySQL 5.7 is configured to use strict mode by default, along some other changes, which makes it incompatible with current Osclass. We need to make some changes to the core (plugins separately) to make it work, since stable releases were published in recent months, including latest 5.7.10 last week. These includes date default value, **data integrity** (truncation of data longer than specified will throw an error instead of silent cut-off), entering signed into unsigned field, and other nuances. On custom servers emulation of old behavior can be achieved, but we should not rely on it.

**Comment by garciademarina** [comment]
fixed #1987

**Comment by garciademarina** [comment]
fixed
