### ISSUE TITLE
oc admin not opening 

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#1991]
when i am trying to open classibook.com/oc-adm it was not showing anything just opening blank please help me to solve this issue, yhank u

**Comment by conejoninja** [comment]
Please, post your issues at the forums : http://forums.osclass.org/
Also, enable PHP : https://doc.osclass.org/Debug_PHP_errors

**Comment by abdulghanysyed** [comment]
hai, no one helped me in osclass forums can you please help me? please?

**Comment by conejoninja** [comment]
This is not the place for support, you could try asking in the forums : http://forums.osclass.org/ (I did not see any topic related to your issue) or you could try our paid support : https://osclass.org/premium_support_info/

**Comment by abdulghanysyed** [comment]
http://forums.osclass.org/general-help/oc-admin-not-opening-showing-blank-page/   this is the link i updated ticket

and i am starter in osclass it was not possible to go with premium support please help me bro
