### ISSUE TITLE
Help me to solve print ad issue

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#1992]
![print ad1](https://cloud.githubusercontent.com/assets/15182895/12236133/1beb3b02-b89e-11e5-9bbf-bf080ca1f761.PNG)
 
hai, http://classibook.com/apple-iphone-66-plus6s6s-plus-unlocked-version-3175 open this link clik on print ad as shown in image i am getting 500 server error, can u please find what is the issue? if issue with server , what is the requirements for this?  please dont reject this issue, i am facing from last 10days no one giving exact solutions.. please help me to solve this issue

**Comment by conejoninja** [comment]
please post this issue in the forums : forums.osclass.org

**Comment by abdulghanysyed** [comment]
sorry i already posted on forum but no one replaid to me http://forums.osclass.org/plugins-20/print-ad-plugin-not-working-getting-server-500-issue/
