### ISSUE TITLE
Upload multiple images one after another

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#1994]
Hello. When we select multiple images to upload (when posting an ad), they start to upload all in the same time. This is wrong because on low connexions the process may not finalise throwing errors like "XHR returned response code 0".
 So, how can we upload the images in sequence, one after the other?

**Comment by conejoninja** [comment]
I don't think this is an issue and here are some reasons:
* You are free to change the uploader to whatever you want to. We offer ajax uploader and inputfile/"classic" uploader in the core, but at the end, it depends on the theme you are using. You could create a new in the theme or via a plugin.
* Fineuploader, the uploader we use, has a maxConnections option, you could set it to 1, and they will upload one by one
* Users could upload images one by one manually, so if a subset of your users have slow connections, they could choose one file to upload, wait, choose another and so on, while giving your users with high speed connection the ability to upload all at once.
* Slow connections are, thankfully, less and less common nowadays

**Comment by Adyyda** [comment]
Fineuploader, the uploader we use, has a maxConnections option, you could set it to 1, and they will upload one by one  - **From where we can change this?**

Fast speed for multiple images has nothing to do with what you say. 
If you select 10 images and you have 5mb/sec speed, each one in sequence will load at 5mb/sec instead of 1 at 300kb, 2 at 500kb, 3 at 200kb, 4 at 1 mb and so on. If you would allow them to load in sequence, first will load with 5mb/sec, when it finish 2 will start with 5 mb/sec and so on, reducing the risk of getting errors like "XHR returned response code 0". Users will see a fast moving bar and so they will know the upload is working instead of 10 slow moving progress bars that are confusing.

Sure we can change it as we wish, but if you do not want to minimise the risk of getting errors during upload because of a simple thing that's another thing.

**Comment by conejoninja** [comment]
Here : https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/frm/Item.form.class.php#L1442

**Comment by Adyyda** [comment]
I assume that we have to change multiple: true into multiple: false? 
A option in admin area to activate or not such option would be best if you can do it in the future.
Slow connections will always exist, especially on mobile devices. Thanks

**Comment by conejoninja** [comment]
No, I told you the option is maxConnections, you could check the documentation of fineuploader here : http://docs.fineuploader.com/branch/master/api/options.html#maxConnections
You need to add it, as by default it's set to 3. multiple is for selecting multiple images at once, not uploading them.


As I already said, this is a theme option, as it's the theme the one which choose which uploader to use. There's probably a way to modify the limit without touching core files, but I didn't try it.

**Comment by Adyyda** [comment]
The theme is modern and bender. Not a custom theme (which anyway uses the uploader from modern or bender since many themes are variations of your themes).
Will look at the link you provided even if i do not wish to alter core files. Thanks

**Comment by dev-101** [comment]
I don't believe that uploading of images is the cause of the problem here, it is most probably the RAM limit of the server. I also get the XHR error (which translates to ordinary HTTP 500 with classic uploader) and memory is the main suspect here IMHO.

**Comment by Adyyda** [comment]
If that is the case, the message should be changed into something else like Upload failed, please refresh the page and try again...

**Comment by conejoninja** [comment]
Uploads are processed as different request, so images are processed one by one. Processing an image should take a fraction of a second. To trigger the RAM error, it should happen that several requests hit your server at the same fraction of a second.

**Comment by dev-101** [comment]
Well, that would require some FineUploader core mods, I assume. Because, with classic uploader you can do this on the server (example, how to treat 500 errors).

This is example from my fastcgi log, when XHR error is returned:

```
FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: read failed, referer: http://osclass.work/item/new
astCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/php5-fcgi", referer: http://osclass.work/item/new
```

Nothing in php error log, of course.

The only solution is to try better server with more RAM or to instruct your users to limit maximum image resolution they are trying to upload (yeah, suck but...).

Teseo mentioned a plugin that would deal with this problem, but it is not yet approved.

**Comment by Adyyda** [comment]
And olso, i never received that error on my pc with 10 mb connection. When i get it, i get it on my laptop with 1 mb wireless connection or on cable at work on 500kb speed (real download/upload speed). That is why is suspect that upload of big, multiple images on slow connections shows the error.

**Comment by dev-101** [comment]
There is no error, since (most probably) PHP probably runs out of memory and HTTP 500 response is returned only as some generic server error. You can only see the timeout response as I given one example above.

**Comment by dev-101** [comment]
To explain further my answer above, I can upload large images just fine, as long as their resolution is not large. XHR is triggered only if image size is large (4-5 Mpix for example), even if the file size is reduced down to 100 kB. This indicates that RAM is the problem, not the upload itself.

**Comment by Adyyda** [comment]
Ok. Will test again by adding big images from my pc with good connection and see if this confirms (at least in my case).

**Comment by Adyyda** [comment]
Forgot to ask
XHR returned response code 0 -  the message is generated by the server or by osclass (if so, from which file so i can change it)?

**Comment by dev-101** [comment]
XHR errors are interpreted by FineUploader (I did not got into FU at all), but the line is in the same file that just catches and displays it.

XHR 0 is, at least in my case, triggered by large PNG files.

**Comment by Adyyda** [comment]
I have made 2 tests - one with jpg of 15 MP and another with png of 10 MP downloaded from google images. Both were made from my pc on cable connection (10 mb download rate - real). Both have failed with a different error (no XHR error).
![untitled](https://cloud.githubusercontent.com/assets/5921012/12784276/cb2ab050-ca8e-11e5-84c6-a00d6ae879b8.jpg)
![untitled png](https://cloud.githubusercontent.com/assets/5921012/12784285/db0ee978-ca8e-11e5-99cf-01bc69fec041.jpg)

dev-101 , please attach here the png images that throw XHR errors on your domain so i can test in mine

**Comment by dev-101** [comment]
Hi, there are a lot of images that trigger this, so it is not a specific-image related.

You can test them here for comparison: http://osclass.work/item/new

**Comment by Adyyda** [comment]
I can't upload them because there is a 2.1 mb limit

**Comment by dev-101** [comment]
Sorry, I have restored the limit to a default value, but this is not the cause of XHR anyway. Check now.

**Comment by Adyyda** [comment]
When i add 4 jpg, first one start to upload quite fast (only 1) than it hangs and after 30 sec or more i see XHR returned response code 500 and no image loaded.
PNG olso behaves similar.

 So, your hosting is worse than mine and i am on a cheap one - https://www.romarg.ro/romania/hosting/gazduire-web.html  version of 3.45 €
This is just so i can work directly on a domain instead of my pc.
![untitled2](https://cloud.githubusercontent.com/assets/5921012/12790826/e861d234-caac-11e5-8399-c6b5a43aa59b.png)

**Comment by dev-101** [comment]
This is just a demo website running on a cheap VPS, do you honestly expect that I will waste resources on a demo? :)

But, it is always a good idea to test apps on low end, since you may be blind about potential issues this way.

Btw, I was working on the server in the past hour, so it is possible that we overloaded it with lot of image processing requests. Here is a pack of ~4 Mpix images (Windows Demo Pack), and interesting enough, they are not returning XHR. Possibly, because exif rotation task is not performed with those samples, so that saves a lot of RAM intensive tasks:

http://osclass.work/win8img.zip

I don't have this issues in production environment with more CPU & RAM, network interface etc.

**Comment by Adyyda** [comment]
Your images do upload just fine on slow wifi connection. But, a issue with big images exist, forum is full of XHR error, and, right now, digital cameras and smartphones make 10-15 MP images, not 2-4. Are we supposed to tell users that they can't upload native images from their devices because our websites do not handle them well? It's absurd. From now on, images will get bigger and bigger as px and mb, not smaller.

**Comment by dev-101** [comment]
True, and there are several approaches to this. Some use in-browser scripts to resize images before uploading, but this may not work at all on mobile, which gets more popular. So, better server specs must follow along.

**Comment by dev-101** [comment]
> Some use in-browser scripts to resize images before uploading

I am just testing teseo's plugin (not approved yet), and I can confirm that it has fixed all the big-images resize issues. Still remains to test it on mobile devices, though.

**Comment by Adyyda** [comment]
What plugin?

**Comment by dev-101** [comment]
"preResize images"

**Comment by Adyyda** [comment]
Let me know when you have tested on mobile. I can't see anything with that name on forum. Thanks

**Comment by dev-101** [comment]
It is not released yet, send PM to teseo.

**Comment by dev-101** [comment]
After talking with teseo, he explained what plugin actually does, since I was curious about the fact it is also based on Fine Uploader:

- it replaces old FU 3.8.0 currently used in core
- it adds Scalling feature (documented in FU API here http://docs.fineuploader.com/branch/master/features/scaling.html)

After this, I asked him about an idea if this could be implemented directly inside the core, as well. Now, personally, I would like to see this become part of the core feature, but plugin, being independent, offers option to upgrade it more frequently w/o touching the core. Still, this would give huge boost to low-memory budget servers, performance and user experience.

This issue could be re-opened until that is discussed and decision is made.

**Comment by Adyyda** [comment]
I agree. If this works fine with mobile devices, it should be added to the core because the benefits are huge. Is better anyway than what we have right now, so no issue with slower upgrades. Thanks for the info.
If Teseo agrees and let you integrate it i the core, after me you should make a thread with a demo on the forum so all users can test it with various devices and make a pool to see if works fine. If is confirmed that is ok, add it to the core.

**Comment by Adyyda** [comment]
Not so good after all. Many users use Android stock browser which make this resize before upload obsolete.

Supported Browsers

This feature is supported on all browsers other than IE9 and older, Android 2.4 or older, and Safari 5.1 or older. Note that Android's stock browser is also not supported, due to multiple long-standing bugs in that browser with Blobs and data URIs. Chrome on Android is supported, though.

**Comment by dev-101** [comment]
That is true, however, even with above it seems that I don't see XHR anymore, as if just updating FU resolved the issue. I have only tested with 1-2 images which never worked before, but have not reverted back to make conclusions. Will perform in-depth tests in upcoming time.

**Comment by Adyyda** [comment]
I see that Teseo plugin is out but i see olso that the licence for fine uploader has changed into a commercial one which requires 99$/year? Can you upgrade osclass to the latest version of fine uploader which is still free for commercial projects? Osclass uses 3.8 and since revision 5 which changed the licence there are many others revisions. https://github.com/FineUploader/fine-uploader/releases?after=5.0.2

**Comment by dev-101** [comment]
This is a very tricky area, *if* your entire site is used for non-commercial project, then yes, you can embed it and continue using it. But, let's not fool ourselves here, in most cases it will be not (through various models). So, indirectly, you may put users into fallacy that your app is really free. Same happened to some other key libraries as well, and this is probably the reason why they are kept old, buggy, and not being updated.

**Comment by Adyyda** [comment]
Ok, but what is the difference right now if osclass uses already 3.8 (free) ad you replace it with 5.0.9(free as well according to their licence)? We already use it so why not bump the revision which has issues fixed and possibly have extra features? After 5.0.9. the licence is changed into commercial one as it can be see in Licence file - that is the moment the project was purchased by Widen company.

**Comment by dev-101** [comment]
Yes, that could work, but you need to build manually 5.0.9 into jquery version, since the library comes in pure javascript. Or find somewhere pre-compiled one.

**Comment by Adyyda** [comment]
something like here https://github.com/xzyfer/fine-uploader/tree/master/dist/jquery.fineuploader  but with revision 5.0.9 ?

**Comment by dev-101** [comment]
Yes

**Comment by Adyyda** [comment]
Will try to find one. To build one, from what i have see here -http://stackoverflow.com/questions/18802557/fine-uploader-example-traditional-build it is beyond my skills

**Comment by dev-101** [comment]
If you know git, no need to look elsewhere. Simply revert to 5.0.9.

**Comment by Adyyda** [comment]
I would do it if i know how...

**Comment by dev-101** [comment]
1. clone the repo in your git client
2. hard reset to 5.0.9

done

**Comment by Adyyda** [comment]
When you know how to do it, it is easy. Will try to follow the steps from stackoverflow and see if i manage.

**Comment by Adyyda** [comment]
Download fineuploader-dist_5.0.9.zip from https://www.versioneye.com/javascript/feryardiant:fineuploader-dist/5.0.9 and see inside folder "dist". Let me know if is ok.

**Comment by dev-101** [comment]
Hi, I have talked to teseo, he says that above libs are different, probably modified and built for a different script. In any case, I have sent him the version derived from earlier link above, tested it and it is working fine. So, probably he will release the downgraded version if his tests pass.

**Comment by Adyyda** [comment]
Ok. If his modified (downgraded) version works, any plan to implement it to the core (if he allows it - i don't think he would mind since he doesn't ask for money)? It would be a great feature as performance.

**Comment by dev-101** [comment]
It is doable, as already said, but this is really up to teseo to decide. I will not go over him.

**Comment by Adyyda** [comment]
Yes but since you are willing to add it to the core there is a good chance. Will see what he will say.

**Comment by Adyyda** [comment]
Hello dev-101

I have asked Teseo and he agrees that you integrate his work into the core. Can you talk to the rest of the team and let us know if you will integrate it? Thanks

> Hi,

The issue is closed now, so I've sent this message to dev101:

Sorry I didn't answer there before the issue was closed. Anyway, of course if and when the Osclass team wanted to use any part of my code as basis to add this feature to the core, I wouldn't have any problem at all, the plugin would still be useful for earlier versions.

**Comment by dev-101** [comment]
Hi Adyyda,
thanks.

Yes, I know, teseo sent me a message and I hope he is reading this reply here :)

I will try to implement it, as soon as I get some time, but cannot promise the exact date. Also, would be much easier if teseo help me with specific details, since there were some other improvements, as well. This is really important, because if affects performance. For now, we have a plugin and it works great.

**Comment by Adyyda** [comment]
Hello dev-101. I have 2 questions - not related to this issue:
1. are osclass developers aware of this bug regarding regions/city https://github.com/osclass/Osclass/issues/2008
2. why the demos of osclass do not have permalinks activated because everyone use them by default? 
Thanks

**Comment by dev-101** [comment]
1. I use Full Breadcrumbs plugin, which is much more advanced and does not have that problem :)

2. Not sure, but from a technical point of view, permalinks are added complication, they look nice to users, but standard links are more easier to handle and work on different servers/setups. Since those are just demos, I guess team does not care much about it.

**Comment by Adyyda** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5921012/13596299/54d613bc-e51a-11e5-9f9c-5344b2dc4e9d.jpg)

Have made a test by creating 2 listings, one in Aldesti (Arad region) and another Aldesti (Valcea region). From sidebar, i start to type Aldesti and i select Aldesti (Valcea) and in breadcrumbs i get Arad > Aldesti and in search result i get booth ads, from Arad and Valcea? 

This whole region and search is a big problem. Not to mention when you post a listing where you see region as styled dropdown, below you have a text input field for City that changes into a non styled select once you made a selection inn Region. 
![untitled1](https://cloud.githubusercontent.com/assets/5921012/13596488/6b67d7f4-e51b-11e5-9808-caea7637588f.jpg)

That is not a improvement, it is a mess. We should see city from beginning as dropdown and styled the same way as the region. 
And in addition, if we chose dropdown for region/city in admin area, that has to apply in all areas of website, including sidebar search. 3 years and so many threads regarding region>city dropdown in sidebar and nothing was done to address this.

**Comment by Adyyda** [comment]
Hello dev-101
Beside what i have mentioned in previous message here is another bug regarding poor implementation of location area.
Go to osclass demo, chose bender theme, make a listing, chose any region/city you wish and post it. All looks fine. Now, go to your account and chose edit listing. Go to city to chose another one from the region you already chosen when posted the item and **you will see all the cities from all regions**! To get the proper cities you have to chose another region than cities but olso, when you click on another region and change it, you will still see the name of previous selected city even if that doesn't exist in the new dropdown - see image bellow where Bucuresti has only 6 options (Sector 1,2,3,4,5,6) and i see Aldesti as option (that is from previous selection)
![screen shot 2016-03-08 at 19 13 44](https://cloud.githubusercontent.com/assets/5921012/13609636/7d60efc6-e562-11e5-8ec6-ea30101d9c93.png)
