### ISSUE TITLE
MySQL server custom port support

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2004]
original forum topic here:

http://forums.osclass.org/installation-update-help/prob-host-install-osclass-and-define-port/
- add port option during installation
- add port value @ config.php

update: while at this, possibly default/custom socket could be added as well (for completeness).

**Comment by cybernet** [comment]
+1

**Comment by garciademarina** [comment]
https://dev.osclass.org/2012/10/22/mysql-alternate-port-number/

**Comment by dev-101** [comment]
Hi Carlos,

Thanks, this is great, but does it cover scenario _during_ installation? Because, config.php does not exist yet at that stage...
