### ISSUE TITLE
Logo upload from admin area

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#2005]
Hello. When you want to upload a logo via admin area, png logo is not saved properly. 
Try yourself to upload in bender theme for instance logo-beta.png attached here and look what we get. This is happening in several versions of osclass/bender , including latest versions.
![logo-beta](https://cloud.githubusercontent.com/assets/5921012/13004489/6f41b23c-d184-11e5-9997-e51bad6a81c8.png)
![logo-upload](https://cloud.githubusercontent.com/assets/5921012/13004488/6f412164-d184-11e5-840a-7673007b5dc0.png)

The only way to get it working is to upload via admin and than fia cpanel or filezilla replace whats been uploaded by osclass. Olso, what's with // in the link?

**Comment by garciademarina** [comment]
May be a problem with your environment. Check png image support or try imagemagick extension.
