### ISSUE TITLE
Two Osclass one DB and RTL and LTR Languages

### ISSUE THREAD

**Issue by nafatrue** [osclass/Osclass#2006]
hi i manages to install tow osclass in two different places and i managed to ceonnect theme to the same DB but i use two languages arabic RTL and french LTR,when i enable RTL i still have french osclass RTL too 
sorry for my english i hope i did explain my issue

**Comment by nafatrue** [comment]
two months and no answer

**Comment by garciademarina** [comment]
this is not a core related issue. 

please ask on forums.osclass.org
