### ISSUE TITLE
uploads/temp/qqfile_ not removed

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2007]
I have a lot of temporary qqfile images in this directory several weeks and months old. Cron is running perfectly, files perms in order. However, it seems that Osclass does not have any internal cleaning mechanism of it's content (failed image uploads/processing/XHR errors etc.).

Files older than e.g. 60 seconds or so should be removed in regular intervals.

**Comment by markuspmeyer** [comment]
confirm, need manual cleaning at the moment or system cron

-rw-r--r--  1 www-data www-data  161629 Apr  7 22:41 auto_qqfile_5706c5ee2c09a.JPG
-rw-r--r--  1 www-data www-data  106708 Apr  7 22:41 auto_qqfile_5706c5ee3f92d.JPG
-rw-r--r--  1 www-data www-data  108270 Apr  7 22:41 auto_qqfile_5706c5ee580c3.JPG
-rw-r--r--  1 www-data www-data   20735 Apr  8 10:00 auto_qqfile_57076505109ab.jpg
-rw-r--r--  1 www-data www-data   14118 Apr  8 10:00 auto_qqfile_570765238c990.jpg
-rw-r--r--  1 www-data www-data   57605 Apr  8 10:23 auto_qqfile_57076a674adb9.jpg
-rw-r--r--  1 www-data www-data 2313733 Apr  9 00:30 auto_qqfile_57083121807a1.jpg
-rw-r--r--  1 www-data www-data 3133246 Apr  9 00:36 auto_qqfile_5708327e937b2.JPG
-rw-r--r--  1 www-data www-data 2517241 Apr  9 05:32 auto_qqfile_570877df1cd42.jpg
-rw-r--r--  1 www-data www-data   44076 Apr  9 05:33 auto_qqfile_570877f731a06.jpg
-rw-r--r--  1 www-data www-data    9604 Apr  9 06:32 auto_qqfile_570885f092912.jpg

**Comment by garciademarina** [comment]
temporary image should be removed by cron hooks. 

if you don't trigger osclass cron manually you need to have running autocron osclass option.

**Comment by garciademarina** [comment]
we will try to check it anyway.

**Comment by dev-101** [comment]
Could be related to FineUploader, is it should manage removal of qq files.

This library is now 100% free (MIT licence), so it is a perfect time to update it in the core.

**Comment by conejoninja** [comment]
Osclass remove qq_* files, I'm under the impression that auto_qq_* are failed uploads (or other temp files), and we should remove those too in cron.php

**Comment by garciademarina** [comment]
https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/cron.php#L56

**Comment by dev-101** [comment]
Thanks Daniel & Carlos for pointing the right line, could be that back when I opened this issue something wasn't quite right and now I cannot reproduce it. Just checked all temp folders on all setups and they are empty. But, I have implemented teseo's plugin which uses newer FineUploader library since then and reduces XHR errors (failed uploads) to virtually 0 on low-memory systems, so this is one of the reasons why I don't have this problem any more. But yes, auto_qqfile should be also removed, so let's keep this issue open until then.

Thanks!

**Comment by dev-101** [comment]
**auto_qqfile_** files are actually created along **qqfiles** automatically by FineUploader, those are thumbnails used in preview window.

But, if item publishing fails for any reason or user changes their mind or dev just tests something in the edit/post page and does not wish to really publish anything, then they are left untouched.

I am just cautious not to remove any of them by cron before certain age threshold, to be sure they aren't in use (say, 1 hour or 3600 seconds should be enough).
