### ISSUE TITLE
Plugin development; Run hook function just one time in publishing an ads.

### ISSUE THREAD

**Issue by RHamidR** [osclass/Osclass#2009]
I have seen the hooks list to find a hook for running my function in initializing the ads publish form, and just for one time.
I found "item_form" hook that runs after changing the category and every time that has been changed.
So could someone help me to do that.

I'm new in developing plugins for osclass and All advises are appreciated.

Thanks in advance.

**Comment by RHamidR** [comment]
I guess this issue is Osclass's issue. I'm surprised nobody didn't have this issue until now!!!!
New_Item hook didn't show anything.
Could somebody show me a way. I don't want to change the core codes.

Thanks in advance

**Comment by conejoninja** [comment]
It depends on what you are trying to do, so tell us what you want to achieve and we'll be able to help you
