### ISSUE TITLE
Avoid timeout on item post or edit due to image processing

### ISSUE THREAD

**Issue by groomain** [osclass/Osclass#2011]
Hi,

Due to image resizing that take a lot of resource some of our users get a timeout on item post or item edit. After the timeout we have in the database an item who is partially inserted without all informations who are coming from plugins.  So the user needs to publish again the item without any image.

Ajax upload reduce the time that a user need to wait after submit the form and that's super cool but it doesn't avoid timeout due to image processing.

I think the best option would be to resize images directly in the AJAX process. Therefore when a user submit an item all the images will be already resized and the process will just be to move all images to the right folder with the right name.

In itemActions.php if the variable $ajax_photos isn't empty 
- Run the part of the function uploadItemResources without the imageResize part

In the controller ajax.php case ajax_upload
- Run the part of the previous uploadItemResources function who resize the picture 

Regards,

**Comment by dev-101** [comment]
Hi groomain, check teseo's plugin which already does what you suggest. It essentially uses scaling feature of FineUploader, but keep an eye on the license change past 5.1.x (no longer free for commercial use).

**Comment by conejoninja** [comment]
Are you sure it's the image processing the one generating the timeout? It shouldn't take more than a few seconds in the worst case to process the images

**Comment by dev-101** [comment]
Hi Conejo,

Image processing is the slowest part in item posting process. You can check this with WebMedia's benchmark plugin (dummy item or lorem items, as later renamed). Inserting 100s of items without images takes far less than the same number of random generated items with images.

**Comment by groomain** [comment]
Yes on our production site with 10 images of 2mb we have a timeout with GD library.

And on my macbook air I also have a timeout with one image of 2mb.

@dev-101 with fineuploader I will also have a timeout considering that the resizing will still be processed.

**Comment by dev-101** [comment]
Hmm, well, have you tried it or not? It sure did resolve all my timeout issues, also, if you reduce image to ~ 1 Mpix, it will be much easier to process. Or adjust it to target size to remove resize stage at the reduced quality due to the basic resizing algorithm.

**Comment by conejoninja** [comment]
Also, use Imagemagick, GD takes huge amounts of RAM

**Comment by groomain** [comment]
Ok i'll try

**Comment by dev-101** [comment]
Well, I have done a lot of benchmarks, it is not actually true that GD is that much worse. It all depends on processing, for example, you can put your server to knees with too much effects and stuff in imagick. And GD actually worked better on my low-end server most of the time.

**Comment by groomain** [comment]
I will try to put my modifications of GD resizing and autoRotate to imagemagick.

Our resizing works with all size of images to always fit the dimensions. Without white  around the image.

**Comment by dev-101** [comment]
Carlos implemented new auto rotation based on exif in latest version, which version do you use? It works excellent.

**Comment by groomain** [comment]
Our works since a long time. Maybe it's the same ;)

**Comment by dev-101** [comment]
This stuff is new, it was introduced in 3.6.0.

**Comment by groomain** [comment]
Yes but it was in development since longtime. I activate it earlier.

It work great !

@conejoninja maybe you can close this ticket I will try to use imagemagick

**Comment by dev-101** [comment]
groomain, I really do not know which code do you use and there is no code that was "in development since the long time" that I am aware of regarding this issue. Can you point me to the commit that you are talking about?

Also, you have a close issue button below this discussion, so you can also close it, as you are the author.
