### ISSUE TITLE
increase VARCHAR(40) for s_section & s_name @ t_preference

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2018]
I hit the problem with 40 characters limit :)

> example fix: 40 -> 128

note about limits: 256 will return `#1071 - Specified key was too long; max key length is 767 bytes` with utf8_general_ci collation, because 3 bytes/char \* 256 > 767 bytes limit, while 255 should be fine since 3 \* 255 < 767, but it is still not `mb4 friendly`, so we should be careful. 128 is OK.

**Comment by conejoninja** [comment]
Not sure why we need to increase the value of those fields, but doing causes no harm, so increased to VARCHAR(128) I would suggest to keep it as small as possible,and avoid mb chars.
