### ISSUE TITLE
Optional osclass route parameters?

### ISSUE THREAD

**Issue by andrewpros** [osclass/Osclass#2023]
Hi.

Is there a way to make optional routes in osclass?

I have many parameters, but many of them are used only in couple of places.

When i just don't specify those parameters in osc_route_url parameter array, they are rendered in link as {names} specified in osc_add_route url parameter.

Any advise?

**Comment by conejoninja** [comment]
For the moment is not possible, you could remove those parameters from the route, and if you pass them to the osc_route_url, they will be added to the url after the ?
For example your_route?param=value1&param2=value2

Other solution would be to create several routes with different parameters, but this is probably not optimal.

**Comment by andrewpros** [comment]
Then why it is closed and not set as a BUG or Enhancement?

Most php scripts that have routes needs, thus supports optional parameters, so the osc route functions are incomplete somewhat for now.

But i have no time so i will make the first option as suggested, thanks, but really consider adding optional parameters to osc functions.

**Comment by conejoninja** [comment]
Sorry I hit the wrong button

**Comment by andrewpros** [comment]
I can confirm that first solution works ok.
