### ISSUE TITLE
[IMPORTANT] Register plugin path serious issue

### ISSUE THREAD

**Issue by andrewpros** [osclass/Osclass#2024]
Hi.

On some systems/hostings, there are serious issue with registering plugins.

You will even not know where is a problem as the admin panel will inform you that it has installed right, but it doesn't.

The register install function won't be called.

I have pinpoint it after hours of testing to a ABS_PATH problem.

Found it in register func https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/classes/Plugins.php#L201

before replace path /oc-content/plugins/plugin_name/index.php
osc_plugins_path() returns => //oc-content/plugins/
after replace /oc-content/plugins/plugin_name/index.php

But it should be only plugin_name/index.php, the problems is that of course osc_plugins_path() returns double slashes, it should be single and then the replace will work.

At the end, the problem lies in ABS_PATH define, not sure why and which.

As a workaround you can add / before the path

osc_register_plugin('/' . osc_plugin_path(**FILE**), "func_install");

But after checking how the osc_register_plugin function works, you could just manually pass the  plugin_name/index.php name, which rise another question why even bother with the osc_plugins_path() in the internal register process.

It could be simplified.

Hope it will be fixed.

**Comment by conejoninja** [comment]
Thanks for reporting this issue, could you tell us something more about this system/configuration/environment? so we'll be able to reproduce it?

Regards

**Comment by andrewpros** [comment]
Sadly no, it is my client shared hosting, but it is a standard php 5.6.17 install, i can provide some phpinfo data, but what you want to know? The server is IdeaWebServer/v0.80.1 (like Apache)

It works without the workaround on my local system, so clearly it has something to do will hosting configuration, so thats it.

Lucky it looks like register function could work without any path replacing, checking etc. but if ABS_PATH has influence on everything then thats not good.

**Comment by conejoninja** [comment]
Tehere are some known issues with symlinks and plugin paths but we'll need some more information to fix this issue, not sure if it's the same or not

**Comment by andrewpros** [comment]
@conejoninja 

Well you didn't ask for months for additional info, i don't know what to provide, but the PROBLEM IS REAL and is still THERE, i need to change every plugin register path to "plugin_folder_name/index.php" , otherwise it won't work. And the same for configuration link, won't work if i use the path.

Funny thing is it is not even used as a path, it is just used as unique identifier, the addHook is overcomplicated with all the slashes/path code.

You can fix it every simple by making an unique hash based on path, that's it., no more thinking about slashes, paths etc.

**Comment by andrewpros** [comment]
@conejoninja Again no input on this?

**Comment by conejoninja** [comment]
I didn't have the time to review or fix this issue. 
I think that the problem is because in certain situations, with symbolic links involved, one plugin "have" two different paths, which result in some errors. We just need time and to be able to reproduce the issue

**Comment by andrewpros** [comment]
@conejoninja Well i will try to provide some meaningful data, but as i noticed above, you don't need the PATH, it is not used as path so it can be hashed and then remove all the code dealing with PATHS, slashes etc. in addHook function.

You can fix it in blanco.
