### ISSUE TITLE
Getting Error when clicking any Category Link in OS Class

### ISSUE THREAD

**Issue by AshBhai** [osclass/Osclass#2026]
Hi,

I've installed OS Class and after upgrading this to latest version, whenever I click on any category link, it gives error "The overallservices.in page isn’t working" with "ERR_TOO_MANY_REDIRECTS".

Below the link which gives error and not giving any result.

http://overallservices.in/index.php?page=search&sCategory=4

Can anyone resolve this issue???

**Comment by garciademarina** [comment]
for this kind of questions use forums.osclass.org
