### ISSUE TITLE
items won't be posted

### ISSUE THREAD

**Issue by nafatrue** [osclass/Osclass#2028]
users post there ads on my website but it wont appear in ads listing,i googled the issue but no success,i'm osclass beginner would you plz help me solve this problem

**Comment by conejoninja** [comment]
Please ask in the forums : http://forums.osclass.org/

**Comment by nafatrue** [comment]
i didnt even receive the activation mail from there forum for the two times i tried to register

**Comment by conejoninja** [comment]
Then write to info@osclass.org from the email used to register in the forums, also, look on your trash/spam folders
