### ISSUE TITLE
ERROR: Some dependencies could not be loaded (modernizr)

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#2042]
please help me that i am getting some issue in my customized cars attribute plugin in admin pannel --- ERROR: Some dependencies could not be loaded (modernizr)

please find the image below

i hope someone help me here..
thank u
![screenshot_1](https://cloud.githubusercontent.com/assets/15182895/16662637/0397cd7a-4496-11e6-98b5-586e1df40dea.png)

**Comment by conejoninja** [comment]
Post your issue int he forums : http://forums.osclass.org/ this is not the correct place

**Comment by abdulghanysyed** [comment]
http://forums.osclass.org/plugins-20/error-some-dependencies-could-not-be-loaded-(modernizr)/
