### ISSUE TITLE
Insecure Admin Panel

### ISSUE THREAD

**Issue by BabyDunk** [osclass/Osclass#2044]
hello
i have an insecure admin panel on the dashboard and the market place,the problem is consistant in every browser, 

teseo suggested that the core files needed changed

here is the items that are breaking my ssl connection

this is from the dashboard
`http://static.osclass.org/market/dashboard/img/banner-11.gif`

this is from the market 
`Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/5/1529_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/5/1529_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/5/1703_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/5/1703_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/2/555_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/2/555_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/1/482_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/1/482_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/4/1288_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/4/1288_thumbnail.png" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/532.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/532.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/203.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/203.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/604.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/604.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/569.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/569.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/577.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/577.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/504.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/504.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/480.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/480.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/6/1820_thumbnail.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/6/1820_thumbnail.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/uploads/market/427.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/uploads/market/427.jpg" on a secure page

...dding:0;margin:0;border:0;display:none",l=f[0].offsetHeight===0,f[0].style.displ...

jquery.min.js (line 2, col 21671)
Loading mixed (insecure) display content "http://market.osclass.org/oc-content/plugins/market/img/market_header_payments_pro.gif" on a secure page

....cleanData(c.getElementsByTagName("*")),c.innerHTML=a);c=0}catch(f){}}c&&this.em...

jquery.min.js (line 2, col 67119)
Loading mixed (insecure) display content "https://market.osclass.org/oc-content/plugins/market/img/market_header_payments_pro.gif" on a secure page

....cleanData(c.getElementsByTagName("*")),c.innerHTML=a);c=0}catch(f){}}c&&this.em...`

**Comment by conejoninja** [comment]
Please access your database, on table oc_t_preference, look for the row with 
s_section = 'osclass' and s_name = 'marketURL'

It should be: http://market.osclass.org/api/v2/

Change it to

https://market.osclass.org/api/v2/

Notice the extra "s", tell us if that worked

**Comment by BabyDunk** [comment]
Hello Daniel and Tank you

 

That fixed the insecure items for the market

 

Their is another insecure item is on dashboard but I can’t find the link “http://static.osclass.org/market/dashboard/img/banner-11.gif”

 

Thanks for you help

Chris

**Comment by mnmlguy** [comment]
I have the same exact issue. I've changed the marketURL in the database to https but I'm still getting market images over http.

**Comment by MichaelSM1305** [comment]
I have the same problem. I use a translator. Where to find it.
but requested an insecure image 'http://static.osclass.org/market/dashboard/img/banner-14.gif'.
My site https
