### ISSUE TITLE
Permalink fail on osclass 

### ISSUE THREAD

**Issue by nimahpoor** [osclass/Osclass#2047]
hello
I have Osclass 3.6.1  on my host after enabling permalink on (( RUSSIAN )) 
items :  HTTP ERROR 500
category and sub category : HTTP ERROR 500
home page is not streaming baners
user/...       and other page   with english address is working 

.htaccess    is    

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

dozakaz.com

**Comment by garciademarina** [comment]
I see that your issue has been fixed, is it correct? 

Can you tell us what did you do?

**Comment by nimahpoor** [comment]
Hi
I changed my host  from qhoster.com   to  one.com  and its working now .But with  limit of characters.For example in categories name you have limit 104 characters.
many of hosters dont support it.
This is not a good CMS and is weak in SEO.
