### ISSUE TITLE
Users items Count bug

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#2056]
First mark an Ad as SPAM and then Delete it.

The # count of user ads is not changed.

**Comment by dev-101** [comment]
This is caused by plugins, as discussed many times before.

Plugin to fix this problem on live sites already exists @ Market:
https://market.osclass.org/plugins/counters/user-items-counter_463

**Comment by eurobank** [comment]
Yes, i was quick to open an issue and the problem was with some custom mod.
