### ISSUE TITLE
Next Page (Pagination) in subcategory - Error 404 

### ISSUE THREAD

**Issue by ralfpalmeiras** [osclass/Osclass#2058]
I created new categories, but the paging is generating 404 in subcategories

**Example:**

http://site.com/category/subcategory/2

Page 2 - Error 404 only with urls friendly

Listing URL: {CATEGORIES}/{ITEM_ID}/{ITEM_TITLE}
Page URL: {PAGE_SLUG}
Category URL: {CATEGORIES}

Listing URL: (Error)
{CATEGORIES}/{ITEM_TITLE}/{ITEM_ID}

Listing URL: (Working)
{CATEGORIES}/{ITEM_TITLE}-{ITEM_ID}

How to use "/{ITEM_ID}" instead of "-{ITEM_ID}"

**Comment by garciademarina** [comment]
https://demo.osclass.org/general/real-estate/2

it's working fine on our demo site. 

If you have question please use the proper channel forums.osclass.org

**Comment by Haisam-Abdo** [comment]
Why does the error occur with other languages? Example: ar fr de
