### ISSUE TITLE
Comment to ad is sent by E-Mail to user (poster of ad) before comment is approved by admin

### ISSUE THREAD

**Issue by markuspmeyer** [osclass/Osclass#2060]
Although comments moderation is activated a user (poster of ad) will anyway get an E-Mail Notification with comment (possible spam) to his ad.
Moderation does prevent a comment from appearing on webpage, but does not prevent spamming users by E-Mail - and though might lower reputation or even risking of being blocked by sendgrid, mailjet or other mail providers when user report E-Mail as spam.

osclass: 3.6.1
Browser: All
php:  5.5.9

![comments](https://cloud.githubusercontent.com/assets/18530570/19015720/0a1a9ad0-880a-11e6-8c2c-d7079c20a6c7.png)

**Comment by garciademarina** [comment]
We can send the user_notification_email only when comments are not being moderated. 

But then users will not receive any email. 

Enabling and Unblocking comments can check if user need to be notified, but can be notified more than once.

**Comment by garciademarina** [comment]
Notification emails will not be sent if comment moderation is enabled
