### ISSUE TITLE
Multiple fatal errors after migrating live site to localhost 

### ISSUE THREAD

**Issue by mlbxl** [osclass/Osclass#2062]
I have migrated a live osclass site before to localhost (WAMP) and everything went good.

But this time, after the migration to local, the site loads normal but some functions/links don't work any more.

These are the problems/fatal errors:
- Categories don't show anymore (parent and child categories)
- I can't log into admin area, I get this fatal error when I try to login:
  Fatal error: Call to a member function result() on boolean in C:\wamp64\www\test\oc-includes\osclass\classes\Stats.php on line 66
- When logged in as an user, I can't go to 'My Account', I get this fatal error:
  Fatal error: Call to a member function row() on boolean in C:\wamp64\www\test\oc-includes\osclass\model\Item.php on line 1238

![fatal error bij het inloggen als admin](https://cloud.githubusercontent.com/assets/17385394/19077081/76892efa-8a4b-11e6-8c3b-8d2aab397d67.PNG)
![fatal error bij my account](https://cloud.githubusercontent.com/assets/17385394/19077082/768a7986-8a4b-11e6-8b5f-85172482754a.PNG)

**Comment by mlbxl** [comment]
The weird thing is that everything worked before, with the same database and same site files.

**Comment by markuspmeyer** [comment]
You probably have the latest mysql version 5.7 installed on localhost. Osclass does not work out of the box with 5.7.
Try:
mysql> set global sql_mode = '';

**Comment by mlbxl** [comment]
Thank you for your reply.

Where do I paste that command?

**Comment by adrienrn** [comment]
#1987

**Comment by mlbxl** [comment]
Thanks for helping me out, I didn't have a clue why this was happening.

mysql> set global sql_mode = '';
This command fixed the problem.

**Comment by mlbxl** [comment]
I just discovered that the command fixes the problem but only in that session.
When I restart WAMP server, the old problem gets back.

Is there no lasting solution for this problem?

**Comment by dev-101** [comment]
You need to store it in my.ini / my.cnf configuration.

Locate the same line **sql-mode** in above file and replace it with **sql-mode=''**, then restart sql server.

**Comment by mlbxl** [comment]
You're right, now it's permanently fixed. What does sql_mode='' do?
