### ISSUE TITLE
How to hide field basad on a category and subcategory

### ISSUE THREAD

**Issue by rotchel-webster** [osclass/Osclass#2065]
Hi, i try to hide this radio boxes! 

```
  <div id="property-type" class="large-12">
    <label>
      <span class="required_fields">* </span>
      <?php _e('Property Type', 'ctg_housing'); ?>
    </label>
  </div>
    <?php
        $itemtype1 = '';$itemtype2 = '';$itemtype3 = '';$itemtype4 = '';
      if(!empty($s_furnished)){
      if($s_furnished=='bare-unit'){
        $itemtype1 = 'checked = "checked"';
        }
      else if($s_furnished=='unfurnished'){
        $itemtype2 = 'checked = "checked"';
        }
      else if($s_furnished=='semi-furnished'){
        $itemtype3 = 'checked = "checked"';
        }
      else if($s_furnished=='fully-furnished'){
        $itemtype4 = 'checked = "checked"';
        }
      }
    ?>
  <div id="property-type-select" class="large-12">
    <div class="item-post-property-type-0">  
      <input type="radio" name="s_furnished" id="s_furnished" value="bare-unit" <?php echo $itemtype1;?>>
      <label for="s_furnished">Bare Unit</label>
    </div>
    <div class="item-post-property-type-0"> 
      <input type="radio" name="s_furnished" id="s_furnished" value="unfurnished"  <?php echo $itemtype2;?>>
      <label for="s_furnished">Unfurnished</label>
    </div>
    <div class="item-post-property-type-1"> 
      <input type="radio" name="s_furnished" id="s_furnished" value="semi-furnished"  <?php echo $itemtype3;?>>
      <label for="s_furnished">Semi-Furnished</label>
    </div>
    <div class="item-post-property-type-1"> 
      <input type="radio" name="s_furnished" id="s_furnished" value="fully-furnished"  <?php echo $itemtype4;?>>
      <label for="s_furnished">Fully Furnished</label>
    </div>
  </div>
```

Whit a show when selected one of this subcategories!

<select id="select_1" name="select_1" depth="1" class="valid">
  <option value="0">Select category</option>
  <option value="1">For Rent</option>
    <select id="select_2" name="select_2" depth="2" class="valid">
      <option value="1">Select subcategory</option>
      <option value="43">Boarding House</option>
      <option value="42">Studio</option>
      <option value="41">Apartment</option>
      <option value="2">Condominium</option>
      <option value="40">Penthouse</option>
      <option value="39">Townhouse</option>
      <option value="38">House and Lot</option>
      <option value="37">Villa</option>
    </select>
  <option value="34">For Sale</option>
    <select id="select_2" name="select_2" depth="2" class="valid">
      <option value="34">Select subcategory</option>
      <option value="33">Studio</option>
      <option value="32">Apartment</option>
      <option value="31">Condominium</option>
      <option value="30">Penthouse</option>
      <option value="29">Townhouse</option>
      <option value="28">House and Lot</option>
      <option value="27">Villa</option>
    </select>
  <option value="26">Pre-Selling</option>
    <select id="select_2" name="select_2" depth="2" class="valid">
      <option value="26">Select subcategory</option>
      <option value="25">Studio</option>
      <option value="24">Apartment</option>
      <option value="23">Condominium</option>
      <option value="22">Penthouse</option>
      <option value="21">Townhouse</option>
      <option value="20">House and Lot</option>
      <option value="19">Villa</option>
    </select>

How do i need to do this? 

Thanks

**Comment by garciademarina** [comment]
for this kind of questions use the proper channel forums.osclass.org
