### ISSUE TITLE
mcrypt deprecated / removed past PHP 7.2/8.0

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2073]
Not urgent, but needs to be addressed later.

https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by andrewpros** [comment]
@dev-101 

Does osclass work already on php 7 without any issues?

**Comment by conejoninja** [comment]
As far as I know, yes, it does. I've been using PHP7 since a while now (several months) without any problem so far.

**Comment by andrewpros** [comment]
@conejoninja Thx for info, nice.
