### ISSUE TITLE
Occasional Error during image upload

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#2079]
Osclass 3.6.1 and PHP 7.0.11 and Imagik.

I see that error in the log at least once per day in all my 5 Osclass installations. I tried to replicate it, but failed. At least you could catch this error and display something.

PHP Fatal error:  Uncaught Exception: File doesn''t exist /home/public_html/oc-content/uploads/temp/qqfile_582532539a07f.jpg doesn't exist in /home/public_html/oc-includes/osclass/classes/ImageResizer.php:41
Stack trace:
#0 /home/public_html/oc-includes/osclass/classes/ImageResizer.php(24): ImageResizer->__construct('/home/p...')
#1 /home/public_html/oc-includes/osclass/controller/ajax.php(297): ImageResizer::fromFile('/home/p...')
#2 /home/public_html/index.php(117): CWebAjax->doModel()
#3 {main}
  thrown in /home/public_html/oc-includes/osclass/classes/ImageResizer.php on line 41

**Comment by conejoninja** [comment]
No the best solution
