### ISSUE TITLE
osc_validate_url() issue

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2086]
regex fails to validate this:

`freshandfunblabla.com`
`www.freshandfunblabla.com`

Those are all valid URLs [ `update: domain does not exist => thus validation fails)` ]

Also, I suggest that we move on to a more robust URL validation regex filter that conforms with RFC.
There are many tricky forms of valid URLs that current regex completely fails.

**Comment by dev-101** [comment]
Actually, I have looked into the validation more carefully, the reason why it fails is not regex, but the fact that domain is non-existent.

But, I'll leave this issue open for the regex part, nevertheless.

**Comment by conejoninja** [comment]
Could you specify a little more? I don't fully understand your issue, it's missing the protocol (http/http/ftp/...)
We do use filter_var, the regexp is only for PHP < 5.2 which is VERY old, next version of PHP, left there for compatibility issues, but should be removed (we'll not improve/fix it).

**Comment by dev-101** [comment]
Hi Conejo, so far I had not personally have any issues, and I rushed at opening an issue that was reported by a user, without detailed checking myself.

filter_var() is ok, but not XSS proof, so I guess (hope) osc_sanitize_url() is enough.

Will leave this case closed. Thanks!
