### ISSUE TITLE
Illegal offset type in isset or empty in /var/www/html/oc-includes/osclass/helpers/hUtils.php

### ISSUE THREAD

**Issue by RobbiNespu** [osclass/Osclass#2087]
Hi there, I got an warning on my apache2.. 
```Illegal offset type in isset or empty in /var/www/html/oc-includes/osclass/helpers/hUtils.php```

Any workaround?

**Comment by dev-101** [comment]
hUtils.php has 13 functions and 300 lines of code. Until devs deploy "gandalf" module (scheduled for next millennium), could you please provide a complete error with exact line # number (meanwhile)? From your error description, I would guess it's the osc_field() function. Also, post which version of Osclass you use, and some code sample or description how you trigger this warning (if possible).
