### ISSUE TITLE
typo in 3.7.0

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2090]
I believe this is a typo in 3.7.0

https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/classes/Scripts.php#L88

**Comment by dev-101** [comment]
Hi Conejo, not an issue? Because, I just don't understand this line, it does not do anything, the brackets should be closed after the next line. Thanks.

**Comment by conejoninja** [comment]
yes, it's an issue. I made the change but didn't push it yet.
