### ISSUE TITLE
Parameters bug in 3.7.0

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2092]
Possibly caused by recent changes. Original forum topic here:

http://forums.osclass.org/3-7-x/(bug)-parameters/

**Comment by dev-101** [comment]
not an issue

**Comment by dev-101** [comment]
* reopened *

This issue is related to Rewrite class and recent fix, however, another user on 2 different hosting systems (`bget.ru` and `hostland.ru`) experienced another bug, which is also related to the recent changes.

Setup was: PHP 7.0.13, MySQL 5.7, nginx 1.10.2

forum topic here:
http://forums.osclass.org/3-7-x/search-not-work-after-update-3-6-to-3-7-help-please!!!/

Problem was "fixed" by reverting regex changes.

**Comment by dev-101** [comment]
Proposed change by Conejo only partially fixed the problem with categories on nginx (forgot to mention permalinks were off).

Instead of mix/inversion of sPattern with sCategory, with proposed fix passes both sPattern and sCategory on category search (from main's page dropdown menu, as explained in the forum's topic).

**Comment by conejoninja** [comment]
hope I didn't break anything in the process

**Comment by dev-101** [comment]
Unfortunately, & character is now ignored on apache (same as before the whole fix) :(

**Comment by conejoninja** [comment]
This should fix it, https://github.com/osclass/Osclass/commit/416a4a1370c8a1ac0de4112d3ddc233a10fa5f47
but we'll still testing it

**Comment by dev-101** [comment]
quick test: works fine on apache w permalinks
will test later more
