### ISSUE TITLE
upgrade link work in demo

### ISSUE THREAD

**Issue by mngzir** [osclass/Osclass#2095]
Admin demo can upgrade the system
It should not work
And messages viwe the demo version

**Comment by conejoninja** [comment]
Which link are you talking about?

**Comment by mngzir** [comment]
pic
![up](https://cloud.githubusercontent.com/assets/23123726/21479779/84da99d2-cb6c-11e6-9dc7-117a9022dd39.png)

**Comment by conejoninja** [comment]
fixed here : https://github.com/osclass/Osclass/commit/645465d4dad94f46883f50c1a5217a672412a63b
