### ISSUE TITLE
OSClass category translation issue after move hosting

### ISSUE THREAD

**Issue by bAnDiTu** [osclass/Osclass#2100]
Hello,

I have a problem with category translation this is set to english and not translated to my language in my case Romanian.
I see a solution on OsClass forum and this is in the file:
oc-includes\osclass\model\Category.php after line 132 we need to add:
$this->dao->where(sprintf("b.fk_c_locale_code = '%s'", $this->dao->connId->real_escape_string(osc_current_user_locale()) ) );

I want to solve this issue because after an upgrade i don't want to need edit this file again.

Thank you!

**Comment by conejoninja** [comment]
We'll need more information to be able to reproduce this issue. Moving to another hosting shouldn't be a problem if you moved your databases too,as the information should be the same.

Could you please specify in more detail what did you do and what's the problem exactly?

**Comment by bAnDiTu** [comment]
Yes, try to move the files and database to another host and see this problem, but set the language to other than English before backup the filles and move.

This is not the first time when i move my website to another server and i have this problem.

**Comment by conejoninja** [comment]
I still don't understand your issue. Are the name of the categories not translated? Did you previously translated? Which thread in the forum are you talking about?

**Comment by bAnDiTu** [comment]
The categoryes and subcategoryes from everywhere it's not translated. I not translated it manualy it is translated by anyone. And for subcategoryes i not have a fix, if i go on main category my sub categoryes is not translated.
See here http://lamobil.ro/anunturi-vehicule.html

The forum where i found this fix is: http://forums.osclass.org/modern/categories-translation/

**Comment by conejoninja** [comment]
same as #1794

**Comment by bAnDiTu** [comment]
Yes, sorry.

**Comment by groomain** [comment]
Probably same as #2034 too

**Comment by arnaudknobloch** [comment]
I there, I have the same problem with category translation (in my case Albanian). I'm **not** using MariaDB. It's a clean install on a LAMP server Ubuntu 16.04. What can I do? (I don't want to start to editing the core files...)
