### ISSUE TITLE
Imagick LIB can't be UNselected after move to other hosting

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#2101]
Users have been reporting in the Forum that Imagick LIB can't be UNselected after move to other hosting (that Imagick is not enabled and can't be).

I think this is a bug and something must be done. Instead of telling them to edit the sql database.

Example:

http://forums.osclass.org/development/how-to-disable-imagemagick/msg146233/?PHPSESSID=s6dsa33m438i8qce8d7fqvada3#new

**Comment by dev-101** [comment]
Not sure that you'll like the solution: continuous checks if the lib is available or not whenever image processing is made. Do you really like that performance wise?

It is not a natural state, but user should be aware of system specs before they make a switch, and this can be easily "fixed" with one small visit with phpMyAdmin or similar.

**Comment by eurobank** [comment]
What "continious checks" means and why it should be continious ? Just check when this option at Admin dashboard is visited. If Imagick is not installed just auto-disable the option and default to GD.

And asking the users to edit the db is kinda absurd. They don't even know how to install and run Osclass.

**Comment by dev-101** [comment]
Sorry, was replying in a hurry, yes, that part can be done to automatically fallback to gd.
