### ISSUE TITLE
how to change from fulltext search(match against) to other search(LIKE) query?

### ISSUE THREAD

**Issue by mngzir** [osclass/Osclass#2103]
Search for fulltext is too weak and show little results
I want to change this to Like query?
please guide me Or in the new version do.
tnx

**Comment by conejoninja** [comment]
Pkease, ask this in the forums http://forums.osclass.org/

**Comment by mngzir** [comment]
The association has repeatedly asking, but incomplete answer
This is a big problem on search ads are weak.
