### ISSUE TITLE
Hook load cities

### ISSUE THREAD

**Issue by ehelguero** [osclass/Osclass#2106]
Hello, i´m having troubles with adding cities. When i marked them, i get the hook_load_cities error in location.js and no cities are added.

Thank you in advance.

**Comment by conejoninja** [comment]
Could you please specify the exact error and how to reproduce the issue?

**Comment by ehelguero** [comment]
Hello, in locations, clicking in a country and then in view-more link , in console show this error:

location.js:103 Uncaught ReferenceError: hook_load_cities is not defined
    at Object.success (location.js:103)
    at k (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at y (jquery.min.js:2)
    at XMLHttpRequest.d (jquery.min.js:2)

I looked into that file and no hook_load_cities is defined.

<img width="759" alt="captura de pantalla 2017-01-11 a las 12 18 44" src="https://cloud.githubusercontent.com/assets/1289195/21848327/21ca2c02-d7f8-11e6-8fd1-eae2503a4cca.png">
