### ISSUE TITLE
More places to modify content by filters?

### ISSUE THREAD

**Issue by andrewpros** [osclass/Osclass#2107]
Hi.

I have a question and a problem.

Why there are so many places where osclass is using run hook instead of providing an ability to modify content before osclass processes it further? I mean run hook is fire and forget, but there are places where it's better to have a filter.

My main problem is now with descriptions of user profile and items, i want then to save with HTML tags, i'm using ckeditor.

But there aren't any filters that would allow me to do it very simple, just override the saved text, it is always Params::getParam that's strips everything.

In UserActions https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/UserActions.php#L197

In ItemActions https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/ItemActions.php#L1162  

And to way to simply plug between.

Of course i know how to make it work, i just run a hook for posted_item and edited_item, grab description and update it again, this time with html tags, just after osclass updated it a sec ago, using my own purifier config with allowed html tags list.

Now i have to make it work the same way for profile description and i just wonder, couldn't we have filters on this or any way to allow devs to save it with their own purifier rules?

It works, but you know, it is somewhat awkward that i need to make a second update code just after normal osclass update code, if we had filter on this it would be just a matter of changing the data.

Or i'm wrong and there is other way?

**Comment by conejoninja** [comment]
Propose new filters with a PR and we'll (probably) accept them. We didn't have more filters/hooks because until now they weren't needed.
