### ISSUE TITLE
form to custom page not working

### ISSUE THREAD

**Issue by ehelguero** [osclass/Osclass#2108]
Hello, i created a custom page and create a page-xx-xx.php file. From the item page, i made a form in item.php and tried to send it to page-xx-xx.php but it says the page doesnt exist. Is there a way to send a form to a custom page?

**Comment by conejoninja** [comment]
Hi, custom pages should work, I tested it and it's working fine on my setup. It should be accessible directly, how are you accessible the page, which url are you using? how did you create the page? did you create a page on the admin too?
