### ISSUE TITLE
Market issues .

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#2111]
When buying  new item  on invoice fields , united kingdom is the only country . 
![buy_](https://cloud.githubusercontent.com/assets/5124319/22398533/d08689a8-e58a-11e6-8e85-e563f47407e8.PNG)
I'm logged, and email adress is   mandatory to input again .

**Comment by conejoninja** [comment]
Could you please expand? what issues are you experiencing?

**Comment by web-media** [comment]
updated  first comment . sorry !

**Comment by web-media** [comment]
Maybe some new fields on register 
 first name , last name, region,city   and  a small button => use   my default profile for  invoice

**Comment by conejoninja** [comment]
Country is selected based on your IP and some ip<->country database. So you are in the UK, or using a VPN located in the UK or the information at the database is wrong (it's made by a third party).

Just continue your purchase as usual, if you are not buying any osclass team's product, this doesn't affect you (and we could change your address later). If you are buying some osclass team's product, then contact us at info@osclass.org with your real location (country/region) and we'll work something.

**Comment by web-media** [comment]
im in spain . madrid .  no proxy used

**Comment by conejoninja** [comment]
Please, contact info@osclass.org with

Your IP 
What you were trying to purchase (from the screenshot, starter pack maybe?)
Your fiscal country
Your VAT/VIES/ID number

**Comment by web-media** [comment]
I've buyed html editor  
https://market.osclass.org/plugins/text-processing-wysiwyg-editors/html-editor_453
