### ISSUE TITLE
adding new rewrite rules

### ISSUE THREAD

**Issue by mlbxl** [osclass/Osclass#2115]
Hi all,

i added a new rewrite rule bij using Rewrite::newInstance()->addRule('^user/test/?$', 'index.php?page=user&action=test').
When i use the listRules function it returns alle the rules including the new added rule (so it's added successfully).
But when I try to go to example.com/user/test I get a 404 error, while going to example.com/?page=user&action=test works as it should.

What am I missing to get this to work?

**Comment by web-media** [comment]
osc_rewrite_enabled ?

**Comment by mlbxl** [comment]
yes

**Comment by conejoninja** [comment]
If you are developing a plugin, I suggest you to use osc_add_route instead. If you are modifying the core, then, could you share which modification did you made?
