### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by zorodimanche** [osclass/Osclass#2123]
Create e-mails for several site managers with a menu deranting (webmaster, site manager, partnership, advertising service ...) and then the user section the recipient in the contact page.

**Comment by conejoninja** [comment]
Not really an issue, but more as a feature

**Comment by dev-101** [comment]
Hi Conejo,
we could change the Conatact frm class to support select/dropdown menu, not only text input.

**Comment by conejoninja** [comment]
This could be easily done with a plugin or a custom page. I'm not a fan of the idea, I think it's better to have a single point of entry communication and let the admin redirect the email to the proper person/department. This could also be accomplish in some way letting the user choose the subject of the message from a predefined list.
