### ISSUE TITLE
Optimize the URLs

### ISSUE THREAD

**Issue by zorodimanche** [osclass/Osclass#2124]
Hi, Optimize urls for better SEO in search engines after several analyzes some osclass url are not seo friendly.

**Comment by conejoninja** [comment]
this issue is too general, please specify a little more

**Comment by zorodimanche** [comment]
Yes, thank you for your reaction: here are for example the urls that are not seo friendly :

www.mywebsite.com/index.php?sShowAs=list
www.mywebsite.com/index.php?sShowAs=gallery
www.mywebsite.com/vehicules/voitures/mercedes-classe-g_i9
www.mywebsite.com/vehicules/voitures/peugeot-208-gti_i8
www.mywebsite.com/vehicules/velos/velo-electrique_i7

**Comment by conejoninja** [comment]
could you please specify why they are not seo friendly?
