### ISSUE TITLE
Integrate the PayPlug payment platform

### ISSUE THREAD

**Issue by zorodimanche** [osclass/Osclass#2128]
Integrate the PayPlug payment platform as it offers more competitive rates than its competitors as paypal.
Moreover, the platform makes it possible to personalize the payment page and thus makes it possible to improve the reputation of the site and reassure the user.
https://www.payplug.com

**Comment by conejoninja** [comment]
This is a great suggestion, but we do not integrate paymet methods directly into the core. There are several payments plugins, with different options out there and I think it will be better integrated with any of those, for example payments pro.

**Comment by zorodimanche** [comment]
So payplug will be integrated ?

**Comment by conejoninja** [comment]
we may consider adding it to payments pro plugin, but we can not tell you if finally we'll do it or when. We need to study the case and consider our options. We continuously add new payment processors to payments pro plugin. Other authors may consider adding it to their plugins too. I suggest you contact some of them, for example from here : https://market.osclass.org/plugins/payments

**Comment by zorodimanche** [comment]
Tank you conejoninja I will contact they
