### ISSUE TITLE
osc_get_preference() cast type issue

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2130]
Hi,

I have noticed that osc_get_preference() always returns type of value as a string, even if we set the type to BOOLEAN in the osc_set_preference().

The reason why I am opening this issue is because of one strange problem that happened on one server from a client, inverse (!) logic was not working as expected, although the string value returned was empty ("") and so I had to change the logic to check for string value == "" (or == "1" or != "") instead using (!) in front like a bool. Again, really puzzled by this, as I could not reproduce the problem on my end, and also no one else complained (so far).

`update`: now when I think about this, maybe the problem was not related to the type, but return context, again no errors on my servers were shown and everything worked as expected.

Should we cast the BOOLEAN type preference values to (bool) in the core?
Thanks

**Comment by conejoninja** [comment]
You have the helper osc_get_bool_preference taht will return a boolean.
The type on the database (INTEGER, STRING, BOOLEAN) is pretty much useless as it's not used anywhere. 

osc_get_preference always return a string since the database field is text (no matter the type).

Also, I suggest you use the !== and === instead of != / ==


Also, according to this : http://php.net/manual/en/language.types.boolean.php
an empty string should be consider "false" :/

**Comment by dev-101** [comment]
Thanks CONEJO,
really missed that helper - it's really useful!

The strange part is that this worked so far every time, as also mentioned in php manual, but then again, something like this happens.

:beers:

**Comment by dev-101** [comment]
Hi Conejo,
I just got an error that osc_get_bool_preference() function does not exist :)

Is this is some PR / develop branch maybe? I have searched similar functions, but did not find any :(

We have getBoolPreference($key), but it does not support custom sections - maybe this is the one?

**Comment by conejoninja** [comment]
Right, my mistake, we have this : https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/helpers/hPreference.php#L1091

But this is only for preferences wuth s_Section = 'osclass'.

We may consider adding this helper though

**Comment by dev-101** [comment]
Thanks! :+1:
