### ISSUE TITLE
Alert is not working if the subscribed user is not registered.

### ISSUE THREAD

**Issue by dev-subhojit** [osclass/Osclass#2131]
I tested the alert system, on the file Alerts.php look there is a code(file: oc-includes/osclass/model/Alerts.php 184 No Line)  `$this->dao->where('fk_i_user_id', $user);` this should be look like this: `$this->dao->where('pk_i_id', $user);` because if the user not been registered on the site the foreign key of the alerts table(column fk_i_user_id) is marking as zero. In this case no email should be send while cron is running. And also I am sure this code (file: oc-includes/osclass/alerts.php 77 No Line) `$alert = Alerts::newInstance()->findBySearchAndUser($s_search['s_search'], $user['pk_i_id']);` is collecting the primary key from the table alerts please check this code(file: oc-includes/osclass/alerts.php 68 No Line): `$users = Alerts::newInstance()->findUsersBySearchAndType($s_search['s_search'], $type, $active);`

After fixing this issue I am receiving the alerts. Please check and resolve the issue. Thanks

**Comment by tabuausada** [comment]
Can you please confirm this issue relates to my problem? Look here please: http://forums.osclass.org/3-7-x/user-alerts/

**Comment by dev-subhojit** [comment]
You can try this code, here is the updated file. Just need to change on the line number 184. https://github.com/osclass/Osclass/pull/2133/files?diff=split

**Comment by dev-subhojit** [comment]
@tabuausada is that work for you?

**Comment by tabuausada** [comment]
Yes it works! You rock thanks!

**Comment by conejoninja** [comment]
Fixed correctly here : https://github.com/osclass/Osclass/commit/17ca0114d4905ebaae6ca12ea8915c6701521b78
