### ISSUE TITLE
All Dates Displayed as 17th of a Month

### ISSUE THREAD

**Issue by timobezjak** [osclass/Osclass#2134]
On my osclass installation, user registration and listing creation dates are all set to the 17th of the current month in the client and admin UIs. They are different (presumably correct) in the database. See screen shots attached. 

Attached you can find a listings display (https://music.ch/kleinanzeigen/equipment/hughes-and-kettner-amps-und-diverses-neuwertig_i352) for an example, and the respective database record which shows different dates. 

<img width="806" alt="member-listing-17" src="https://cloud.githubusercontent.com/assets/683478/23557791/8bb08f56-0031-11e7-98ad-05195cb74329.png">
<img width="1181" alt="member-listing-database" src="https://cloud.githubusercontent.com/assets/683478/23557793/8bb4c526-0031-11e7-9996-558c311c9e95.png">

Also you can find overviews from the admin ui where all these dates are equally displayed as 17th of some month.

![listings-17](https://cloud.githubusercontent.com/assets/683478/23557794/8bb53e5c-0031-11e7-9c18-c6ee8ca793eb.jpg)
![users-17](https://cloud.githubusercontent.com/assets/683478/23557792/8bb30ca4-0031-11e7-8010-5fb2af8c3516.jpg)

**Comment by conejoninja** [comment]
We are not able to reproduce this issue,

Is there anything unusual in your setup? some plugin maybe?

**Comment by timobezjak** [comment]
Today I figured it out: It’s the custom date format I was using. 
8/4/2017 is totally uncommon in Switzerland, as are the other osclass 
standards. So I used "y. M Y" – and the preview showed it, as 
expected, as 8. Apr 2017. Today I dropped that and voilà, the dates are 
correct. I guess that would make it an osclass bug, or was there an 
error in my date format string? I’ll use the uncommon time format for 
the time being, but I will very gladly return to a custom string as soon 
as this is fixed.

Thanks for all your good work!
—Timo

**Comment by conejoninja** [comment]
Thanks for the information, I reopen the issue as the preview should be the same as the date shown later

**Comment by conejoninja** [comment]
We're not able to reproduce this issue, the format "y. M Y" returns the "correct" date formate : 17. Apr 2017

As per PHP docs : http://php.net/manual/en/function.date.php  "y" is the 2-digits year (17).

If you could provide more information about your setup we might be able to reproduce this issue and fix it.

**Comment by timobezjak** [comment]
I’ll need to check if I mistakenly used that wrong format string or if 
I mistakenly posted you a different one than I actually used. Either 
way, sorry for the mistake. I’ll get back if needed.
