### ISSUE TITLE
500 Error when posting new ad with photo using PHP 7.1.2

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2139]
forum topic here:
http://forums.osclass.org/3-6-x/500-error-when-posting-new-ad-with-photo-using-php-7-1-2/

**Comment by dev-101** [comment]
I have reproduced it on PHP 7.1.2:

>PHP Warning:  Illegal string offset 'a709e41d-4a2e-44a3-8ea5-1159c01fa6f6' in /osc371/oc-includes/AjaxUploader.php on line 54

>PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /osc371/oc-includes/osclass/ItemActions.php:1175

**Comment by conejoninja** [comment]
We are not able to reproduce the issue. How could we reproduce it?

**Comment by conejoninja** [comment]
This doesn't happen in hotfixes, it does in master , here are some fixes for some warnings, https://github.com/osclass/Osclass/commit/cade8770183f86ae1e315757d611d61e68dae4b4 but we were only able to reproduce the fatal error in the master branch
