### ISSUE TITLE
All Custom fileds in search filter can not work.search do not work

### ISSUE THREAD

**Issue by NelsonFx** [osclass/Osclass#2156]
From http://forums.osclass.org/3-7-x/(problem)-all-custom-fileds-in-search-filter-can-not-work-search-do-not-work!/msg146913/#msg146913

Hi.
After updating from 3.6.1 to 3.7.1 oc can not search custom fields.
I see it do not pass custom fields parameters to url (GET).
only price and title can be searched and pass to url.
please solve that.
Thanks.

------

i have a new installation and have the same problem with a clean installation.

**Comment by dev-101** [comment]
Post details how to reproduce this issue, step-by-step.
Also, it may help to know which php version, server, what htaccess/osclass settings you have.

It works fine on several instances here.

**Comment by NelsonFx** [comment]
i tested in the  fully hosted Osclass Free service and works great but is v3.6.1

Apache version v2.4.10
PHP version v5.6.30  FCGId
OsClass v3.7.1

-- .htaccess
<IfModule mod_deflate.c>
# force deflate for mangled headers 
<IfModule mod_setenvif.c>
  <IfModule mod_headers.c>
    SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
    RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
  </IfModule>
</IfModule>

# HTML, TXT, CSS, JavaScript, JSON, XML, HTC:
<IfModule filter_module>
  FilterDeclare   COMPRESS
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$text/html'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$text/css'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$text/plain'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$text/xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$text/x-component'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/javascript'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/json'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/xhtml+xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/rss+xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/atom+xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/vnd.ms-fontobject'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$image/svg+xml'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$application/x-font-ttf'"
  FilterProvider  COMPRESS  DEFLATE "%{CONTENT_TYPE} = '$font/opentype'"
  FilterChain     COMPRESS
  FilterProtocol  COMPRESS  DEFLATE change=yes;byteranges=no
</IfModule>

<IfModule !mod_filter.c>
  # Legacy versions of Apache
  AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
  AddOutputFilterByType DEFLATE application/javascript
  AddOutputFilterByType DEFLATE text/xml application/xml text/x-component
  AddOutputFilterByType DEFLATE application/xhtml+xml application/rss+xml application/atom+xml
  AddOutputFilterByType DEFLATE image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype
</IfModule>
</IfModule>
<IfModule mod_expires.c>
  ExpiresActive on

# Perhaps better to whitelist expires rules? Perhaps.
  ExpiresDefault                          "access plus 1 month"

# cache.appcache needs re-requests in FF 3.6 (thx Remy ~Introducing HTML5)
  ExpiresByType text/cache-manifest       "access plus 0 seconds"



# Your document html
  ExpiresByType text/html                 "access plus 0 seconds"

# Data
  ExpiresByType text/xml                  "access plus 0 seconds"
  ExpiresByType application/xml           "access plus 0 seconds"
  ExpiresByType application/json          "access plus 0 seconds"

# RSS feed
  ExpiresByType application/rss+xml       "access plus 1 hour"

# Favicon (cannot be renamed)
  ExpiresByType image/x-icon              "access plus 1 week" 

# Media: images, video, audio
  ExpiresByType image/gif                 "access plus 1 month"
  ExpiresByType image/png                 "access plus 1 month"
  ExpiresByType image/jpg                 "access plus 1 month"
  ExpiresByType image/jpeg                "access plus 1 month"
  ExpiresByType video/ogg                 "access plus 1 month"
  ExpiresByType audio/ogg                 "access plus 1 month"
  ExpiresByType video/mp4                 "access plus 1 month"
  ExpiresByType video/webm                "access plus 1 month"

# HTC files  (css3pie)
  ExpiresByType text/x-component          "access plus 1 month"

# Webfonts
  ExpiresByType font/truetype             "access plus 1 month"
  ExpiresByType font/opentype             "access plus 1 month"
  ExpiresByType application/x-font-woff   "access plus 1 month"
  ExpiresByType image/svg+xml             "access plus 1 month"
  ExpiresByType application/vnd.ms-fontobject "access plus 1 month"

# CSS and JavaScript
  ExpiresByType text/css                  "access plus 1 year"
  ExpiresByType application/javascript    "access plus 1 year"
  ExpiresByType text/javascript           "access plus 1 year"

  <IfModule mod_headers.c>
    Header append Cache-Control "public"
  </IfModule>

</IfModule>


####Custom Rewrite Rules Start###
RewriteEngine on
RewriteBase /
RewriteCond $1 ^(index\.php)?$ [OR]
RewriteCond $1 \.(gif|jpg|css|js|png|ico)$ [NC,OR]
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^(.*)$ - [S=1]
RewriteRule . /index.php [L]
####Custom Rewrite Rules End####

**Comment by conejoninja** [comment]
Not sure what .htaccess has to do with it or how to reproduce the issue.

Could you please specify which custom fields are you using? or better, share a copy of your database, if you don't want to make it public, send it to desteban@osclass.org

**Comment by dev-101** [comment]
Idea is that some custom rewrite rules can interfere with meta & permalinks (very remote, but it can happen). I had similar issues recently, when upgrading to new server, though it wasn't with Osclass.

**Comment by conejoninja** [comment]
@NelsonFx please provide some url examples and probably a database backup too to be able to reproduce this issue

**Comment by conejoninja** [comment]
Will open this issue when some more information is provided, as we can not reproduce it
