### ISSUE TITLE
meta fields htmlentities() issue

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2162]
If we need to use **<** or **>** symbols in metas (discovered with **dropdowns** CF type), this will be a problem when using standard helper osc_item_meta_value(), because for e.g. **<** will be first converted to **`&lt;`** while stored into database, and then again processed with htmlentities() while printing.

expected result:

`<` (stored as `&lt;` in db)

result now as it is:

`&lt;` (actual HTML is `&amp;lt;` because of double processing)

-------------------------------------------------------------------------------

`update:`
preliminary fix (for **dropdowns**) is to replace **htmlentities()** with **html_entity_decode()**
https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/helpers/hItems.php#L1243

**Comment by dev-101** [comment]
Another problem, which seems to be related (but it might not be, just discovered it):

- create dropdown CF with fractions as options, for example [4] numbers: **1 1/2, 2 1/4, 3 1/8, 4 1/2**
- generate some items with random cf value from above

issues:
(1) without permalinks: when you are in that category, try to filter results by some fraction number, it will show all items (breaking url: say, we were here **index.php?page=search&sCategory=97** before filtering, now we will end up here: **index.php?page=search&sOrder=dt_pub_date&iOrderType=desc** instead of proper url with meta)

(2) with permalinks (apache): while url will not be broken (**search/sOrder,dt_pub_date/iOrderType,desc/meta3,1+1+2/category,Test**), the results will be 0 (nothing found)

**Comment by conejoninja** [comment]
I only found the issue on the admin, on the public/front it was shown correctly. Not sure if this fix the issue or we are missing something.

About the search and "/" it's complicated to fix, in other fields (like pattern) it will be removed, so it makes sense to be removed here too. (it's not a custom field problem, but a search one)

**Comment by dev-101** [comment]
Hi Conejo, yes, exactly, the problem is within osc_item_meta_value() helper.
About 2nd issue, ok, I also think it is better to leave it for now.

**Comment by dev-101** [comment]
Hi Conejo, I have just saw the fix. Not sure if need this in the form? Because, the helper is faulty.

**Comment by conejoninja** [comment]
The form field doesn't use the helper, so a fix there was needed. I just fix the helper for dropdown and radio options (where it fails). Text and textarea doesn't allow some characters (< >   )

**Comment by dev-101** [comment]
Thanks, I bluntly asked you this, as I wasn't investigated it as I should. :beers:
