### ISSUE TITLE
PHP Warning:  array_merge(): Argument #1 is not an array in /oc-admin/main.php on line 93

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2166]
sys
`PHP 7.0.17 + latest hotfix`

getting this notice sometimes:

`PHP Warning:  array_merge(): Argument #1 is not an array in /oc-admin/main.php on line 93`

**Comment by xiris** [comment]
Looks like is a problem in retrieving the featured plugins from the market.

- This is from local development or some hosting?
- Did you connect (login) to the marketplace?

**Comment by dev-101** [comment]
Sorry, forgot on this, json data is fetched properly, it was custom mod that interfered with widgets later that caused this issue.

Problem was the result is `null`, and notice is later generated in next line while decoding.
I have simply hidden the notice by casting array_featured_ vars into `(array)`.

/ closing /

**Comment by dev-101** [comment]
However, just recalled that same is working fine in different server & PHP version (5.6 branch) without any issue, so this could mean some PHP 7.0.x incompatibility specifically. Will create PR, not sure if it will be accepted, though.

**Comment by xiris** [comment]
Maybe it is related with the "custom" implementation of the json_decode/encode functions and lot of others?

**Comment by dev-101** [comment]
Not sure, really, as I haven't modified anything PHP related in core admin files.

**Comment by xiris** [comment]
I mean, the platform have custom implementation of some php functions

**Comment by dev-101** [comment]
Thanks for the edit/example, did not cross my mind, but could be related.
Anyway, this is accepted/merged now.
