### ISSUE TITLE
Fresh install  error

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#2179]
[23-Apr-2017 16:58:13 Europe/Madrid] PHP Fatal error:  Call to undefined method Translation::init() in xxx/public_html/oc-load.php on line 257 
on fresh install zip  from github
endlesss  upgrade 
![capture](https://cloud.githubusercontent.com/assets/5124319/25314588/5603d53c-2847-11e7-9b1b-a9ae2b5af9d7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5124319/25314587/56025680-2847-11e7-8e99-c0abd80c7119.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5124319/25314586/55ffd9d2-2847-11e7-936f-569818d435c5.PNG)

**Comment by dev-101** [comment]
You have messed something up. You say it is a "fresh install", but from your screenshots, I would say that you have tried to upgrade an existing version, and something went wrong (incomplete => thus, endless upgrade loop).

I have installed just now fresh master branch (373) without issues, and past week hotfixes branch for testing. No problem.

**Comment by conejoninja** [comment]
That doesn't look like an installation, more like an upgrade. And it looks like something when wrong, because the highlight are from the 3.6 version, but it should say "3.7 highlight" instead.

Please, make sure that all files have the correct permissions and that there wasn't any problem uploading/copying files. Try uploading the files again.

**Comment by web-media** [comment]
Does  looked strange to me also . I've installed osclass more than 100 times  from version 2.1.1 to 3.7.1 in  various setups.
First was  the error [23-Apr-2017 16:58:13 Europe/Madrid] PHP Fatal error: Call to undefined method Translation::init() in xxx/public_html/oc-load.php on line 257 . 
After removing the line 257 from oc-load  file y was  able to access  the admin panel  and  the endless  upgrade  loop  came up
I've deleted the database and all files  to install again the script  from github  zip with  no issues .
