### ISSUE TITLE
My osclass website is suffering; CSRF token is invalid.

### ISSUE THREAD

**Issue by kw3ku** [osclass/Osclass#2190]
Not just CSRF token is invalid.
Users cannot sign in
Admin cannot take any function correctly, its a worrying situation. 

Please, help me

**Comment by kw3ku** [comment]
www.oxglow.com.gh

**Comment by krahamath** [comment]
From when this problem happen ? after change or edit something like plugin or theme ?

**Comment by conejoninja** [comment]
Check the free disk space on your server and the permissions of your session' folder. Looks like PHP is unable to write sessions and it's usually either there's no space left on the disk or the folder has wrong write permissions.

You could enable PHP debug to see what is happening : https://doc.osclass.org/Debug_PHP_errors

**Comment by kw3ku** [comment]
There is enough disk on the website, now there is a new problem. users cannot sign into their account.  Why don't you give it a try on the website?  I am facing problems in there.

**Comment by kw3ku** [comment]
What is session folder ??

**Comment by kw3ku** [comment]
i did a clean install and still the problems are showing up in that as well.
