### ISSUE TITLE
Missing upgrade button

### ISSUE THREAD

**Issue by krahamath** [osclass/Osclass#2195]
I see Upgrade button is missing, what is the problem ?
![osclass_upgrade_button](https://cloud.githubusercontent.com/assets/6831562/25717228/13e7e6b6-3102-11e7-9bff-79d3e7a0ad50.png)

**Comment by conejoninja** [comment]
If you're using a SSL certificate please do these changes : https://forums.osclass.org/3-7-x/can't-upgrade-to-3-7-3/msg149546/#msg149546 or upgrade manually.

**Comment by krahamath** [comment]
Thanks. May i know, future upgrade also required this or you will update the code ?

**Comment by conejoninja** [comment]
It shouldn't happens in future versions.

**Comment by krahamath** [comment]
Great, Thank you.
