### ISSUE TITLE
"Ajax error, please try again." when changing the category order

### ISSUE THREAD

**Issue by HKJCoder** [osclass/Osclass#2207]
Hi,
Referencing this issue

 #1965 

The problem still there in the latest osclass version 3.7.3

To reproduce:

- Drag and drop Sub Category into main category. You will get alert that this could take a while
- Drag and dropping many categories in the same time let osclass hit entry process limit in the server.

Debug procedures:
- Talked with hosting provider to confirm its not a server issue.
- Installed fresh copy of osclass from softaculos  
- I had tried to change PHP to 5.6, 7 and 7.1 but still same problem.
- Also changed max_input_vars as suggested but no use.

Each drag and drop create another instance of XHR request; tell getting error 803 or 500 from hosting.
Please refer to attachment.

Kindly advice.
Thank you
![capture](https://user-images.githubusercontent.com/26726985/27723892-e2d712f2-5d77-11e7-8577-1e36163387cf.PNG)

**Comment by dev-101** [comment]
- tldr:
no matter what "they" say, this is a hosting related issue.

Now, which hosting is it? How many entry process limit are we talking about? I never had this issue in any server, including one shared with 20 processes max, but number of main categories is just 4, and up to 30 subcats at most there. How many subcategories are there - 1 000, 10 000, 100 000?

**Comment by conejoninja** [comment]
How many categories do you have?
Looks like it only happens sometimes and not always.
How often did you moved/sorted the categories?

It's a bit worrying that each time it takes more and more to process the request, but besides that, looks like a timeout.

**Comment by HKJCoder** [comment]
Hi,
as i said, i installed osclass using softcoulaus with its default test category (general)
thank you

**Comment by HKJCoder** [comment]
if we ignore the ajax error that comes always, please refer to attached image, always its taking long time , up to 3 to 5 min, which is weird for drag drop only 15 category at a time; then site hits entry limit!!!

the hosting i use is recommended by osclass.org

even if we consider its not a bug, each drag drop run in its own XHR instant , so  hosting will consider 10 drag drop as running the script 10 times concurrent.

Hope you may consider another approach for reorder categories.

**Comment by dev-101** [comment]
Moving default number of categories, even in fast sequence one after another, should take very little time, really (less than 1 second for each request on cheap servers, and less than 0.1 seconds on faster ones).

Something is not right in your case, as the requests take minutes to complete, and as you pile them up in sequence, starting new when olders were not complitet hits your limit somehow.

I can only speculate what is wrong, but could be a very slow CPU, limited CPU, or issues with database connections that have long delays for some reason.

Try different hosting and see if it happens there.
