### ISSUE TITLE
More inforamtion in user managment panel + more fields in registration form

### ISSUE THREAD

**Issue by nikopolll** [osclass/Osclass#2213]
In user account panel, user can specify if user is company or private person. But there is no such information in user management panel for admin. This could be new column with icon different for privet users and for companies.

Secon issue. This could be a plugin. Registration form should be splited for two parts. One for private users (like is now), and second with additional fields for companies: 
- Name of company
- Adress
- Contact number
- e-mail adres
- invoice data - this could be text field, because in different countries  are needed diffrent informations.

**Comment by conejoninja** [comment]
Hi, thanks for sharing your ideas.

The company/user column could be added in the admin panel with a plugin, or instead a new column could be to change the color of the row.

About the registration process, that's a thing for the theme, and maybe a plugin. Some of the fields which are in Osclass (address, contact number, email address,...) could be added to the registration form without doing anything else and it will work. New fields (invoice data, name of company,...) requires a plugin. It's done in the market https://market.osclass.org/user/register

I don't think we should include any of those in the core of Osclass, therefor I'm closing this issue.
