### ISSUE TITLE
Unable to delete city from database

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#2214]
I tried to delete city from admin pannel. But it was not deleted,
Next i tried to delete city from msql but still not deleted and getting this error find the image below,
Hope you will help me here.. Thank u
![screenshot_2017-07-18-03-48-55-211](https://user-images.githubusercontent.com/15182895/28306145-d54a8d56-6bbb-11e7-9260-45b4d2261036.jpeg)

**Comment by conejoninja** [comment]
We are unable to reproduce this issue, so it looks like it is not a bug, but some problem of your specific settings (plugins), please open a thread in the forums: http://forums.osclass.org/

The error says it, oc_t_city table depends on oc_t_city_stats, so you first need to delete the values of the city you want to delete from oc_t_city_stats (probably there are other references, like oc_t_item_location,...etc).


Probably there's a plugin that doesn't allow you to delete the city for some reason. DO NOT remove values directly from the database, you are at risk of "corrupting" your data.

**Comment by abdulghanysyed** [comment]
Thank you for intimating this  DO NOT remove values directly from the database, you are at risk of "corrupting" your data.

**Comment by conejoninja** [comment]
I didn't want to intimidate anyone, but the truth is that unless you know what you are doing, it's a bad idea and will cause more errors than it fixes.
