### ISSUE TITLE
error after publishing listing

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#2215]
getting error after publishing listing http://classibook.com/item/new 
please sir, help me to solve this issue,...

find the image http://prntscr.com/fyusxt

**Comment by conejoninja** [comment]
remove the } from the email ban rule in your admin panel

**Comment by abdulghanysyed** [comment]
sorry to say sir, i not found this } ban rule in my users>ban rule 
have so many spam mails already detected 
i have cheked but still not found...

is there any other way to find?

**Comment by conejoninja** [comment]
Check for other strange characters in the ban rules, it's because of that

**Comment by abdulghanysyed** [comment]
i want to check every email in ban list?

**Comment by abdulghanysyed** [comment]
i have disbaled all ban rules, but still same issue, please sir help me

**Comment by abdulghanysyed** [comment]
I Have deleted all rules from database now its working more than 68000 spam mails i found, but i dont that much of listings on my site :paintbrush:
