### ISSUE TITLE
Custom item expiration by integer removed for good?

### ISSUE THREAD

**Issue by andrewpros** [osclass/Osclass#2219]
Hi.

First of all i don't know if it is a bug or permanent change.

I updated osclass from 3.5.7 to 3.7.3 recently, updated on production (tested on local before, no issues) and to my surprise the custom expiration date was not working anymore (3,5,7,14, etc days), users were reporting that their items was set to never expire.

So i checked all the release changelogs, nothing there.

Finally i had to investigate the source code with debugger and i found out that in 3.7.0 there was a change in code regarding the dt_expiration param and stayed that more or less till now 3.7.3 https://github.com/osclass/Osclass/blob/v3.7.3/oc-includes/osclass/ItemActions.php#L1195

Now before 3.7.0 there wasn't any category code if it was an int value, if not, then and only then it was using the category default expire days.

Now it looks this is gone and if i want custom date i need to provide the full format date yyyy-mm-dd? And it will always end on 23:59:59?

**Comment by garciademarina** [comment]
![image](https://user-images.githubusercontent.com/546607/41547607-f63ce028-7320-11e8-99b0-99bdb8e0814a.png)

You can set **days** _(integer)_ or a **date time**.

**Comment by andrewpros** [comment]
Yeah, no thanks after a year, this script is terrible.
