### ISSUE TITLE
Problem in Searching Chinese Text

### ISSUE THREAD

**Issue by zfc0812** [osclass/Osclass#2223]
This issue has been[ previously closed](https://github.com/osclass/Osclass/issues/1221) back in 2013. However the suggested solution is not working for the current version of Osclass. I changed the line 822 to the code to
`$this->dao->where(sprintf("(d.s_title LIKE '%%%s%%' OR d.s_description LIKE '%%%s%%')", $this->sPattern, $this->sPattern));`

But Chinese search is still not supported.

**Comment by conejoninja** [comment]
It was explained in #1221

**Comment by zfc0812** [comment]
It is not working on current version of Osclass. I changed the line 822, but the problem is not solved.

**Comment by conejoninja** [comment]
Try changing line 943 
https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/model/Search.php#L943

**Comment by zfc0812** [comment]
Thank you very much! It's work!

**Comment by maxrubino** [comment]
Hello,
in last version 3.8.1 is already like that the line 943. It does not work, what to do?
