### ISSUE TITLE
Search function not working after changing site language to Chinese

### ISSUE THREAD

**Issue by zfc0812** [osclass/Osclass#2224]
I am using the Chinese (China) language pack available from Osclass  market. After setting the site language to Chinese, the search function is not working regardless of searching English text or Chinese text.

**Comment by conejoninja** [comment]
Not able to reproduce the issue, did you made any modification to the files?

**Comment by dev-101** [comment]
Hi, this is not a bug, but by design. Please, verify that you indeed have items posted with search keywords in proper language title/description. Search will only return items if the match is found for particular language.

**Comment by zfc0812** [comment]
I do not make any modification to the file. Please see [my site](http://www.woyao.my). Set the site language in English and search "phone" (without quote), search result will be returned. However, if ou change the site language to Chinese and search the same keyword, no result will be returned.

**Comment by conejoninja** [comment]
Search only works on the selected language. If the users has selected Chinese, it will only search on items that have a chinese title/description.

Check that listings have a chinese title/description, also enable SQL debug https://doc.osclass.org/Debug_SQL_queries to see if there's some error in the SQL (I doubt it)
