### ISSUE TITLE
Unfortunately my database lost in oc-item backup not working

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#2225]
i have lost my oc-item database 
but i have a backup 
when i am restoring that backup i am getting error

Error
SQL query:

CREATE TABLE `oc_t_admin` (
  `pk_i_id` int(10) UNSIGNED NOT NULL,
  `s_name` varchar(100) NOT NULL,
  `s_username` varchar(40) NOT NULL,
  `s_password` char(60) NOT NULL,
  `s_email` varchar(100) DEFAULT NULL,
  `s_secret` varchar(40) DEFAULT NULL,
  `b_moderator` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8
MySQL said: Documentation

#1050 - Table 'oc_t_admin' already exists

How to solve this?

**Comment by conejoninja** [comment]
For the last time, post your issues in the forums https://forums.osclass.org/

This is not an issue with the code itself, but with your setup. Also, the error is quite explicit, the table already exists and the backup is trying to create it again. Remove tables from your database or do not create them in your backup. Make sure the backup you have has the information (data) too and not only the structure of the tables before deleting anything. Make sure plugin's tables are backup'd too.

And once more, ASK IN THE FORUMS, this is not the correct place to.
