### ISSUE TITLE
invalid email address verification on resend password request

### ISSUE THREAD

**Issue by DeveloperChris** [osclass/Osclass#2228]
Hi

When requesting a new password the test for email validity is itself invalid.

Verifying email addresses is fraught with difficulty it is best to leave the verification to php's built in filter function.

I had a customer complain they could not resent their password, on testing I realised that the email address included an apostrophe entirely valid in email addresses but often missed when creating a 
validation routine.

in login.php around line 202 replace the following line 
   if( !preg_match('|^[a-z0-9\\.\\_\\+\\-]+@[a-z0-9\\.\\-]+\\.[a-z]{2,3}$|i', Params::getParam('s_email')) ) {
with
   if (!filter_var(Params::getParam('s_email'), FILTER_VALIDATE_EMAIL)) {

**Comment by garciademarina** [comment]
I will change line 202 and use osc_validate_email() function that is already in osclass core. 

**osc_validate_email** will return true with the following email address ```o'connor@example.com```

```osc_validate_email("o'connor@example.com")```
