### ISSUE TITLE
BUG with same city names

### ISSUE THREAD

**Issue by visiondesignzoo** [osclass/Osclass#2231]
Hi, i have a problem with searching by city name.

Go to OSCLASS demo, chose modern for instance, go to search page and start type city CASTELLANOS. As you start type, you will see 2 CASTELLANOS, one from Léon (first) and the second from Zamora. Now, select the second option, from region Zamora and click on Apply to search. Take a look now at the breadcumbs where you will see NoLogo Inc. » León » Castellanos

I have the same problem on my Osclass installation.
Please, how to fix the big bug?

Many thanks!

**Comment by teseo-2014** [comment]
Hi,

Proposed solution here:

https://forums.osclass.org/general-help/bug-with-same-city-names/msg156867/#msg156867

Regards

**Comment by garciademarina** [comment]
fixed e1bb7eb
