### ISSUE TITLE
Admin to approve/confirm new users - feature request?

### ISSUE THREAD

**Issue by andreasba** [osclass/Osclass#2237]
Good afternoon

I am setting up osclass (which is a fantastic project, thank you! :)) and would like to be able to confirm users before they can actually post any ads, even tough they confirm their e-mail addresses.

The reason for this is that for the start, it should be a more closed user group but the website should be accessable via the Internet.

I searched a lot but only found an old plugin from oscanyaon which does not seem to exist anymore, so I think this would be a great addition to the project?

Unfortunately I am not a great coder so I can only suggest.

Thank you
Andreas

**Comment by garciademarina** [comment]
You could do it through plugins. 

You can take a look at **more edit plugin** https://market.osclass.org/plugins/ad-management/more-edit_23

This plugin will increase the control over the listings, you can take a look maybe it's useful to you.
