### ISSUE TITLE
split/separate "Location" step @ installation

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2238]
(explanation for this request is in a form of a short story - please read on to understand why)

Subject: Osclass 3.0.2 (blast from the past) ~ related to Osclass 3.7.4 (current)
_________________________________________________________________________

Hi, something interesting I found by accident today, that is, while testing a plugin for a forum user who could not install it inside ancient Osclass version 3.0.2.

Apparently, it is no longer possible to install old Osclass 3.0.2 (either for fun, or debugging) because of **location** stage, whose js does not fallback any longer as it did before (and because url for geo installation is changed), so the user is stuck at 3rd installation step 'forever'.

But, anyway, all that is not at all important in this issue; what's important is that we should separate the page (step) of admin/contact/web-title creation **and** move location step into the next (separate) step after the admin user was created, to avoid this kind of "compatibility" issues in the future, so, users can manually skip the geo stage if it fails for whatever reason, but the admin user, along contact and title will be created (e.g. manual skipping will not skip a lot of tasks, just location task). Hope you get the idea. I know that the js code is no longer the same for location selector, like the one in the past, but who knows if it can "strike again" in the future.

What do you think? :)

**Comment by garciademarina** [comment]
We cannot maintain compatibility with older versions, you are talking about a version that is more than 5 years old. 

However I guess we should have released a major release, something like 4.X.X 

More info here: https://semver.org/

**Comment by dev-101** [comment]
Hi Carlos, I wasn't referring to old version :)

As I mentioned, old version is not important ;)

I was just suggesting to separate location stage in latest Osclass.

Thanks
