### ISSUE TITLE
HTML Purifier

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#2245]
HTML Purifier current version is 4.9.3
>HTML Purifier 4.9.3 released
 on Monday, June 19, 2017

HTML Purifier osclass version 4.5.0
>PHP Version 7.2.1

```php 
[21-Jan-2018 22:50:42 Europe/Berlin] PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in xxx\osclass374\oc-includes\htmlpurifier\HTMLPurifier.autoload.php on line 17
```

**Comment by dev-101** [comment]
Problem is that new version is not released yet, so even if OT wish to fix this, they can only manually apply the patch atm: https://github.com/ezyang/htmlpurifier/issues/154

**Comment by web-media** [comment]
> HTML Purifier4.9.3, released 2017-06-02
+- Workaround PHP 7.1 infinite loop when opcode cache is enabled.

>HTML Purifier 4.8.0 is a bugfix release, collecting a year
+of accumulated bug fixes.  In particular, we fixed some minor
+bugs and now declare full PHP 7 compatibility. The primary
+backwards-incompatible change is that HTML Purifier will now
+add rel="noreferrer" to all links with target attributes
+(you can disable this with %HTML.TargetNoReferrer.)  Other
+changes: new configuration options %CSS.AllowDuplicates and
+%Attr.ID.HTML5; border-radius is partially supported when
+%CSS.AllowProprietary, and tel URIs are supported by default.

> HTML Purifier 4.7.0 is a bugfix release, collecting two years
+worth of accumulated bug fixes.

**Comment by dev-101** [comment]
Not sure what's the point of above log? I am one of the users who reported this bug initially... it's unrelated to the current 4.9.3 release - go on test it yourself ;)

**Comment by ied3vil** [comment]
> Not sure what's the point of above log? I am one of the users who reported this bug initially... it's unrelated to the current 4.9.3 release - go on test it yourself ;)
> 
> Btw. how can a release from June last year fix issue in PHP that was released in November? :)

have you heard of beta and pre release versions?

**Comment by dev-101** [comment]
Because it wasn't at that time, trust me.

Anyway, please don't revamp old and closed issues.
