### ISSUE TITLE
itemActions.php need to filter meta request

### ISSUE THREAD

**Issue by plonknimbuzz** [osclass/Osclass#2253]
https://github.com/osclass/Osclass/blob/cbf31336888fc3e5f730ea8b35e4d06610b87935/oc-includes/osclass/ItemActions.php#L151
```
$meta = Params::getParam("meta");
    
if($meta!='' && count($meta)>0) {
//if(is_array($meta) && !empty($meta)) { //PHP 7.2 supp >> recommend
	foreach($_meta as $_m) {
		$meta[$_m['pk_i_id']] = (isset($meta[$_m['pk_i_id']]))?$meta[$_m['pk_i_id']]:'';
	}

	$mField = Field::newInstance();
	....
}
```

**Comment by garciademarina** [comment]
Hi there, 
I don't see any reason why we should change it. 
$_meta variable will be an empty array if no custom fields are attached to the selected category. 
Regards
