### ISSUE TITLE
PHP Notice:  Undefined index: s_title / oc-includes/osclass/helpers/hDefines.php on line 499

### ISSUE THREAD

**Issue by mouratboura** [osclass/Osclass#2254]
While I add adsense code into admin area, after click save, URL is redirecting to 
oc-admin/index.php?page=appearance&action=render&file=oc-content/themes/osclasswizards/admin/settings.php  and not saving, also debug error recording below;

[10-Apr-2018 17:21:11 Europe/Madrid] PHP Notice:  Undefined index: s_title in /home/folder/public_html/www.mysite.com/oc-includes/osclass/helpers/hDefines.php on line 499

**Comment by garciademarina** [comment]
This issue is seems related to the theme, try to contact with the author.

**Comment by mouratboura** [comment]
it is also occuring even for zero installed BENDER theme, this is indicating that it is not relared with theme...Something else but, I can not solve it...
