### ISSUE TITLE
Category.php  bugs

### ISSUE THREAD

**Issue by wahidmounir** [osclass/Osclass#2255]
in public function listWhere() line 92

`$this->dao->select( sprintf("a.*, b.*, c.i_num_items, FIELD(fk_c_locale_code, '%s') as locale_order", $this->dao->connId->real_escape_string($this->_language) ) );`

_language variable is an array which generate a bug in the SQL query and the correct value to pass is _language[pk_c_coe]
the query becomes 
`$this->dao->select( sprintf("a.*, b.*, c.i_num_items, FIELD(fk_c_locale_code, '%s') as locale_order", $this->dao->connId->real_escape_string($this->_language[pk_c_code]) ) );`

same thing for function

listEnabled() in line 127 in category.php

**Comment by Asifcu** [comment]
My site name is www.sellbaazar.com
How to show only ad title without showing details and photo?

**Comment by garciademarina** [comment]
from the constructor of Category model class: 

```
...
            if($l == '') {
                $l = osc_current_user_locale();
            }

            $this->_language   = $l;
...
```

osc_current_user_locale() should return always a string. 

Can you give me more information about how to reproduce your issue ? 

Regards
