### ISSUE TITLE
$_SERVER["REMOTE_ADDR"] doesnt exists in my linux machine

### ISSUE THREAD

**Issue by Divyanshu29** [osclass/Osclass#2262]
I get Undefined index: REMOTE_ADDR in /var/www/html/bWAPP/security.php error when i try to run a php file. Tried phpinfo() but didnt find REMOTE_ADDR. The problem being when i run this on web i get a while blank screen.

**Comment by garciademarina** [comment]
Are your web server behind a proxy? 

Try to provide more information like, hosting provider, web server, php version, ...? I will try to reproduce your issue. 

Regards

**Comment by Divyanshu29** [comment]
I'm using Apache2.0 and yes it's configured for proxy with burp suit and PHP version is 7.0 and im facing this issue while running bWAPP in Kali linux

**Comment by Divyanshu29** [comment]
Could u be please more discriptive I'm kind of newbie...
