### ISSUE TITLE
Osclass Market Server and Osclass sites Dependancy

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#2297]
The last 3 days all my Osclass are slow in the dashboard functions.

The last 3 days now i get 504 Gateway Time-outs trying to see if Osclass Market is slow or something.

Both issues related.

This is a VERY old problem that should somehow be fixed. When Osclass Market server/site has some problems, ALL Osclass sites installations also suffer from extreme slowness in the dashboard and probably other areas.

So either this should be fixed and problems at Osclass Market server have nothing to do with Osclass sites or  somebody must tell us what to REMOVE from the code to totally be free from Osclass Market hicupps.

I think we have suffered enough from this old problem. It has been brought up several times, in several posts in the forums, and apparently nothing has been done.

**Comment by dev-101** [comment]
Hi, there is no way I can test this, but you can try this modification:
https://github.com/osclass/Osclass/commit/bfe61516d265fa8ec64e66f5af6b96e9ddd63f43

file: https://raw.githubusercontent.com/osclass/Osclass/bfe61516d265fa8ec64e66f5af6b96e9ddd63f43/oc-includes/osclass/utils.php

NOTE: this fix is very strict and it will limit file downloads operations down to 1 second! Beware if your server has limited connectivity speed (also at another end), downloads may fail! Later the limit can be raised to something like 2 or 3 seconds.

**Comment by eurobank** [comment]
What do you mean "downloads" ? From Market ? We have NOT connected any sites of ours with Market.

Is this what you mean ? 

Because the slowdown happens NOT when doing something with Market but in general usage of Dashboard.

**Comment by dev-101** [comment]
It doesn't matter, everything like update checks, banners etc. is considered as download.

**Comment by eurobank** [comment]
Ok, then i will try that and update here with my findings.

Many thanks dev101.

**Comment by dev-101** [comment]
You may see some warnings about **oc-admin modern theme**, ignore it for now, it is not dangerous, it happens when data isn't fetched and that part doesn't check for that event.

**Comment by eurobank** [comment]
@dev-101 

That fix seems to work but enabling debug log i see some notices. But you warned me about. Are those ok ? There are two kind of notices.

--- Not related to changes ---

Sorry !
