### ISSUE TITLE
Admin username is required

### ISSUE THREAD

**Issue by Adyyda** [osclass/Osclass#2301]
![Screen Shot 2019-06-02 at 22 27 40](https://user-images.githubusercontent.com/5921012/58766382-a0b77400-8586-11e9-8569-8409563ae665.png)

When you make a clean install of osclass 3.8, you can't proceed further if you use a custom username. This is a serious issue since you must use only admin.

**Comment by dev-101** [comment]
Just checked, it worked without any issues. There is no such code that restricts you to use 'admin', it is just a pre-entered value/suggestion.

**Comment by Adyyda** [comment]
Did you made a clean install and were able to insert for instance Admin-username? I tried several variants and each time i get that error (you can see the image). It worked only when i used the default username.

I have made the install in a subdomain.

Also, just noticed another issue. The latest osclass pack comes with Bender theme 3.1.5. When i enter admin area i get a message that a theme update exist (3.2.0) but you can't update it. There is no such button. I go to the market, download the 3.2 version and in replaces the 3.1.5 and when i check it i see this button from mobile mode? That issue doesn't exist in 3.1.5? 

![Screen Shot 2019-06-03 at 07 55 02](https://user-images.githubusercontent.com/5921012/58777140-85c02080-85d5-11e9-9076-b0687bfd9166.png)
![Screen Shot 2019-06-03 at 07 55 24](https://user-images.githubusercontent.com/5921012/58777141-8658b700-85d5-11e9-8241-4b7503f169ee.png)
![Screen Shot 2019-06-03 at 07 55 43](https://user-images.githubusercontent.com/5921012/58777142-8658b700-85d5-11e9-8821-b8dc632e9b93.png)

**Comment by dev-101** [comment]
Your issue with username is related to something else in your setup, there is no such code that will restrict you. Yes, it was a clean install.

About another issue, do not post them in unrelated section. You have to create and connect your Market account inside your installation, also make sure your server can connect.

**Comment by Adyyda** [comment]
Ok. What username did you try?

I am asking because right now i have downloaded osclass from the site, and i had a clean install in the main domain and the same thing happens?

[osclass.3.8.0.zip](https://github.com/osclass/Osclass/files/3247849/osclass.3.8.0.zip)

In the end it seems that we cant use a username like User-Admin "-" seems to not be accepted by the script and if so, you should put a note regarding this in the installer. The moment i removed - and used a shorter name, it worked?

**Comment by Adyyda** [comment]
I went into admin area and tried to change the username and it can't be changed if i use User-Admin. Turns out that you can add only a-z and numbers but no special characters? 

![1](https://user-images.githubusercontent.com/5921012/58808096-fd1ba180-8621-11e9-9d1f-89da3b290fc8.jpg)

**Comment by dev-101** [comment]
You can remove regex validation part if you like, but I am not sure if that is generally a good idea. Why do you want to use special characters for username? You can use underscore _ . Also, numbers _are allowed_.

Keep it safe & simple.
