### ISSUE TITLE
Server Is Timing Out

### ISSUE THREAD

**Issue by nootkan** [osclass/Osclass#2310]
Is the osclass server down?  I am trying to log in to the forum but I keep getting server time out issues.  I have tried on three different computers in three different homes with the same result. Cannot even get to the official website.

**Comment by patriksh** [comment]
@nootkan 

Osclass 3.9.0 -> https://github.com/navjottomer/osclass
Osclass Market -> https://market.osclasscommunity.com/
Osclass Docs -> https://osclass.gitbook.io/osclass-docs/
Osclass Forum -> https://forums.osclasscommunity.com/
Osclass Discourse Forum -> https://osclass.discourse.group/
