### ISSUE TITLE
"The king is dead, long live the king"

### ISSUE THREAD

**Issue by patriksh** [osclass/Osclass#2311]
Osclass 3.9.0 -> https://github.com/navjottomer/osclass
Osclass Market -> https://market.osclasscommunity.com/
Osclass Docs -> https://osclass.gitbook.io/osclass-docs/
Osclass Forum -> https://forums.osclasscommunity.com/
Osclass Discourse Forum -> https://osclass.discourse.group/

**Comment by Dis555** [comment]
Osclass Market -> https://osclass.market/

> Osclass 3.9.0 -> https://github.com/navjottomer/osclass
> Osclass Market -> https://market.osclasscommunity.com/
> Osclass Docs -> https://osclass.gitbook.io/osclass-docs/
> Osclass Forum -> https://forums.osclasscommunity.com/
> Osclass Discourse Forum -> https://osclass.discourse.group/

But in this fork 3.9.0 version, so far with a lot of bugs. 
And all these sites have nothing to do with the official Osclass.  
While there is such a version (https://osclass-pro.com/en/download.html) with fixes of the official version.
The market is better - https://osclass.market/

**Comment by patriksh** [comment]
@Dis555 There is no "official" anymore. And there is not a lot of bugs at all.

I see you're continuing your way, not supporting the open-source community at all and just promoting your own paid shit.

Also be kind and remove my plugins from osclass.market.

**Comment by Dis555** [comment]
> @Dis555 There is no "official" anymore. And there is not a lot of bugs at all.
> 
> I see you're continuing your way, not supporting the open-source community at all and just promoting your own paid shit.

As you put it "shit" - you advertise.  And we were the first to create an affordable website with all the free plugins.
I think many draw conclusions on the way you communicate. Is it worth it to deal with you and your sites.

**Comment by patriksh** [comment]
@Dis555 I do, but advertise non-profit sites and the future of Osclass.

**Comment by patriksh** [comment]
@Dis555 lmao I also love the 10$ phone login plugin (probably modified copy of mine), while mine is also published there, but for free.

**Comment by Dis555** [comment]
> @Dis555 I do, but advertise non-profit sites and the future of Osclass.

I also gave links to a free fixed latest Osclass. And on a site on which there are almost all free plugins, languages, locations and themes. I’m not selling anything to anyone here.

**Comment by patriksh** [comment]
But saying "All this sites have nothing to do with official Osclass" and "This market is better"?

Whatever, I'm done.

**Comment by Dis555** [comment]
> @Dis555 lmao I also love the 10$ phone login plugin (probably modified copy of mine), while mine is also published there, but for free.

Amazing. What does your comment have to do with me?
And you have a very negative attitude towards everything ... that is not yours.
However, I remember that you wrote exactly the same evil comments earlier in the official forum. For which you were banned there. You must learn to behave with dignity, and not write all sorts of evil things.
