### ISSUE TITLE
LDAP SUPORT?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [osclass/Osclass#2319]
LDAP?

**Comment by patriksh** [comment]
https://github.com/mindstellar/Osclass/

**Comment by AnonymousWebHacker** [comment]
Tnks, but I change to Osclass evolution https://forum.osclass-evo.com

**Comment by patriksh** [comment]
> Tnks, but I change to Osclass evolution https://forum.osclass-evo.com

Why support closed-source version?

**Comment by AnonymousWebHacker** [comment]
It is not because it is closed or open, but there are more changes, it is seen that there is more interest in improving. I really apologize for answering you like this. I prefer open things as you say, only if the repo is dead, I decided to change, otherwise I will stay here.

**Comment by AnonymousWebHacker** [comment]
If you notice, https://github.com/osclass/Osclass/ the newest commit is 2 years ago

**Comment by patriksh** [comment]
@AnonymousWebHacker -> https://github.com/mindstellar/Osclass/
