### ISSUE TITLE
Locations doesn't support multilanguage

### ISSUE THREAD

**Issue by extr** [osclass/Osclass#245]
When you want to add new Country, Region, City in Locations settings it is not possible to add another translations. This issue is also valid for 2.3.7 version

**Comment by songlianglee** [comment]
Hello [conejoninja](/conejoninja)
Then 
Should I Create  new table "t_region_en_US" without importing ?????

**Comment by maxrubino** [comment]
It is not necessary to add a new table. I did it just working with .po
