### ISSUE TITLE
[bug] in adding regions on develop branch

### ISSUE THREAD

**Issue by trains58554** [osclass/Osclass#376]
Hi 

When I try to add a region it says it has been added but it does not get added to the database. If I then go into the database and add it it shows up and I can then add cities. Adding countries works just fine as well it is just the region that is not working.

Jay

**Comment by AweeGander** [comment]
Hello Conejo

i am having the same issue at trains58554 

ReferenceError: hook_load_cities is not defined
	hook_load_cities();

on every install. can you tell me how to fix this.. i have been told that it is my hosting provider install problem but im not to sure. would like to know for sure before i move hosting
