### ISSUE TITLE
Issue on search Pagination & sCategory=Array

### ISSUE THREAD

**Issue by jimwinny** [osclass/Osclass#507]
Hello,

I realize that a lot of site creating with OSCLASS have the same issue. Has anyone tried to search in more than 1 category (so select 3 categories to search in but not all) and then navigating on page 2 of given search results, the search is showing ALL ads of the site again, and not keeping the category selection, seems the sCategory=Array is not working ? 

So this :

http://localhost/index.php?page=search&sOrder=dt_pub_date&iOrderType=desc&criteres=&region=&ville=&categorie=Array&sPriceMin=&sPriceMax=&iPage=2

should give same result as this

http://localhost/index.php?page=search&sOrder=dt_pub_date&iOrderType=desc&sPattern=&sRegion=&sCity=&sCategory%5B%5D=9&sCategory%5B%5D=9003&sCategory%5B%5D=10&sCategory%5B%5D=10003&sPriceMin=&sPriceMax=&iPage=2

but this is not working. How to remove the combine in Array ? Any expert advise ? Thanks !!!!

**Comment by aSakwe** [comment]
hello,i'm using osclass and i i'm a newbie.when i run a search my pagination does show the search results and paginations at the bottom but when i click on next page ,it takes me to next page and shoes me number of items found but i cant be able to list the items.
here is the link from the pagination----->
http://localhost/search/sParams,cameroun%2Fdouala%2Fiphone/region,Cameroun/city,Douala/pattern,iphone/iPage,2
: "iphone"                                        31 ads

    There are no results matching "iphone"
i get the above message 
please help but when i jst load the site pagination loads well and i can go to page 2,3 and above.
please help been on this for almost 2weeks and my confidence is dropping i don't know what to do.

**Comment by fazil1122** [comment]
Search box not working while hosting,but in the same project sucessfully working in localhost
www.onlinechantha.com
help meeeee
