### ISSUE TITLE
[bug] in oc-includes/osclass/model/Search.php listCountries.

### ISSUE THREAD

**Issue by trains58554** [osclass/Osclass#509]
[quote]
I think that the following is a bug in the original code (osclass 3.0.1).
I had to change it as follows, in order for me to have this function works correctly.
In Search.php under oc-includes/osclass/model:

public function listCountries($zero = ">", $order = "items DESC")
 {
   return CountryStats::newInstance()->listCities($zero, $order);
 }

Change to:
   return CountryStats::newInstance()->listCountries($zero, $order);
[/quote]

reference 
http://forums.osclass.org/general-help/bug-in-function-listcountries/

**Comment by colorbis** [comment]
How to make a list of each county (Regions ) followed by the cities that are in that county (Regions).
I need somebody's code that can help me because I can not do it.

I use the bender theme.

thank you very much and wish you a good day.

Regions
city
city
city
city
Regions
city
city
city
