### ISSUE TITLE
Delete comment issue - "Probable invalid request."

### ISSUE THREAD

**Issue by ghost** [osclass/Osclass#641]
Using osc 3.1, modern theme with no edits.

Logged as a user, from the item page I attempted to delete a comment and received the message "Probable invalid request."

Deleting the comment from the admin panel works fine.

item page query string: 
index.php?page=item&action=delete_comment&id=12&comment=1

admin query string:
index.php?page=comments&action=delete&id=1

The function setting off the message:
\helpers\hSecurity.php

<pre> 
function osc_csrf_check($drop = true) {
    if(Params::getParam('CSRFName')=='' || Params::getParam('CSRFToken')=='') {
        exit(__("Probable invalid request."));
    }
    $name = Params::getParam('CSRFName');
    $token = Params::getParam('CSRFToken');
    if (!osc_csrfguard_validate_token($name, $token, $drop)) {
        exit(__("Invalid CSRF token."));
    }
}
</pre>

Let me know if any more info is needed to recreate. Thanks

**Comment by kw3ku** [comment]
i have a big problem on my osclass platform now. its called CSRF token is invalid.
