### ISSUE TITLE
One of the plugins changed the order of the admin menu, how to solve this?

### ISSUE THREAD

**Issue by echteinfachtv** [osclass/Osclass#915]
I tried out some plugins of osclass. Later on I realized that the order of the menu items in the left-floated menu bar was changed. 

Now, instead starting with "dashboard" it starts with "plugins". 
1. How can I find the responsible plugin? ... I guess it was [osc_terms](http://forums.osclass.org/plugins/%28new-plugin%29-terms-and-conditions-beta-version/) btw.
2. How can I have the default sorting?
3. How can we prevent plugins changing the menu order?

Thanks!

**Comment by isohut** [comment]
In my case the problematic plugin was: Sitemap Plugin, from: http://tuffclassified.com

**Comment by dev-101** [comment]
Why are you posting link to this website, when it does not have anything related to plugin itself?

**Comment by isohut** [comment]
To help other people solve their problems, is that wrong?

On Wed, Oct 21, 2015 at 1:39 PM, dev-101 <notifications@github.com> wrote:

> Why are you posting link to this website, when it does not have anything
> related to plugin itself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osclass/Osclass/issues/915#issuecomment-149850818>.
>



-- 
Сайт за безплатни обяви в България
http://www.isohut.eu

**Comment by dev-101** [comment]
Then post the proper link.

**Comment by isohut** [comment]
I'm not advertise anything, chill out mate...whatever, don't be so evil

**Comment by dev-101** [comment]
OK :)
