### ISSUE TITLE
PermLinks enabling causing URL Error - Please help

### ISSUE THREAD

**Issue by bengalliboy** [osclass/Osclass#993]
I am using bcute theme with latest osclass version here: KhansList.com
On enabling the permlinks, I get this error on the generated link:

On front page (main.php) It displays the location and # of ads okay however when clicking to it, it goes to "khanslist.com/-c" and thus results on 404 error page not found.

Can someone please help??

**Comment by vksgrg** [comment]
Still issue not resolved

we have enabled the permalinks in oc-admin panel setting page

and url is also converted to seo friendly urls , but when we go to the listing page showing error 404
